package scenarios.Custom;

import org.testng.annotations.Test;

import auto.framework.ReportLog;
import auto.framework.TestBase;
import auto.framework.web.WebControl;
import common.TestDataHandler;
import common_scenarios.VIP_Common;
import pageobjects.VIPCustomPage;
import pageobjects.VIPLandingPage;
import pageobjects.VIPOverviewPage;


public class Financials_Custom_19_PreTaxROICDecomp extends TestBase{

	@Test(priority=1)
	public void CUSTOM_PreTaxROICDecomp () throws Exception {
		ReportLog.setTestName("CUSTOM - Pre-Tax ROIC Decomposition");
		TestDataHandler testDataHandler = TestDataHandler.loadTestData("Sheet", "RowSelection='Test1'");

        /* Pre-Tax ROIC Decomposition Dashboard
		 * Author: alyssa.kay.n.mababa*/
		
		ReportLog.setTestCase("CUSTOM_Reg_Auto_163");
		VIP_Common.LogInPage(testDataHandler);
		WebControl.waitForPageToLoad(45);
		VIPCustomPage.contents.ModalCloseButton.click();
        Thread.sleep(2000);
		VIPCustomPage.contents.UserEIDHeader.verifyDisplayed(true, 10);
		VIPLandingPage.contents.OverviewButton.hover();
		VIPLandingPage.contents.OverviewButtonTooltip.verifyText("Overview");
		VIPLandingPage.contents.OverviewButton.click();
		WebControl.waitForPageToLoad(45);
		Thread.sleep(2000);
		VIPOverviewPage.contents.OverviewTitle.verifyDisplayed(true, 30);
		//Navigate to Financials Tab		
		//VIPCustomPage.contents.FinancialsTabIcon.hover();
		//VIPCustomPage.contents.FinancialsTabIcon.verifyDisplayed(true, 10);
		VIPCustomPage.contents.FinancialsTab.hover();
		VIPCustomPage.contents.FinancialsTab.verifyDisplayed(true, 10);
		VIPCustomPage.contents.FinancialsTab.click();
		WebControl.waitForPageToLoad(45);
		Thread.sleep(2000);
		VIPLandingPage.contents.HelpIcon.hover();
		VIPCustomPage.contents.SelectDashboardDropdown.waitForExist(true, 10);
		VIPCustomPage.contents.SelectDashboardDropdown.click();
		//Navigate to Pre-Tax ROIC Decomposition Dashboard
		VIPCustomPage.contents.PreTaxROICDecompMenu.click();
		WebControl.waitForPageToLoad(45);
		Thread.sleep(2000);
        VIPCustomPage.contents.LeftHandChartHeader.verifyDisplayed(true, 5);
		VIPCustomPage.contents.LeftHandChartHeader.verifyText("RETURN ON INVESTED CAPITAL (ROIC) DECOMPOSITION");
		VIPCustomPage.contents.LeftHandChartNote.verifyDisplayed(true, 5);
		VIPCustomPage.contents.LeftHandChartNote.verifyText("Click on the KPI box to view peer comparison");
		VIPCustomPage.contents.RightHandChartHeader.verifyDisplayed(true, 5);
		VIPCustomPage.contents.RightHandChartHeader.verifyText("PRE-TAX RETURN ON INVESTED CAPITAL");
        VIPCustomPage.contents.PreTaxROICBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.EBITMARGINBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.CAPITALEFFICIENCYBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.EBITDAMarginBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.DARevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.WorkingCapitalRevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.NetPPERevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.GoodwillIntangiblesRevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.NetOtherAssetsRevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.COGSRevenueBox.verifyDisplayed(true, 5);
		VIPCustomPage.contents.SGARevenueBox.verifyDisplayed(true, 5);
        VIPCustomPage.contents.MultiplySymbol.verifyDisplayed(true, 5);
        VIPCustomPage.contents.MinusSymbol.verifyDisplayed(true, 5);
		VIPCustomPage.contents.CapEffText.verifyDisplayed(true, 5);
		VIPCustomPage.contents.CapEffText.verifyText("1/sum of");
        VIPCustomPage.contents.ROICBetterLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICBetterLegendText.verifyText("Better than peer median");
		VIPCustomPage.contents.ROICWorseLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICWorseLegendText.verifyText("Worse than peer median");
		VIPCustomPage.contents.ROICInlineLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICInlineLegendText.verifyText("In-line with peer median");
        WebControl.takeScreenshot("Custom_Reg_Auto_163");
        
        ReportLog.setTestCase("CUSTOM_Reg_Auto_166");
		VIPCustomPage.contents.EBITMARGINiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.EBITMARGINiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.EBITMTooltip);
		VIPCustomPage.contents.EBITMARGINiIcon.click();
		VIPCustomPage.contents.CAPITALEFFICIENCYiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.CAPITALEFFICIENCYiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.CAPEFFTooltip);
		VIPCustomPage.contents.CAPITALEFFICIENCYiIcon.click();
		VIPCustomPage.contents.EBITDAMarginiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.EBITDAMarginiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.EBITDATooltip);
		VIPCustomPage.contents.EBITDAMarginiIcon.click();
		VIPCustomPage.contents.DARevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.DARevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.DATooltip);
		VIPCustomPage.contents.DARevenueiIcon.click();
		VIPCustomPage.contents.WorkingCapitalRevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.WorkingCapitalRevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.WCRTooltip);
		VIPCustomPage.contents.WorkingCapitalRevenueiIcon.click();
		VIPCustomPage.contents.NetPPERevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.NetPPERevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.NPPETooltip);
		VIPCustomPage.contents.NetPPERevenueiIcon.click();
		VIPCustomPage.contents.GoodwillIntangiblesRevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.GoodwillIntangiblesRevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.GITooltip);
		VIPCustomPage.contents.GoodwillIntangiblesRevenueiIcon.click();
		VIPCustomPage.contents.COGSRevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.COGSRevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.COGSTooltip);
		VIPCustomPage.contents.COGSRevenueiIcon.click();
		VIPCustomPage.contents.SGARevenueiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.SGARevenueiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.SGATooltip);
		VIPCustomPage.contents.SGARevenueiIcon.click();
		VIPCustomPage.contents.ROICiIcon.hover();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText("Click here to view definitions");
		VIPCustomPage.contents.ROICiIcon.click();
		VIPCustomPage.contents.PreTaxROICDecompTooltipText.verifyText(testDataHandler.ROICTooltip);
		VIPCustomPage.contents.ROICiIcon.click();
        WebControl.takeScreenshot("Custom_Reg_Auto_166");

        ReportLog.setTestCase("Q2A_Reg_Auto_167");
		VIPCustomPage.contents.EBITMARGINBox.hover();
		VIPCustomPage.contents.EBITMARGINBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("EBIT MARGIN");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.CAPITALEFFICIENCYBox.hover();
		VIPCustomPage.contents.CAPITALEFFICIENCYBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("CAPITAL EFFICIENCY");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.EBITDAMarginBox.hover();
		VIPCustomPage.contents.EBITDAMarginBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("EBITDA MARGIN");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.DARevenueBox.hover();
		VIPCustomPage.contents.DARevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("D&A / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.WorkingCapitalRevenueBox.hover();
		VIPCustomPage.contents.WorkingCapitalRevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("WORKING CAPITAL / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.NetPPERevenueBox.hover();
		VIPCustomPage.contents.NetPPERevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("NET PPE / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.GoodwillIntangiblesRevenueBox.hover();
		VIPCustomPage.contents.GoodwillIntangiblesRevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("GOODWILL & INTANGIBLES / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.NetOtherAssetsRevenueBox.hover();
		VIPCustomPage.contents.NetOtherAssetsRevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("NET OTHER ASSETS / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.COGSRevenueBox.hover();
		VIPCustomPage.contents.COGSRevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("COGS / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.SGARevenueBox.hover();
		VIPCustomPage.contents.SGARevenueBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("SG&A / REVENUE");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		VIPCustomPage.contents.PreTaxROICBox.hover();
		VIPCustomPage.contents.PreTaxROICBox.click();
        VIPCustomPage.contents.RightHandChartHeader.verifyText("PRE-TAX RETURN ON INVESTED CAPITAL");
        VIPCustomPage.contents.ROICTargetCompLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegend.verifyDisplayed(true, 5);
		VIPCustomPage.contents.ROICPeerMedianLegendText.verifyText("Peer Median");
		WebControl.takeScreenshot("Q2A_Reg_Auto_167");
		
		ReportLog.setTestCase("Q2A_Reg_Auto_169");
		VIPCustomPage.contents.PreTaxROICDecompToggleButton.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompToggleLabel.verifyText("Detailed Peer Comparison");
		VIPCustomPage.contents.PreTaxROICDecompToggleButton.click();
		VIPCustomPage.contents.PreTaxROICDecompFirstPeriodHeader.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompSecondPeriodHeader.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompThirdPeriodHeader.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompFirstPeriodChart.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompSecondPeriodChart.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompThirdPeriodChart.verifyDisplayed(true, 5);
		WebControl.takeScreenshot("Q2A_Reg_Auto_169");

		ReportLog.setTestCase("Q2A_Reg_Auto_170");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.verifyDisplayed(true, 5);
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndPreTaxROICMMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndEBITMarginMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndEBITDAMarginMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndCOGSRevenueMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndSGARevenueMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndDARevenueMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndCapitlEfficiencyMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndWorkingCapitalMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndNetPPERevenueMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndGWIntanRevMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndNetOtherAssRevMenu.verifyDisplayed(true, 5);
		VIPCustomPage.contents.IndEBITMarginMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("EBIT MARGIN");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndEBITDAMarginMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("EBITDA MARGIN");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndCOGSRevenueMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("COGS / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndSGARevenueMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("SG&A / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndDARevenueMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("D&A / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndCapitlEfficiencyMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("CAPITAL EFFICIENCY");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndWorkingCapitalMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("WORKING CAPITAL / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndNetPPERevenueMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("NET PPE / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndGWIntanRevMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("GOODWILL & INTANGIBLES / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndNetOtherAssRevMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("NET OTHER ASSETS / REVENUE");
		VIPCustomPage.contents.PreTaxROICDecompSIDropdown.click();
		VIPCustomPage.contents.IndPreTaxROICMMenu.click();
		VIPCustomPage.contents.PreTaxROICDecompDetailedChartHeader.verifyText("PRE-TAX RETURN ON INVESTED CAPITAL");
		WebControl.takeScreenshot("Q2A_Reg_Auto_170");

		//Tagline and Footnote - Added 2/10/2021 by alyssa.kay.n.mababa
		//Tagline and Footnote - Updated 2/25/2021 by charisma.l.desipeda
		ReportLog.setTestCase("CUSTOM_RT_TC_Tagline_Footnote_048_049_050");
		VIPLandingPage.contents.HelpIcon.hover();
		Thread.sleep(1000);
		String PreTaxROICDecompTagline = VIPCustomPage.contents.DefaultTagline.getText();
		String PreTaxROICDecompFootnote = VIPCustomPage.contents.DefaultFootnote.getText();
		if((PreTaxROICDecompTagline.equals("ROIC Decomposition")) & (PreTaxROICDecompFootnote.equals("Note: Numbers may not add up due to rounding; Source: S&P Capital IQ; Annual and Quarterly reports; Accenture Client Value Services."))) {
			VIPCustomPage.contents.DefaultTagline.hover();
			VIPCustomPage.contents.TooltipText.verifyDisplayed(true, 5);
			VIPCustomPage.contents.TooltipText.verifyText("Click to edit tagline");
			VIPCustomPage.contents.DefaultFootnote.hover();
			VIPCustomPage.contents.TooltipText.verifyDisplayed(true, 5);
			VIPCustomPage.contents.TooltipText.verifyText("Click to edit footnote");
			VIPCustomPage.contents.DefaultFootnote.click();
			Thread.sleep(1000);
			VIPCustomPage.contents.TaglineFootnoteModalTitle.verifyText("Add Tagline and Footnote:");
			VIPCustomPage.contents.ModalTaglineHeader.verifyText("Tagline:");
			VIPCustomPage.contents.TaglineTextBox.sendKeys("_test");
			Thread.sleep(1000);
			VIPCustomPage.contents.ModalFootnoteHeader.verifyText("Footnote:");
			VIPCustomPage.contents.FootnoteTextBox.sendKeys("_test");
			Thread.sleep(1000);
			VIPCustomPage.contents.TaglineCount.verifyText("257 characters remaining");
			VIPCustomPage.contents.FootnoteCount.verifyText("713 characters remaining");
			VIPCustomPage.contents.ModalApplyButton.click();
			Thread.sleep(1000);
			VIPCustomPage.contents.DefaultTagline.verifyText("ROIC Decomposition_test");
			VIPCustomPage.contents.DefaultFootnote.verifyText("Note: Numbers may not add up due to rounding; Source: S&P Capital IQ; Annual and Quarterly reports; Accenture Client Value Services._test");
		}
		else {
			VIPCustomPage.contents.DefaultTagline.hover();
			VIPCustomPage.contents.TooltipText.verifyDisplayed(true, 5);
			VIPCustomPage.contents.TooltipText.verifyText("Click to edit tagline");
			VIPCustomPage.contents.DefaultFootnote.hover();
			VIPCustomPage.contents.TooltipText.verifyDisplayed(true, 5);
			VIPCustomPage.contents.TooltipText.verifyText("Click to edit footnote");
			VIPCustomPage.contents.DefaultFootnote.click();
			Thread.sleep(1000);
			VIPCustomPage.contents.TaglineFootnoteModalTitle.verifyText("Add Tagline and Footnote:");
			VIPCustomPage.contents.ModalTaglineHeader.verifyText("Tagline:");
			VIPCustomPage.contents.TaglineTextBox.clear();
			VIPCustomPage.contents.TaglineTextBox.sendKeys("ROIC Decomposition_test");
			Thread.sleep(1000);
			VIPCustomPage.contents.ModalFootnoteHeader.verifyText("Footnote:");
			VIPCustomPage.contents.FootnoteTextBox.clear();
			VIPCustomPage.contents.FootnoteTextBox.sendKeys("Note: Numbers may not add up due to rounding; Source: S&P Capital IQ; Annual and Quarterly reports; Accenture Client Value Services._test");
			Thread.sleep(1000);
			VIPCustomPage.contents.TaglineCount.verifyText("257 characters remaining");
			VIPCustomPage.contents.FootnoteCount.verifyText("713 characters remaining");
			VIPCustomPage.contents.ModalApplyButton.click();
			Thread.sleep(1000);
			VIPCustomPage.contents.DefaultTagline.verifyText("ROIC Decomposition_test");
			VIPCustomPage.contents.DefaultFootnote.verifyText("Note: Numbers may not add up due to rounding; Source: S&P Capital IQ; Annual and Quarterly reports; Accenture Client Value Services._test");
		}
		VIPCustomPage.contents.DefaultFootnote.click();
		VIPCustomPage.contents.TaglineTextBox.sendKeys("_test");
		Thread.sleep(2000);
		VIPCustomPage.contents.FootnoteTextBox.sendKeys("_test");
		VIPCustomPage.contents.TaglineFootnoteModalCloseButton.click();
		VIPCustomPage.contents.DefaultTagline.verifyText("ROIC Decomposition_test");
		VIPCustomPage.contents.DefaultFootnote.verifyText("Note: Numbers may not add up due to rounding; Source: S&P Capital IQ; Annual and Quarterly reports; Accenture Client Value Services._test");
		WebControl.takeScreenshot("CUSTOM_RT_TC_Tagline_Footnote_048_049_050");
	}
}
