package scenarios.SHELDON;

import java.text.NumberFormat;
import org.testng.annotations.Test;
import auto.framework.ReportLog;
import auto.framework.TestBase;
import auto.framework.web.WebControl;
import auto.framework.web.WebControl1;
import common.TestDataHandler;
import common_scenarios.VIP_Common;
import pageobjects.SheldonWebsitePage;
import pageobjects.VIPLandingPage;
import pageobjects.VIPOverviewPage;
import pageobjects.VIPSheldonPage;

public class Sheldon_All extends TestBase {

	@Test
	public void WEBFunctionality_01_Landing () throws Exception {
		
		ReportLog.setTestName("Sheldon");
		TestDataHandler testDataHandler = TestDataHandler.loadTestData("Sheet", "RowSelection='Test1'");
		
		ReportLog.setTestCase("Sheldon_Login");
		VIP_Common.LogInPage(testDataHandler);
		Thread.sleep(3000);
		VIPLandingPage.contents.StartNowButton.click();
		if ((testDataHandler.ShowCVS.equals("Yes")) & (testDataHandler.ShowVCM.equals("Yes"))) {
		VIPLandingPage.contents.DisclaimerModal.verifyDisplayed(true, 10);
		VIPLandingPage.contents.DisclaimerProceedButton.click();
		VIPLandingPage.contents.NewDisclaimerText.verifyDisplayed(true, 10);
		VIPLandingPage.contents.NewDisclaimerText.verifyText(testDataHandler.VCMDisclaimer);
		VIPLandingPage.contents.NewDisclaimerProceedButton.click();
		VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.StartNowButton.verifyDisplayed(false);}
		else if ((testDataHandler.ShowCVS.equals("No")) & (testDataHandler.ShowVCM.equals("Yes"))) {
		VIPLandingPage.contents.NewDisclaimerText.verifyDisplayed(true, 10);
		VIPLandingPage.contents.DisclaimerModal.verifyDisplayed(false);
		VIPLandingPage.contents.NewDisclaimerText.verifyText(testDataHandler.VCMDisclaimer);
		VIPLandingPage.contents.NewDisclaimerProceedButton.click();
		VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.StartNowButton.verifyDisplayed(false);}
		else if ((testDataHandler.ShowCVS.equals("Yes")) & (testDataHandler.ShowVCM.equals("No"))) {
		VIPLandingPage.contents.DisclaimerModal.verifyDisplayed(true, 10);
		VIPLandingPage.contents.DisclaimerProceedButton.click();
		VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.StartNowButton.verifyDisplayed(false);}
		else { VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.DisclaimerModal.verifyDisplayed(false);
		VIPLandingPage.contents.NewDisclaimerText.verifyDisplayed(false);
		VIPLandingPage.contents.StartNowButton.verifyDisplayed(false);}
		VIPLandingPage.contents.CompanyNameTextbox.sendKeys("The Walt Disney Company");
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.waitForExist(true, 20);
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.waitForExist(true, 20);
		VIPLandingPage.contents.CompanyTypeAhead.click();
		Thread.sleep(4000);
		WebControl.waitForPageToLoad(45);
		Thread.sleep(4000);
		VIPOverviewPage.contents.OverviewTitle.waitForExist(true, 60);
		VIPOverviewPage.contents.GenerateFinancialReportButton.waitForExist(true, 10);
		Thread.sleep(4000);
		WebControl.takeScreenshot("Sheldon_Login");
		
		//Technology&BusinessLever
		ReportLog.setTestCase("Reg_Auto_001_TechnologySideMenu");
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 10);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuSheldonClick.verifyDisplayed(true, 5);
		VIPSheldonPage.contents.SideMenuSheldonClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		WebControl.takeScreenshot("Reg_Auto_001_TechnologySideMenu");
		
		ReportLog.setTestCase("Reg_Auto_002_TechnologyTitle");
		VIPSheldonPage.contents.SheldonTitle.verifyText("Top Mentions of Technology & Business Levers");
		WebControl.takeScreenshot("Reg_Auto_002_TechnologyTitle");
		
		ReportLog.setTestCase("Reg_Auto_003_TechnologySubTitle1");
		VIPSheldonPage.contents.SheldonSubTitle1.verifyDisplayed(true, 3);
		String SubHeader1 = VIPSheldonPage.contents.SheldonSubTitle1.getText();
		VIPSheldonPage.contents.SheldonSubTitle1.verifyText(SubHeader1);
		WebControl.takeScreenshot("Reg_Auto_003_TechnologySubTitle1");
		
		ReportLog.setTestCase("Reg_Auto_004_TechnologySubTitle2");
		VIPSheldonPage.contents.SheldonSubTitle2.verifyText("The information displayed here depends on the current Competitors List, please go to Refine Criteria settings under Competitors tab to adjust if needed.");
		WebControl.takeScreenshot("Reg_Auto_004_TechnologySubTitle2");
		
		ReportLog.setTestCase("Reg_Auto_005_RefineCriteria");
		VIPSheldonPage.contents.SheldonRefineCriteria.click();
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.CompetitorsTitle.verifyText("Competitors");
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 10);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuSheldonClick.verifyDisplayed(true, 5);
		VIPSheldonPage.contents.SideMenuSheldonClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		WebControl.takeScreenshot("Reg_Auto_005_RefineCriteria");
		
		ReportLog.setTestCase("Reg_Auto_006_InfoIcon");
		VIPSheldonPage.contents.InfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.InfoIconTooltip.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InfoIconTooltip.verifyText("Below heatmap is prepared based on the number of mentions of relevant technologies within Factiva articles. The darker the cell colour, the higher the number of mentions for the corresponding technology.");
		VIPSheldonPage.contents.InfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_006_InfoIcon");
		
		ReportLog.setTestCase("Reg_Auto_007_TargetCompany");
		VIPSheldonPage.contents.FirstCompany.verifyText("The Walt Disney Company");
		WebControl.takeScreenshot("Reg_Auto_007_TargetCompany");
		
		ReportLog.setTestCase("Reg_Auto_008_TechnologyLabels");
		VIPSheldonPage.contents.TechLabel1.verifyText("Clouds, PaaS, SaaS, Iaas");
		VIPSheldonPage.contents.TechLabel2.verifyText("AI");
		VIPSheldonPage.contents.TechLabel3.verifyText("Mobile");
		VIPSheldonPage.contents.TechLabel4.verifyText("Big Data");
		VIPSheldonPage.contents.TechLabel5.verifyText("Robots and Drones");
		VIPSheldonPage.contents.TechLabel6.verifyText("Extended Reality");
		VIPSheldonPage.contents.TechLabel7.verifyText("Security");
		VIPSheldonPage.contents.TechLabel8.verifyText("Blockchain");
		VIPSheldonPage.contents.TechLabel9.verifyText("IoT");
		VIPSheldonPage.contents.TechLabel10.verifyText("Social/Collaboration");
		VIPSheldonPage.contents.TechLabel11.verifyText("Crowdsourcing");
		VIPSheldonPage.contents.TechLabel12.verifyText("Autonomous Machines");
		VIPSheldonPage.contents.TechLabel13.verifyText("Human Augmentation");
		VIPSheldonPage.contents.TechLabel14.verifyText("3D Printing");
		VIPSheldonPage.contents.TechLabel15.verifyText("API Management Tools");
		VIPSheldonPage.contents.TechLabel16.verifyText("Business Process Automation (inc. RPA)");
		VIPSheldonPage.contents.TechLabel17.verifyText("Interactive");
		VIPSheldonPage.contents.TechLabel18.verifyText("Chatbots and Virtual Agents");
		VIPSheldonPage.contents.TechLabel19.verifyText("Quantum Computing");
		VIPSheldonPage.contents.TechLabel20.verifyText("Industry 4.0");
		VIPSheldonPage.contents.TechLabel21.verifyText("Advanced Analytics");
		WebControl.takeScreenshot("Reg_Auto_008_TechnologyLabels");
		
		ReportLog.setTestCase("Reg_Auto_009_TechFootnote");
		VIPSheldonPage.contents.Footnote.verifyDisplayed(true, 2);
		String TechFootnote = VIPSheldonPage.contents.Footnote.getText();
		VIPSheldonPage.contents.Footnote.verifyText(TechFootnote);
		WebControl.takeScreenshot("Reg_Auto_009_TechFootnote");
		
		ReportLog.setTestCase("Reg_Auto_010_KeyInsightsTitle");
		VIPSheldonPage.contents.KeyInsightsTitle.verifyDisplayed(true, 2);
		WebControl.takeScreenshot("Reg_Auto_010_KeyInsightsTitle");
		
		ReportLog.setTestCase("Reg_Auto_011_KeyInsightsMost");
		VIPSheldonPage.contents.KeyInsightsContentMost.verifyDisplayed(true, 2);
		String KeyInsightsMost = VIPSheldonPage.contents.KeyInsightsContentMost.getText();
		VIPSheldonPage.contents.KeyInsightsContentMost.verifyText(KeyInsightsMost, KeyInsightsMost.contains("most featured"));
		WebControl.takeScreenshot("Reg_Auto_011_KeyInsightsMost");
		
		ReportLog.setTestCase("Reg_Auto_012_KeyInsightsHighest");
		VIPSheldonPage.contents.KeyInsightsContentHighest.verifyDisplayed(true, 2);
		String KeyInsightsHighest = VIPSheldonPage.contents.KeyInsightsContentHighest.getText();
		VIPSheldonPage.contents.KeyInsightsContentHighest.verifyText(KeyInsightsHighest, KeyInsightsHighest.contains("highest"));
		WebControl.takeScreenshot("Reg_Auto_012_KeyInsightsHighest");
		
		ReportLog.setTestCase("Reg_Auto_013_NotCovered");
		VIPOverviewPage.contents.BackToSearchButton.hover();
		VIPOverviewPage.contents.BackToSearchButton.click();
		VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.CompanyNameTextbox.sendKeys("China Resources Pharmaceutical Group Limited");
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.waitForExist(true, 20);
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.verifyDisplayed(true, 20);
		VIPLandingPage.contents.CompanyTypeAhead.click();
		Thread.sleep(4000);
		WebControl.waitForPageToLoad(45);
		Thread.sleep(4000);
		VIPOverviewPage.contents.OverviewTitle.waitForExist(true, 60);
		VIPOverviewPage.contents.GenerateFinancialReportButton.waitForExist(true, 10);
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 10);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuSheldonClick.verifyDisplayed(true, 5);
		VIPSheldonPage.contents.SideMenuSheldonClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.SheldonTitle.verifyText("Top Mentions of Technology & Business Levers");
		VIPSheldonPage.contents.NOtCoveredNote.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.NOtCoveredNote.verifyText("This Company is not covered by Sheldon.");
		VIPSheldonPage.contents.KeyInsightsTitle.verifyDisplayed(false);
		WebControl.takeScreenshot("Reg_Auto_013_NotCovered");
		
		ReportLog.setTestCase("Reg_Auto_087_TopAcqNoDataAvailable");
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 3);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuAcqInvClick.verifyDisplayed(true, 3);
		VIPSheldonPage.contents.SideMenuAcqInvClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.AcquiTitle.verifyText("Acquisitions & Investments");
		VIPSheldonPage.contents.TopAcquisitionsTitle.verifyText("TOP ACQUISITIONS");
		VIPSheldonPage.contents.TopAcquisitionsNoData.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.TopAcquisitionsNoData.verifyText("No Data Available.");		
		WebControl.takeScreenshot("Reg_Auto_087_TopAcqNoDataAvailable");		
		
		ReportLog.setTestCase("Reg_Auto_088_TopInvNoDataAvailable");
		VIPSheldonPage.contents.TopInvestmentsTitle.verifyText("TOP INVESTMENTS");
		VIPSheldonPage.contents.TopInvestmentsNoData.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.TopInvestmentsNoData.verifyText("No Data Available.");				
		WebControl.takeScreenshot("Reg_Auto_088_TopInvNoDataAvailable");
				
		ReportLog.setTestCase("Reg_Auto_014_TechSheldonLogo");
		VIPLandingPage.contents.HelpIcon.hover();
		VIPOverviewPage.contents.BackToSearchButton.hover();
		VIPOverviewPage.contents.BackToSearchButton.click();
		VIPLandingPage.contents.CompanyNameTextbox.verifyDisplayed(true, 10);
		VIPLandingPage.contents.CompanyNameTextbox.sendKeys("The Walt Disney Company");
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.waitForExist(true, 30);
		Thread.sleep(3000);
		VIPLandingPage.contents.CompanyTypeAhead.verifyDisplayed(true, 30);
		VIPLandingPage.contents.CompanyTypeAhead.click();
		Thread.sleep(4000);
		WebControl.waitForPageToLoad(60);
		Thread.sleep(4000);
		VIPOverviewPage.contents.OverviewTitle.waitForExist(true, 60);
		VIPOverviewPage.contents.GenerateFinancialReportButton.waitForExist(true, 10);
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 10);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuSheldonClick.verifyDisplayed(true, 5);
		VIPSheldonPage.contents.SideMenuSheldonClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.SheldonTitle.verifyText("Top Mentions of Technology & Business Levers");
		VIPSheldonPage.contents.SheldonLogo.verifyDisplayed(true, 3);
		VIPSheldonPage.contents.SheldonLogo.click();
		WebControl.waitForPageToLoad(80);
		Thread.sleep(2000);
		WebControl.switchWithTitle("SheldonProfilerFrontend");
		Thread.sleep(2000);
		WebControl.takeScreenshot("Reg_Auto_014_TechSheldonLogo");
		
		//Technology Comparison with Sheldon Website
		ReportLog.setTestCase("Reg_Auto_015_3DPrinting");
		WebControl.waitForPageToLoad(60);
		Thread.sleep(3000);
		WebControl.waitForPageToLoad(60);
		Thread.sleep(3000);
		WebControl1.escape();
		WebControl.waitForPageToLoad(60);
		Thread.sleep(3000);
		SheldonWebsitePage.contents.SheldonProfilerHeader.verifyDisplayed(true, 2);
		SheldonWebsitePage.contents.SelectCompanyHeader.verifyDisplayed(true, 2);
		SheldonWebsitePage.contents.CompanyNameInput.verifyDisplayed(true, 2);
		SheldonWebsitePage.contents.CompanyNameInput.click();
		SheldonWebsitePage.contents.CompanyNameInput.sendKeys("The Walt Disney Company");
		Thread.sleep(3000);
		SheldonWebsitePage.contents.CompanyNameTypeAhead.waitForExist(true, 20);
		Thread.sleep(3000);
		SheldonWebsitePage.contents.CompanyNameTypeAhead.verifyDisplayed(true, 20);
		SheldonWebsitePage.contents.CompanyNameTypeAhead.click();
		Thread.sleep(4000);
		SheldonWebsitePage.contents.SearchButton.click();
		Thread.sleep(4000);
		WebControl.waitForPageToLoad(60);
		Thread.sleep(4000);
		SheldonWebsitePage.contents.Card1.click();
		SheldonWebsitePage.contents.Card2.click();
		SheldonWebsitePage.contents.NextButton.click();
		Thread.sleep(4000);
		WebControl.waitForPageToLoad(60);
		Thread.sleep(4000);
		//GetValuesinSheldonWebSite
		SheldonWebsitePage.contents.TechTable.verifyDisplayed(true, 5);
		String Column1Row1 = SheldonWebsitePage.contents.C1R1.getText();
		SheldonWebsitePage.contents.C1R1.verifyText(Column1Row1);
		String Column1Row2 = SheldonWebsitePage.contents.C1R2.getText();
		SheldonWebsitePage.contents.C1R2.verifyText(Column1Row2);
		String Column1Row3 = SheldonWebsitePage.contents.C1R3.getText();
		SheldonWebsitePage.contents.C1R3.verifyText(Column1Row3);
		String Column2Row1 = SheldonWebsitePage.contents.C2R1.getText();
		SheldonWebsitePage.contents.C2R1.verifyText(Column2Row1);
		String Column2Row2 = SheldonWebsitePage.contents.C2R2.getText();
		SheldonWebsitePage.contents.C2R2.verifyText(Column2Row2);
		String Column2Row3 = SheldonWebsitePage.contents.C2R3.getText();
		SheldonWebsitePage.contents.C2R3.verifyText(Column2Row3);
		String Column3Row1 = SheldonWebsitePage.contents.C3R1.getText();
		SheldonWebsitePage.contents.C3R1.verifyText(Column3Row1);
		String Column3Row2 = SheldonWebsitePage.contents.C3R2.getText();
		SheldonWebsitePage.contents.C3R2.verifyText(Column3Row2);
		String Column3Row3 = SheldonWebsitePage.contents.C3R3.getText();
		SheldonWebsitePage.contents.C3R3.verifyText(Column3Row3);		
		String Column4Row1 = SheldonWebsitePage.contents.C4R1.getText();
		int C4R1 = Integer.parseInt(Column4Row1);
		SheldonWebsitePage.contents.C4R1.verifyText(Column4Row1);
		String Column4Row2 = SheldonWebsitePage.contents.C4R2.getText();
		int C4R2 = Integer.parseInt(Column4Row2);
		SheldonWebsitePage.contents.C4R2.verifyText(Column4Row2);
		String Column4Row3 = SheldonWebsitePage.contents.C4R3.getText();
		SheldonWebsitePage.contents.C4R3.verifyText(Column4Row3);
		String Column5Row1 = SheldonWebsitePage.contents.C5R1.getText();
		SheldonWebsitePage.contents.C5R1.verifyText(Column5Row1);
		String Column5Row2 = SheldonWebsitePage.contents.C5R2.getText();
		SheldonWebsitePage.contents.C5R2.verifyText(Column5Row2);
		String Column5Row3 = SheldonWebsitePage.contents.C5R3.getText();
		SheldonWebsitePage.contents.C5R3.verifyText(Column5Row3);
		String Column6Row1 = SheldonWebsitePage.contents.C6R1.getText();
		SheldonWebsitePage.contents.C6R1.verifyText(Column6Row1);
		String Column6Row2 = SheldonWebsitePage.contents.C6R2.getText();
		SheldonWebsitePage.contents.C6R2.verifyText(Column6Row2);
		String Column6Row3 = SheldonWebsitePage.contents.C6R3.getText();
		SheldonWebsitePage.contents.C6R3.verifyText(Column6Row3);
		String Column7Row1 = SheldonWebsitePage.contents.C7R1.getText();
		SheldonWebsitePage.contents.C7R1.verifyText(Column7Row1);
		String Column7Row2 = SheldonWebsitePage.contents.C7R2.getText();
		SheldonWebsitePage.contents.C7R2.verifyText(Column7Row2);
		String Column7Row3 = SheldonWebsitePage.contents.C7R3.getText();
		SheldonWebsitePage.contents.C7R3.verifyText(Column7Row3);
		String Column8Row1 = SheldonWebsitePage.contents.C8R1.getText();
		SheldonWebsitePage.contents.C8R1.verifyText(Column8Row1);
		String Column8Row2 = SheldonWebsitePage.contents.C8R2.getText();
		SheldonWebsitePage.contents.C8R2.verifyText(Column8Row2);
		String Column8Row3 = SheldonWebsitePage.contents.C8R3.getText();
		SheldonWebsitePage.contents.C8R3.verifyText(Column8Row3);
		String Column9Row1 = SheldonWebsitePage.contents.C9R1.getText();
		SheldonWebsitePage.contents.C9R1.verifyText(Column9Row1);
		String Column9Row2 = SheldonWebsitePage.contents.C9R2.getText();
		SheldonWebsitePage.contents.C9R2.verifyText(Column9Row2);
		String Column9Row3 = SheldonWebsitePage.contents.C9R3.getText();
		SheldonWebsitePage.contents.C9R3.verifyText(Column9Row3);
		String Column10Row1 = SheldonWebsitePage.contents.C10R1.getText();
		int C10R1 = Integer.parseInt(Column10Row1);
		SheldonWebsitePage.contents.C10R1.getAttribute(Column10Row1);
		String Column10Row2 = SheldonWebsitePage.contents.C10R2.getText();
		int C10R2 = Integer.parseInt(Column10Row2);
		SheldonWebsitePage.contents.C10R2.getAttribute(Column10Row2);
		String Column10Row3 = SheldonWebsitePage.contents.C10R3.getText();
		SheldonWebsitePage.contents.C10R3.verifyText(Column10Row3);
		String Column11Row1 = SheldonWebsitePage.contents.C11R1.getText();
		SheldonWebsitePage.contents.C11R1.verifyText(Column11Row1);
		String Column11Row2 = SheldonWebsitePage.contents.C11R2.getText();
		SheldonWebsitePage.contents.C11R2.verifyText(Column11Row2);
		String Column11Row3 = SheldonWebsitePage.contents.C11R3.getText();
		SheldonWebsitePage.contents.C11R3.verifyText(Column11Row3);
		String Column12Row1 = SheldonWebsitePage.contents.C12R1.getText();
		int C12R1 = Integer.parseInt(Column12Row1);
		SheldonWebsitePage.contents.C12R1.verifyText(Column12Row1);
		String Column12Row2 = SheldonWebsitePage.contents.C12R2.getText();
		int C12R2 = Integer.parseInt(Column12Row2);
		SheldonWebsitePage.contents.C12R2.verifyText(Column12Row2);
		String Column12Row3 = SheldonWebsitePage.contents.C12R3.getText();
		SheldonWebsitePage.contents.C12R3.verifyText(Column12Row3);
		String Column13Row1 = SheldonWebsitePage.contents.C13R1.getText();
		SheldonWebsitePage.contents.C13R1.verifyText(Column13Row1);
		String Column13Row2 = SheldonWebsitePage.contents.C13R2.getText();
		SheldonWebsitePage.contents.C13R2.verifyText(Column13Row2);
		String Column13Row3 = SheldonWebsitePage.contents.C13R3.getText();
		SheldonWebsitePage.contents.C13R3.verifyText(Column13Row3);
		String Column14Row1 = SheldonWebsitePage.contents.C14R1.getText();
		SheldonWebsitePage.contents.C14R1.verifyText(Column14Row1);
		String Column14Row2 = SheldonWebsitePage.contents.C14R2.getText();
		SheldonWebsitePage.contents.C14R2.verifyText(Column14Row2);
		String Column14Row3 = SheldonWebsitePage.contents.C14R3.getText();
		SheldonWebsitePage.contents.C14R3.verifyText(Column14Row3);
		String Column15Row1 = SheldonWebsitePage.contents.C15R1.getText();
		SheldonWebsitePage.contents.C15R1.verifyText(Column15Row1);
		String Column15Row2 = SheldonWebsitePage.contents.C15R2.getText();
		SheldonWebsitePage.contents.C15R2.verifyText(Column15Row2);
		String Column15Row3 = SheldonWebsitePage.contents.C15R3.getText();
		SheldonWebsitePage.contents.C15R3.verifyText(Column15Row3);
		String Column16Row1 = SheldonWebsitePage.contents.C16R1.getText();
		SheldonWebsitePage.contents.C16R1.verifyText(Column16Row1);
		String Column16Row2 = SheldonWebsitePage.contents.C16R2.getText();
		SheldonWebsitePage.contents.C16R2.verifyText(Column16Row2);
		String Column16Row3 = SheldonWebsitePage.contents.C16R3.getText();
		SheldonWebsitePage.contents.C16R3.verifyText(Column16Row3);
		String Column17Row1 = SheldonWebsitePage.contents.C17R1.getText();
		SheldonWebsitePage.contents.C17R1.verifyText(Column17Row1);
		String Column17Row2 = SheldonWebsitePage.contents.C17R2.getText();
		int C17R2 = Integer.parseInt(Column17Row2);
		SheldonWebsitePage.contents.C17R2.verifyText(Column17Row2);
		String Column17Row3 = SheldonWebsitePage.contents.C17R3.getText();
		SheldonWebsitePage.contents.C17R3.verifyText(Column17Row3);
		String Column18Row1 = SheldonWebsitePage.contents.C18R1.getText();
		SheldonWebsitePage.contents.C18R1.verifyText(Column18Row1);
		String Column18Row2 = SheldonWebsitePage.contents.C18R2.getText();
		SheldonWebsitePage.contents.C18R2.verifyText(Column18Row2);
		String Column18Row3 = SheldonWebsitePage.contents.C18R3.getText();
		SheldonWebsitePage.contents.C18R3.verifyText(Column18Row3);
		String Column19Row1 = SheldonWebsitePage.contents.C19R1.getText();
		int C19R1 = Integer.parseInt(Column19Row1);
		SheldonWebsitePage.contents.C19R1.verifyText(Column19Row1);
		String Column19Row2 = SheldonWebsitePage.contents.C19R2.getText();
		SheldonWebsitePage.contents.C19R2.verifyText(Column19Row2);
		String Column19Row3 = SheldonWebsitePage.contents.C19R3.getText();
		SheldonWebsitePage.contents.C19R3.verifyText(Column19Row3);
		String Column20Row1 = SheldonWebsitePage.contents.C20R1.getText();
		SheldonWebsitePage.contents.C20R1.verifyText(Column20Row1);
		String Column20Row2 = SheldonWebsitePage.contents.C20R2.getText();
		SheldonWebsitePage.contents.C20R2.verifyText(Column20Row2);
		String Column20Row3 = SheldonWebsitePage.contents.C20R3.getText();
		SheldonWebsitePage.contents.C20R3.verifyText(Column20Row3);
		String Column21Row1 = SheldonWebsitePage.contents.C21R1.getText();
		SheldonWebsitePage.contents.C21R1.verifyText(Column21Row1);
		String Column21Row2 = SheldonWebsitePage.contents.C21R2.getText();
		SheldonWebsitePage.contents.C21R2.verifyText(Column21Row2);
		String Column21Row3 = SheldonWebsitePage.contents.C21R3.getText();
		SheldonWebsitePage.contents.C21R3.verifyText(Column21Row3);
		//3DPrintingValuesinVIPWebsite		
		WebControl.switchWithTitle("Value Insights Platform");		
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.Print3DR1.hover();
		Thread.sleep(2000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | 3D Printing : " + Column1Row1);
		VIPSheldonPage.contents.Print3DR2.hover();
		Thread.sleep(2000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | 3D Printing : " + Column1Row2);
		VIPSheldonPage.contents.Print3DR3.hover();
		Thread.sleep(2000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | 3D Printing : " + Column1Row3);
		WebControl.takeScreenshot("Reg_Auto_015_3DPrinting");
		
		ReportLog.setTestCase("Reg_Auto_016_AdvancedAnalytics");
		VIPSheldonPage.contents.AAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Advanced Analytics : " + Column2Row1);
		VIPSheldonPage.contents.AAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Advanced Analytics : " + Column2Row2);
		VIPSheldonPage.contents.AAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Advanced Analytics : " + Column2Row3);
		WebControl.takeScreenshot("Reg_Auto_016_AdvancedAnalytics");
		
		ReportLog.setTestCase("Reg_Auto_017_ APIManagementTools");
		VIPSheldonPage.contents.APIR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | API Management Tools : " + Column3Row1);
		VIPSheldonPage.contents.APIR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | API Management Tools : " + Column3Row2);
		VIPSheldonPage.contents.APIR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | API Management Tools : " + Column3Row3);
		WebControl.takeScreenshot("Reg_Auto_017_ APIManagementTools");
		
		NumberFormat numberformat = NumberFormat.getInstance();
		numberformat.setGroupingUsed(true);
		
		ReportLog.setTestCase("Reg_Auto_018_AI");
		VIPSheldonPage.contents.AIR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | AI : " + (numberformat.format(C4R1)));
		VIPSheldonPage.contents.AIR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | AI : " + (numberformat.format(C4R2)));
		VIPSheldonPage.contents.AIR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | AI : " + Column4Row3);
		WebControl.takeScreenshot("Reg_Auto_018_AI");
		
		ReportLog.setTestCase("Reg_Auto_019_AutonomousMachines");
		VIPSheldonPage.contents.AMR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Autonomous Machines : " + Column5Row1);
		VIPSheldonPage.contents.AMR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Autonomous Machines : " + Column5Row2);
		VIPSheldonPage.contents.AMR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Autonomous Machines : " + Column5Row3);
		WebControl.takeScreenshot("Reg_Auto_019_AutonomousMachines");
		
		ReportLog.setTestCase("Reg_Auto_020_BigData");
		VIPSheldonPage.contents.BigDataR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Big Data : " + Column6Row1);
		VIPSheldonPage.contents.BigDataR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Big Data : " + Column6Row2);
		VIPSheldonPage.contents.BigdataR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Big Data : " + Column6Row3);
		WebControl.takeScreenshot("Reg_Auto_020_BigData");
		
		ReportLog.setTestCase("Reg_Auto_021_Blockchain");
		VIPSheldonPage.contents.BChainR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Blockchain : " + Column7Row1);
		VIPSheldonPage.contents.BChainR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Blockchain : " + Column7Row2);
		VIPSheldonPage.contents.BChainR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Blockchain : " + Column7Row3);
		WebControl.takeScreenshot("Reg_Auto_021_Blockchain");
		
		ReportLog.setTestCase("Reg_Auto_022_BusinessProcessAutomation(RPA)");
		VIPSheldonPage.contents.RPAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Business Process Automation (inc. RPA) : " + Column8Row1);
		VIPSheldonPage.contents.RPAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Business Process Automation (inc. RPA) : " + Column8Row2);
		VIPSheldonPage.contents.RPAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Business Process Automation (inc. RPA) : " + Column8Row3);
		WebControl.takeScreenshot("Reg_Auto_022_BusinessProcessAutomation(RPA)");
		
		ReportLog.setTestCase("Reg_Auto_023_ChatbotsandVirtualAgents");
		VIPSheldonPage.contents.ChatbotsR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Chatbots and Virtual Agents : " + Column9Row1);
		VIPSheldonPage.contents.ChatbotsR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Chatbots and Virtual Agents : " + Column9Row2);
		VIPSheldonPage.contents.ChatbotsR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Chatbots and Virtual Agents : " + Column9Row3);
		WebControl.takeScreenshot("Reg_Auto_023_ChatbotsandVirtualAgents");
		
		ReportLog.setTestCase("Reg_Auto_024_Clouds,PaaS,SaaS,Iaas");
		VIPSheldonPage.contents.CloudsR1.hover();
		Thread.sleep(3000);	
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Clouds, PaaS, SaaS, Iaas : " + (numberformat.format(C10R1)));
		VIPSheldonPage.contents.CloudsR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Clouds, PaaS, SaaS, Iaas : " + (numberformat.format(C10R2)));
		VIPSheldonPage.contents.CloudsR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Clouds, PaaS, SaaS, Iaas : " + Column10Row3);
		WebControl.takeScreenshot("Reg_Auto_024_Clouds,PaaS,SaaS,Iaas");
		
		ReportLog.setTestCase("Reg_Auto_025_Crowdsourcing");
		VIPSheldonPage.contents.CrowdsourcingR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Crowdsourcing : " + Column11Row1);
		VIPSheldonPage.contents.CrowdsourcingR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Crowdsourcing : " + Column11Row2);
		VIPSheldonPage.contents.CrowdsourcingR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Crowdsourcing : " + Column11Row3);
		WebControl.takeScreenshot("Reg_Auto_025_Crowdsourcing");
		
		ReportLog.setTestCase("Reg_Auto_026_ExtendedReality");
		VIPSheldonPage.contents.ERR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Extended Reality : " + (numberformat.format(C12R1)));
		VIPSheldonPage.contents.ERR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Extended Reality : " + (numberformat.format(C12R2)));
		VIPSheldonPage.contents.ERR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Extended Reality : " + Column12Row3);
		WebControl.takeScreenshot("Reg_Auto_026_ExtendedReality");
		
		ReportLog.setTestCase("Reg_Auto_027_HumanAugmentation");
		VIPSheldonPage.contents.HAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Human Augmentation : " + Column13Row1);
		VIPSheldonPage.contents.HAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Human Augmentation : " + Column13Row2);
		VIPSheldonPage.contents.HAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Human Augmentation : " + Column13Row3);
		WebControl.takeScreenshot("Reg_Auto_027_HumanAugmentation");
		
		ReportLog.setTestCase("Reg_Auto_028_Industry4.0");
		VIPSheldonPage.contents.IndustryR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Industry 4.0 : " + Column14Row1);
		VIPSheldonPage.contents.IndustryR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Industry 4.0 : " + Column14Row2);
		VIPSheldonPage.contents.IndustryR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Industry 4.0 : " + Column14Row3);
		WebControl.takeScreenshot("Reg_Auto_028_Industry4.0");
		
		ReportLog.setTestCase("Reg_Auto_029_Interactive");
		VIPSheldonPage.contents.InteractiveR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Interactive : " + Column15Row1);
		VIPSheldonPage.contents.InteractiveR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Interactive : " + Column15Row2);
		VIPSheldonPage.contents.InteractiveR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Interactive : " + Column15Row3);
		WebControl.takeScreenshot("Reg_Auto_029_Interactive");
		
		ReportLog.setTestCase("Reg_Auto_030_IoT");
		VIPSheldonPage.contents.IoTR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | IoT : " + Column16Row1);
		VIPSheldonPage.contents.IoTR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | IoT : " + Column16Row2);
		VIPSheldonPage.contents.IoTR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | IoT : " + Column16Row3);
		WebControl.takeScreenshot("Reg_Auto_030_IoT");
		
		ReportLog.setTestCase("Reg_Auto_031_Mobile");
		VIPSheldonPage.contents.MobileR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Mobile : " + Column17Row1);
		VIPSheldonPage.contents.MobileR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Mobile : " + (numberformat.format(C17R2)));
		VIPSheldonPage.contents.MobileR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Mobile : " + Column17Row3);
		WebControl.takeScreenshot("Reg_Auto_031_Mobile");
				
		ReportLog.setTestCase("Reg_Auto_032_QuantumComputing");
		VIPSheldonPage.contents.QuantumR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Quantum Computing : " + Column18Row1);
		VIPSheldonPage.contents.QuantumR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Quantum Computing : " + Column18Row2);
		VIPSheldonPage.contents.QuantumR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Quantum Computing : " + Column18Row3);
		WebControl.takeScreenshot("Reg_Auto_032_QuantumComputing");
		
		ReportLog.setTestCase("Reg_Auto_033_RobotsandDrones");
		VIPSheldonPage.contents.RobotsR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Robots and Drones : " + (numberformat.format(C19R1)));
		VIPSheldonPage.contents.RobotsR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Robots and Drones : " + Column19Row2);
		VIPSheldonPage.contents.RobotsR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Robots and Drones : " + Column19Row3);
		WebControl.takeScreenshot("Reg_Auto_033_RobotsandDrones");
		
		
		ReportLog.setTestCase("Reg_Auto_034_Security");
		VIPSheldonPage.contents.SecurityR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Security : " + Column20Row1);
		VIPSheldonPage.contents.SecurityR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Security : " + Column20Row2);
		VIPSheldonPage.contents.SecurityR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Security : " + Column20Row3);
		WebControl.takeScreenshot("Reg_Auto_034_Security");
		
		ReportLog.setTestCase("Reg_Auto_035_Social/Collaboration");
		VIPSheldonPage.contents.SocialR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Social/Collaboration : " + Column21Row1);
		VIPSheldonPage.contents.SocialR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Social/Collaboration : " + Column21Row2);
		VIPSheldonPage.contents.SocialR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Social/Collaboration : " + Column21Row3);
		WebControl.takeScreenshot("Reg_Auto_035_Social/Collaboration");
		
		ReportLog.setTestCase("Reg_Auto_036_BusinesstTab");
		VIPSheldonPage.contents.BusinessTabClick.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTabClick.click();
		VIPSheldonPage.contents.BusinessTab.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTab.click();
		VIPSheldonPage.contents.BusinessTabSelected.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTabSelected.click();
		WebControl.takeScreenshot("Reg_Auto_036_BusinesstTab");
		
		ReportLog.setTestCase("Reg_Auto_037_BusinessTitle");
		VIPSheldonPage.contents.SheldonTitle.verifyText("Top Mentions of Technology & Business Levers");
		WebControl.takeScreenshot("Reg_Auto_037_BusinessTitle");
		
		ReportLog.setTestCase("Reg_Auto_038_BusinessSubTitle1");
		VIPSheldonPage.contents.SheldonSubTitle1.verifyDisplayed(true, 3);
		String SubHeader1b = VIPSheldonPage.contents.SheldonSubTitle1.getText();
		VIPSheldonPage.contents.SheldonSubTitle1.verifyText(SubHeader1b);
		WebControl.takeScreenshot("Reg_Auto_038_BusinessSubTitle1");
		
		ReportLog.setTestCase("Reg_Auto_039_BusinessSubTitle2");
		VIPSheldonPage.contents.SheldonSubTitle2.verifyText("The information displayed here depends on the current Competitors List, please go to Refine Criteria settings under Competitors tab to adjust if needed.");
		WebControl.takeScreenshot("Reg_Auto_039_BusinessSubTitle2");
		
		ReportLog.setTestCase("Reg_Auto_040_BusinessRefineCriteria");
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.SheldonRefineCriteria.click();
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.CompetitorsTitle.verifyText("Competitors");
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 10);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuSheldonClick.verifyDisplayed(true, 5);
		VIPSheldonPage.contents.SideMenuSheldonClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		WebControl.takeScreenshot("Reg_Auto_040_BusinessRefineCriteria");
		
		ReportLog.setTestCase("Reg_Auto_041_BusinessInfoIcon");
		VIPSheldonPage.contents.BusinessTabClick.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTabClick.click();
		VIPSheldonPage.contents.BusinessTab.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTab.click();
		VIPSheldonPage.contents.BusinessTabSelected.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.BusinessTabSelected.click();
		VIPSheldonPage.contents.InfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.InfoIconTooltip.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InfoIconTooltip.verifyText("Below heatmap is prepared based on the number of mentions of relevant business levers within Factiva articles. The darker the cell colour, the higher the number of mentions for the corresponding business lever.");
		VIPSheldonPage.contents.InfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_041_BusinessInfoIcon");
		
		ReportLog.setTestCase("Reg_Auto_042_BusinessTabs");
		VIPSheldonPage.contents.SubHeader2.verifyText("GROWTH");
		VIPSheldonPage.contents.SubHeader2.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.SubHeader2.click();
		VIPSheldonPage.contents.SubHeader3.verifyText("PROFITABILITY");
		VIPSheldonPage.contents.SubHeader3.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.SubHeader3.click();
		VIPSheldonPage.contents.SubHeader4.verifyText("SUSTAINABILITY");
		VIPSheldonPage.contents.SubHeader4.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.SubHeader4.click();
		VIPSheldonPage.contents.SubHeader1.verifyText("SELECT ALL");
		VIPSheldonPage.contents.SubHeader1.hover();
		Thread.sleep(1000);
		VIPSheldonPage.contents.SubHeader1.click();		
		WebControl.takeScreenshot("Reg_Auto_042_BusinessTabs");
		
		ReportLog.setTestCase("Reg_Auto_043_TargetCompany");
		VIPSheldonPage.contents.FirstCompany.verifyText("The Walt Disney Company");
		WebControl.takeScreenshot("Reg_Auto_043_TargetCompany");
		
		ReportLog.setTestCase("Reg_Auto_044_BusinessLabels");
		VIPSheldonPage.contents.BusLabel1.verifyText("CSR");
		VIPSheldonPage.contents.BusLabel2.verifyText("Financial Risk Reduction");
		VIPSheldonPage.contents.BusLabel3.verifyText("Customer Satisfaction and User Centricity");
		VIPSheldonPage.contents.BusLabel4.verifyText("Ecosystem Experience, Alliances, Partnerships");
		VIPSheldonPage.contents.BusLabel5.verifyText("Cost Model & Financial Rules");
		VIPSheldonPage.contents.BusLabel6.verifyText("M&A");
		VIPSheldonPage.contents.BusLabel7.verifyText("New Geographic Mkts. and Intl. Growth");
		VIPSheldonPage.contents.BusLabel8.verifyText("Process Eff., Process & Op Management");
		VIPSheldonPage.contents.BusLabel9.verifyText("Asset Utilization");
		VIPSheldonPage.contents.BusLabel10.verifyText("Customer Retention");
		VIPSheldonPage.contents.BusLabel11.verifyText("Organization and Organizational Resilience");
		VIPSheldonPage.contents.BusLabel12.verifyText("New Business Models");
		VIPSheldonPage.contents.BusLabel13.verifyText("Brand Value and Corporate Image");
		VIPSheldonPage.contents.BusLabel14.verifyText("Compliance");
		VIPSheldonPage.contents.BusLabel15.verifyText("New and Digital Dist. Channels");
		VIPSheldonPage.contents.BusLabel16.verifyText("Culture, People, Employee Engagement");
		VIPSheldonPage.contents.BusLabel17.verifyText("Cross-Selling Up-Selling");
		VIPSheldonPage.contents.BusLabel18.verifyText("Operational Risk Reduction");
		VIPSheldonPage.contents.BusLabel19.verifyText("Productivity");
		VIPSheldonPage.contents.BusLabel20.verifyText("New and Adjacent Products and Services");
		VIPSheldonPage.contents.BusLabel21.verifyText("Cost Cutting");
		VIPSheldonPage.contents.BusLabel22.verifyText("Cost Optimization");
		VIPSheldonPage.contents.BusLabel23.verifyText("Customer Acquisition");
		VIPSheldonPage.contents.BusLabel24.verifyText("New and Digital Communication Channels");
		VIPSheldonPage.contents.BusLabel25.verifyText("Skills");
		WebControl.takeScreenshot("Reg_Auto_044_BusinessLabels");
		
		ReportLog.setTestCase("Reg_Auto_045_HoverMessage");
		VIPSheldonPage.contents.CSRR1.hover();
		VIPSheldonPage.contents.BusHoverMessage.verifyText("The Walt Disney Company | CSR : 877");
		WebControl.takeScreenshot("Reg_Auto_045_HoverMessage");
		
		ReportLog.setTestCase("Reg_Auto_046_BusinessFootnote");
		VIPSheldonPage.contents.Footnote.verifyDisplayed(true, 2);
		String BizFootnote = VIPSheldonPage.contents.Footnote.getText();
		VIPSheldonPage.contents.Footnote.verifyText(BizFootnote);
		WebControl.takeScreenshot("Reg_Auto_046_BusinessFootnote");
		
		ReportLog.setTestCase("Reg_Auto_047_KeyInsightsTitle");
		VIPSheldonPage.contents.KeyInsightsTitle.verifyDisplayed(true, 2);
		WebControl.takeScreenshot("Reg_Auto_047_KeyInsightsTitle");
		
		ReportLog.setTestCase("Reg_Auto_048_KeyInsightsMost");
		VIPSheldonPage.contents.KeyInsightsContentMost.verifyDisplayed(true, 2);
		String BizKeyInsightsMost = VIPSheldonPage.contents.KeyInsightsContentMost.getText();
		VIPSheldonPage.contents.KeyInsightsContentMost.verifyText(BizKeyInsightsMost, BizKeyInsightsMost.contains("most featured"));
		WebControl.takeScreenshot("Reg_Auto_048_KeyInsightsMost");
		
		ReportLog.setTestCase("Reg_Auto_049_KeyInsightsHighest");
		VIPSheldonPage.contents.KeyInsightsContentHighest.verifyDisplayed(true, 2);
		String BizKeyInsightsHighest = VIPSheldonPage.contents.KeyInsightsContentHighest.getText();
		VIPSheldonPage.contents.KeyInsightsContentHighest.verifyText(BizKeyInsightsHighest, BizKeyInsightsHighest.contains("highest"));
		WebControl.takeScreenshot("Reg_Auto_049_KeyInsightsHighest");
		
		ReportLog.setTestCase("Reg_Auto_050_BizSheldonLogo");
		WebControl.switchWithTitle("SheldonProfilerFrontend");
		Thread.sleep(2000);
		//GetBusinessDataValues
		SheldonWebsitePage.contents.BizTable.verifyDisplayed(true, 5);
		String BizColumn1Row1 = SheldonWebsitePage.contents.BizC1R1.getText();
		SheldonWebsitePage.contents.BizC1R1.verifyText(BizColumn1Row1);
		String BizColumn1Row2 = SheldonWebsitePage.contents.BizC1R2.getText();
		SheldonWebsitePage.contents.BizC1R2.verifyText(BizColumn1Row2);
		String BizColumn1Row3 = SheldonWebsitePage.contents.BizC1R3.getText();
		SheldonWebsitePage.contents.BizC1R3.verifyText(BizColumn1Row3);
		String BizColumn2Row1 = SheldonWebsitePage.contents.BizC2R1.getText();
		SheldonWebsitePage.contents.BizC2R1.verifyText(BizColumn2Row1);
		String BizColumn2Row2 = SheldonWebsitePage.contents.BizC2R2.getText();
		SheldonWebsitePage.contents.BizC2R2.verifyText(BizColumn2Row2);
		String BizColumn2Row3 = SheldonWebsitePage.contents.BizC2R3.getText();
		SheldonWebsitePage.contents.BizC2R3.verifyText(BizColumn2Row3);
		String BizColumn3Row1 = SheldonWebsitePage.contents.BizC3R1.getText();
		SheldonWebsitePage.contents.BizC3R1.verifyText(BizColumn3Row1);
		String BizColumn3Row2 = SheldonWebsitePage.contents.BizC3R2.getText();
		SheldonWebsitePage.contents.BizC3R2.verifyText(BizColumn3Row2);
		String BizColumn3Row3 = SheldonWebsitePage.contents.BizC3R3.getText();
		SheldonWebsitePage.contents.BizC3R3.verifyText(BizColumn3Row3);
		String BizColumn4Row1 = SheldonWebsitePage.contents.BizC4R1.getText();
		SheldonWebsitePage.contents.BizC4R1.verifyText(BizColumn4Row1);
		String BizColumn4Row2 = SheldonWebsitePage.contents.BizC4R2.getText();
		int BizC4R2 = Integer.parseInt(BizColumn4Row2);
		SheldonWebsitePage.contents.BizC4R2.verifyText(BizColumn4Row2);
		String BizColumn4Row3 = SheldonWebsitePage.contents.BizC4R3.getText();
		SheldonWebsitePage.contents.BizC4R3.verifyText(BizColumn4Row3);
		String BizColumn5Row1 = SheldonWebsitePage.contents.BizC5R1.getText();
		SheldonWebsitePage.contents.BizC5R1.verifyText(BizColumn5Row1);
		String BizColumn5Row2 = SheldonWebsitePage.contents.BizC5R2.getText();
		SheldonWebsitePage.contents.BizC5R2.verifyText(BizColumn5Row2);
		String BizColumn5Row3 = SheldonWebsitePage.contents.BizC5R3.getText();
		SheldonWebsitePage.contents.BizC5R3.verifyText(BizColumn5Row3);
		String BizColumn6Row1 = SheldonWebsitePage.contents.BizC6R1.getText();
		SheldonWebsitePage.contents.BizC6R1.verifyText(BizColumn6Row1);
		String BizColumn6Row2 = SheldonWebsitePage.contents.BizC6R2.getText();
		SheldonWebsitePage.contents.BizC6R2.verifyText(BizColumn6Row2);
		String BizColumn6Row3 = SheldonWebsitePage.contents.BizC6R3.getText();
		SheldonWebsitePage.contents.BizC6R3.verifyText(BizColumn6Row3);
		String BizColumn7Row1 = SheldonWebsitePage.contents.BizC7R1.getText();
		SheldonWebsitePage.contents.BizC7R1.verifyText(BizColumn7Row1);
		String BizColumn7Row2 = SheldonWebsitePage.contents.BizC7R2.getText();
		SheldonWebsitePage.contents.BizC7R2.verifyText(BizColumn7Row2);
		String BizColumn7Row3 = SheldonWebsitePage.contents.BizC7R3.getText();
		SheldonWebsitePage.contents.BizC7R3.verifyText(BizColumn7Row3);
		String BizColumn8Row1 = SheldonWebsitePage.contents.BizC8R1.getText();
		SheldonWebsitePage.contents.BizC8R1.verifyText(BizColumn8Row1);
		String BizColumn8Row2 = SheldonWebsitePage.contents.BizC8R2.getText();
		SheldonWebsitePage.contents.BizC8R2.verifyText(BizColumn8Row2);
		String BizColumn8Row3 = SheldonWebsitePage.contents.BizC8R3.getText();
		SheldonWebsitePage.contents.BizC8R3.verifyText(BizColumn8Row3);
		String BizColumn9Row1 = SheldonWebsitePage.contents.BizC9R1.getText();
		SheldonWebsitePage.contents.BizC9R1.verifyText(BizColumn9Row1);
		String BizColumn9Row2 = SheldonWebsitePage.contents.BizC9R2.getText();
		SheldonWebsitePage.contents.BizC9R2.verifyText(BizColumn9Row2);
		String BizColumn9Row3 = SheldonWebsitePage.contents.BizC9R3.getText();
		SheldonWebsitePage.contents.BizC9R3.verifyText(BizColumn9Row3);
		String BizColumn10Row1 = SheldonWebsitePage.contents.BizC10R1.getText();
		SheldonWebsitePage.contents.BizC10R1.verifyText(BizColumn10Row1);
		String BizColumn10Row2 = SheldonWebsitePage.contents.BizC10R2.getText();
		SheldonWebsitePage.contents.BizC10R2.verifyText(BizColumn10Row2);
		String BizColumn10Row3 = SheldonWebsitePage.contents.BizC10R3.getText();
		SheldonWebsitePage.contents.BizC10R3.verifyText(BizColumn10Row3);
		String BizColumn11Row1 = SheldonWebsitePage.contents.BizC11R1.getText();
		SheldonWebsitePage.contents.BizC11R1.verifyText(BizColumn11Row1);
		String BizColumn11Row2 = SheldonWebsitePage.contents.BizC11R2.getText();
		SheldonWebsitePage.contents.BizC11R2.verifyText(BizColumn11Row2);
		String BizColumn11Row3 = SheldonWebsitePage.contents.BizC11R3.getText();
		SheldonWebsitePage.contents.BizC11R3.verifyText(BizColumn11Row3);
		String BizColumn12Row1 = SheldonWebsitePage.contents.BizC12R1.getText();
		SheldonWebsitePage.contents.BizC12R1.verifyText(BizColumn12Row1);
		String BizColumn12Row2 = SheldonWebsitePage.contents.BizC12R2.getText();
		SheldonWebsitePage.contents.BizC12R2.verifyText(BizColumn12Row2);
		String BizColumn12Row3 = SheldonWebsitePage.contents.BizC12R3.getText();
		SheldonWebsitePage.contents.BizC12R3.verifyText(BizColumn12Row3);
		String BizColumn13Row1 = SheldonWebsitePage.contents.BizC13R1.getText();
		SheldonWebsitePage.contents.BizC13R1.verifyText(BizColumn13Row1);
		String BizColumn13Row2 = SheldonWebsitePage.contents.BizC13R2.getText();
		SheldonWebsitePage.contents.BizC13R2.verifyText(BizColumn13Row2);
		String BizColumn13Row3 = SheldonWebsitePage.contents.BizC13R3.getText();
		SheldonWebsitePage.contents.BizC13R3.verifyText(BizColumn13Row3);
		String BizColumn14Row1 = SheldonWebsitePage.contents.BizC14R1.getText();
		SheldonWebsitePage.contents.BizC14R1.verifyText(BizColumn14Row1);
		String BizColumn14Row2 = SheldonWebsitePage.contents.BizC14R2.getText();
		SheldonWebsitePage.contents.BizC14R2.verifyText(BizColumn14Row2);
		String BizColumn14Row3 = SheldonWebsitePage.contents.BizC14R3.getText();
		SheldonWebsitePage.contents.BizC14R3.verifyText(BizColumn14Row3);
		String BizColumn15Row1 = SheldonWebsitePage.contents.BizC15R1.getText();
		SheldonWebsitePage.contents.BizC15R1.verifyText(BizColumn15Row1);
		String BizColumn15Row2 = SheldonWebsitePage.contents.BizC15R2.getText();
		SheldonWebsitePage.contents.BizC15R2.verifyText(BizColumn15Row2);
		String BizColumn15Row3 = SheldonWebsitePage.contents.BizC15R3.getText();
		SheldonWebsitePage.contents.BizC15R3.verifyText(BizColumn15Row3);
		String BizColumn16Row1 = SheldonWebsitePage.contents.BizC16R1.getText();
		SheldonWebsitePage.contents.BizC16R1.verifyText(BizColumn16Row1);
		String BizColumn16Row2 = SheldonWebsitePage.contents.BizC16R2.getText();
		SheldonWebsitePage.contents.BizC16R2.verifyText(BizColumn16Row2);
		String BizColumn16Row3 = SheldonWebsitePage.contents.BizC16R3.getText();
		SheldonWebsitePage.contents.BizC16R3.verifyText(BizColumn16Row3);
		String BizColumn17Row1 = SheldonWebsitePage.contents.BizC17R1.getText();
		SheldonWebsitePage.contents.BizC17R1.verifyText(BizColumn17Row1);
		String BizColumn17Row2 = SheldonWebsitePage.contents.BizC17R2.getText();
		SheldonWebsitePage.contents.BizC17R2.verifyText(BizColumn17Row2);
		String BizColumn17Row3 = SheldonWebsitePage.contents.BizC17R3.getText();
		SheldonWebsitePage.contents.BizC17R3.verifyText(BizColumn17Row3);
		String BizColumn18Row1 = SheldonWebsitePage.contents.BizC18R1.getText();
		SheldonWebsitePage.contents.BizC18R1.verifyText(BizColumn18Row1);
		String BizColumn18Row2 = SheldonWebsitePage.contents.BizC18R2.getText();
		SheldonWebsitePage.contents.BizC18R2.verifyText(BizColumn18Row2);
		String BizColumn18Row3 = SheldonWebsitePage.contents.BizC18R3.getText();
		SheldonWebsitePage.contents.BizC18R3.verifyText(BizColumn18Row3);
		String BizColumn19Row1 = SheldonWebsitePage.contents.BizC19R1.getText();
		SheldonWebsitePage.contents.BizC19R1.verifyText(BizColumn19Row1);
		String BizColumn19Row2 = SheldonWebsitePage.contents.BizC19R2.getText();
		SheldonWebsitePage.contents.BizC19R2.verifyText(BizColumn19Row2);
		String BizColumn19Row3 = SheldonWebsitePage.contents.BizC19R3.getText();
		SheldonWebsitePage.contents.BizC19R3.verifyText(BizColumn19Row3);
		String BizColumn20Row1 = SheldonWebsitePage.contents.BizC20R1.getText();
		SheldonWebsitePage.contents.BizC20R1.verifyText(BizColumn20Row1);
		String BizColumn20Row2 = SheldonWebsitePage.contents.BizC20R2.getText();
		SheldonWebsitePage.contents.BizC20R2.verifyText(BizColumn20Row2);
		String BizColumn20Row3 = SheldonWebsitePage.contents.BizC20R3.getText();
		SheldonWebsitePage.contents.BizC20R3.verifyText(BizColumn20Row3);
		String BizColumn21Row1 = SheldonWebsitePage.contents.BizC21R1.getText();
		SheldonWebsitePage.contents.BizC21R1.verifyText(BizColumn21Row1);
		String BizColumn21Row2 = SheldonWebsitePage.contents.BizC21R2.getText();
		SheldonWebsitePage.contents.BizC21R2.verifyText(BizColumn21Row2);
		String BizColumn21Row3 = SheldonWebsitePage.contents.BizC21R3.getText();
		SheldonWebsitePage.contents.BizC21R3.verifyText(BizColumn21Row3);
		String BizColumn22Row1 = SheldonWebsitePage.contents.BizC221R1.getText();
		SheldonWebsitePage.contents.BizC221R1.verifyText(BizColumn22Row1);
		String BizColumn22Row2 = SheldonWebsitePage.contents.BizC22R2.getText();
		SheldonWebsitePage.contents.BizC22R2.verifyText(BizColumn22Row2);
		String BizColumn22Row3 = SheldonWebsitePage.contents.BizC22R3.getText();
		SheldonWebsitePage.contents.BizC22R3.verifyText(BizColumn22Row3);
		String BizColumn23Row1 = SheldonWebsitePage.contents.BizC23R1.getText();
		SheldonWebsitePage.contents.BizC23R1.verifyText(BizColumn23Row1);
		String BizColumn23Row2 = SheldonWebsitePage.contents.BizC23R2.getText();
		SheldonWebsitePage.contents.BizC23R2.verifyText(BizColumn23Row2);
		String BizColumn23Row3 = SheldonWebsitePage.contents.BizC23R3.getText();
		SheldonWebsitePage.contents.BizC23R3.verifyText(BizColumn23Row3);
		String BizColumn24Row1 = SheldonWebsitePage.contents.BizC24R1.getText();
		SheldonWebsitePage.contents.BizC24R1.verifyText(BizColumn24Row1);
		String BizColumn24Row2 = SheldonWebsitePage.contents.BizC24R2.getText();
		SheldonWebsitePage.contents.BizC24R2.verifyText(BizColumn24Row2);
		String BizColumn24Row3 = SheldonWebsitePage.contents.BizC24R3.getText();
		SheldonWebsitePage.contents.BizC24R3.verifyText(BizColumn24Row3);
		String BizColumn25Row1 = SheldonWebsitePage.contents.BizC25R1.getText();
		SheldonWebsitePage.contents.BizC25R1.verifyText(BizColumn25Row1);
		String BizColumn25Row2 = SheldonWebsitePage.contents.BizC25R2.getText();
		SheldonWebsitePage.contents.BizC25R2.verifyText(BizColumn25Row2);
		String BizColumn25Row3 = SheldonWebsitePage.contents.BizC25R3.getText();
		SheldonWebsitePage.contents.BizC25R3.verifyText(BizColumn25Row3);
		WebControl.takeScreenshot("Reg_Auto_050_BizSheldonLogo");
		
		ReportLog.setTestCase("Reg_Auto_051_AssetUtilization");
		WebControl.switchWithTitle("Value Insights Platform");		
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.InfoIcon.click();
		VIPSheldonPage.contents.AUR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Asset Utilization : " + BizColumn1Row1);
		VIPSheldonPage.contents.AUR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Asset Utilization : " + BizColumn1Row2);
		VIPSheldonPage.contents.AUR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Asset Utilization : " + BizColumn1Row3);
		WebControl.takeScreenshot("Reg_Auto_051_AssetUtilization");
		
		ReportLog.setTestCase("Reg_Auto_052_BrandValueandCorporateImage");
		VIPSheldonPage.contents.BVCIR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Brand Value and Corporate Image : " + BizColumn2Row1);
		VIPSheldonPage.contents.BVCIR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Brand Value and Corporate Image : " + BizColumn2Row2);
		VIPSheldonPage.contents.BVCIR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Brand Value and Corporate Image : " + BizColumn2Row3);
		WebControl.takeScreenshot("Reg_Auto_052_BrandValueandCorporateImage");
		
		ReportLog.setTestCase("Reg_Auto_053_Compliance");
		VIPSheldonPage.contents.ComplianceR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Compliance : " + BizColumn3Row1);
		VIPSheldonPage.contents.ComplianceR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Compliance : " + BizColumn3Row2);
		VIPSheldonPage.contents.ComplianceR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Compliance : " + BizColumn3Row3);
		WebControl.takeScreenshot("Reg_Auto_053_Compliance");
		
		ReportLog.setTestCase("Reg_Auto_054_CSR");
		VIPSheldonPage.contents.CSRR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | CSR : " + BizColumn4Row1);
		VIPSheldonPage.contents.CSRR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | CSR : " + (numberformat.format(BizC4R2)));
		VIPSheldonPage.contents.CSRR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | CSR : " + BizColumn4Row3);
		WebControl.takeScreenshot("Reg_Auto_054_CSR");
		
		ReportLog.setTestCase("Reg_Auto_055_CostCutting");
		VIPSheldonPage.contents.CCR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Cost Cutting : " + BizColumn5Row1);
		VIPSheldonPage.contents.CCR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Cost Cutting : " + BizColumn5Row2);
		VIPSheldonPage.contents.CCR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Cost Cutting : " + BizColumn5Row3);
		WebControl.takeScreenshot("Reg_Auto_055_CostCutting");
		
		ReportLog.setTestCase("Reg_Auto_056_CostModel&Financial");
		VIPSheldonPage.contents.CMFRR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Cost Model & Financial Rules : " + BizColumn6Row1);
		VIPSheldonPage.contents.CMFRR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Cost Model & Financial Rules : " + BizColumn6Row2);
		VIPSheldonPage.contents.CMFRR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Cost Model & Financial Rules : " + BizColumn6Row3);
		WebControl.takeScreenshot("Reg_Auto_056_CostModel&Financial");
		
		ReportLog.setTestCase("Reg_Auto_057_CostOptimization");
		VIPSheldonPage.contents.COR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Cost Optimization : " + BizColumn7Row1);
		VIPSheldonPage.contents.COR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Cost Optimization : " + BizColumn7Row2);
		VIPSheldonPage.contents.COR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Cost Optimization : " + BizColumn7Row3);
		WebControl.takeScreenshot("Reg_Auto_057_CostOptimization");
		
		ReportLog.setTestCase("Reg_Auto_058_Cross-SellingUp-Selling");
		VIPSheldonPage.contents.CSUSR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Cross-Selling Up-Selling : " + BizColumn8Row1);
		VIPSheldonPage.contents.CSUSR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Cross-Selling Up-Selling : " + BizColumn8Row2);
		VIPSheldonPage.contents.CSUSR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Cross-Selling Up-Selling : " + BizColumn8Row3);
		WebControl.takeScreenshot("Reg_Auto_058_Cross-SellingUp-Selling");
		
		ReportLog.setTestCase("Reg_Auto_059_Culture,People,EmployeeEngagement");
		VIPSheldonPage.contents.CPEER1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Culture, People, Employee Engagement : " + BizColumn9Row1);
		VIPSheldonPage.contents.CPEER2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Culture, People, Employee Engagement : " + BizColumn9Row2);
		VIPSheldonPage.contents.CPEER3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Culture, People, Employee Engagement : " + BizColumn9Row3);
		WebControl.takeScreenshot("Reg_Auto_059_Culture,People,EmployeeEngagement");

		ReportLog.setTestCase("Reg_Auto_060_CustomerAcquisition");
		VIPSheldonPage.contents.CAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Customer Acquisition : " + BizColumn10Row1);
		VIPSheldonPage.contents.CAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Customer Acquisition : " + BizColumn10Row2);
		VIPSheldonPage.contents.CAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Customer Acquisition : " + BizColumn10Row3);
		WebControl.takeScreenshot("Reg_Auto_060_CustomerAcquisition");
		
		ReportLog.setTestCase("Reg_Auto_061_CustomerRetention");
		VIPSheldonPage.contents.CRR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Customer Retention : " + BizColumn11Row1);
		VIPSheldonPage.contents.CRR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Customer Retention : " + BizColumn11Row2);
		VIPSheldonPage.contents.CRR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Customer Retention : " + BizColumn11Row3);
		WebControl.takeScreenshot("Reg_Auto_061_CustomerRetention");
		
		ReportLog.setTestCase("Reg_Auto_062_CustomerSatisfactionandUserCentricity");
		VIPSheldonPage.contents.CSUCR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Customer Satisfaction and User Centricity : " + BizColumn12Row1);
		VIPSheldonPage.contents.CSUCR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Customer Satisfaction and User Centricity : " + BizColumn12Row2);
		VIPSheldonPage.contents.CSUCR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Customer Satisfaction and User Centricity : " + BizColumn12Row3);
		WebControl.takeScreenshot("Reg_Auto_062_CustomerSatisfactionandUserCentricity");
		
		ReportLog.setTestCase("Reg_Auto_063_EcosystemExperience");
		VIPSheldonPage.contents.EAPR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Ecosystem Experience, Alliances, Partnerships : " + BizColumn13Row1);
		VIPSheldonPage.contents.EAPR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Ecosystem Experience, Alliances, Partnerships : " + BizColumn13Row2);
		VIPSheldonPage.contents.EAPR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Ecosystem Experience, Alliances, Partnerships : " + BizColumn13Row3);
		WebControl.takeScreenshot("Reg_Auto_063_EcosystemExperience");

		ReportLog.setTestCase("Reg_Auto_064_FinancialRiskReduction");
		VIPSheldonPage.contents.FRR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Financial Risk Reduction : " + BizColumn14Row1);
		VIPSheldonPage.contents.FRR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Financial Risk Reduction : " + BizColumn14Row2);
		VIPSheldonPage.contents.FRR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Financial Risk Reduction : " + BizColumn14Row3);
		WebControl.takeScreenshot("Reg_Auto_064_FinancialRiskReduction");
		
		ReportLog.setTestCase("Reg_Auto_065_M&A");
		VIPSheldonPage.contents.MAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | M&A : " + BizColumn15Row1);
		VIPSheldonPage.contents.MAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | M&A : " + BizColumn15Row2);
		VIPSheldonPage.contents.MAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | M&A : " + BizColumn15Row3);
		WebControl.takeScreenshot("Reg_Auto_065_M&A");
		
		ReportLog.setTestCase("Reg_Auto_066_NewandDigital");
		VIPSheldonPage.contents.NDR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | New and Digital Dist. Channels : " + BizColumn16Row1);
		VIPSheldonPage.contents.NDR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | New and Digital Dist. Channels : " + BizColumn16Row2);
		VIPSheldonPage.contents.NDR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | New and Digital Dist. Channels : " + BizColumn16Row3);
		WebControl.takeScreenshot("Reg_Auto_066_NewandDigital");
		
		ReportLog.setTestCase("Reg_Auto_067_NewGeographic");
		VIPSheldonPage.contents.NGR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | New Geographic Mkts. and Intl. Growth : " + BizColumn17Row1);
		VIPSheldonPage.contents.NGR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | New Geographic Mkts. and Intl. Growth : " + BizColumn17Row2);
		VIPSheldonPage.contents.NGR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | New Geographic Mkts. and Intl. Growth : " + BizColumn17Row3);
		WebControl.takeScreenshot("Reg_Auto_067_NewGeographic");
		
		ReportLog.setTestCase("Reg_Auto_068_NewAdjacent");
		VIPSheldonPage.contents.NAR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | New and Adjacent Products and Services : " + BizColumn18Row1);
		VIPSheldonPage.contents.NAR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | New and Adjacent Products and Services : " + BizColumn18Row2);
		VIPSheldonPage.contents.NAR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | New and Adjacent Products and Services : " + BizColumn18Row3);
		WebControl.takeScreenshot("Reg_Auto_068_NewAdjacent");
		
		ReportLog.setTestCase("Reg_Auto_069_NewandDigitalCommunicationChannels");
		VIPSheldonPage.contents.NDCCR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | New and Digital Communication Channels : " + BizColumn19Row1);
		VIPSheldonPage.contents.NDCCR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | New and Digital Communication Channels : " + BizColumn19Row2);
		VIPSheldonPage.contents.NDCCR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | New and Digital Communication Channels : " + BizColumn19Row3);
		WebControl.takeScreenshot("Reg_Auto_069_NewandDigitalCommunicationChannels");
		
		ReportLog.setTestCase("Reg_Auto_070_NewBusinessModels");
		VIPSheldonPage.contents.NBMR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | New Business Models : " + BizColumn20Row1);
		VIPSheldonPage.contents.NBMR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | New Business Models : " + BizColumn20Row2);
		VIPSheldonPage.contents.NBMR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | New Business Models : " + BizColumn20Row3);
		WebControl.takeScreenshot("Reg_Auto_070_NewBusinessModels");
		
		ReportLog.setTestCase("Reg_Auto_071_OperationalRiskReduction");
		VIPSheldonPage.contents.ORRR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Operational Risk Reduction : " + BizColumn21Row1);
		VIPSheldonPage.contents.ORRR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Operational Risk Reduction : " + BizColumn21Row2);
		VIPSheldonPage.contents.ORRR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Operational Risk Reduction : " + BizColumn21Row3);
		WebControl.takeScreenshot("Reg_Auto_071_OperationalRiskReduction");
		
		ReportLog.setTestCase("Reg_Auto_072_OrganizationalResilience");
		VIPSheldonPage.contents.ORGR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Organization and Organizational Resilience : " + BizColumn22Row1);
		VIPSheldonPage.contents.ORGR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Organization and Organizational Resilience : " + BizColumn22Row2);
		VIPSheldonPage.contents.ORGR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Organization and Organizational Resilience : " + BizColumn22Row3);
		WebControl.takeScreenshot("Reg_Auto_072_OrganizationalResilience");
		
		ReportLog.setTestCase("Reg_Auto_073_ProcessEff");
		VIPSheldonPage.contents.PEPMR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Process Eff., Process & Op Management : " + BizColumn23Row1);
		VIPSheldonPage.contents.PEPMR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Process Eff., Process & Op Management : " + BizColumn23Row2);
		VIPSheldonPage.contents.PEPMR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Process Eff., Process & Op Management : " + BizColumn23Row3);
		WebControl.takeScreenshot("Reg_Auto_073_ProcessEff");
		
		ReportLog.setTestCase("Reg_Auto_074_Productivity");
		VIPSheldonPage.contents.ProductivityR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Productivity : " + BizColumn24Row1);
		VIPSheldonPage.contents.ProductivityR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Productivity : " + BizColumn24Row2);
		VIPSheldonPage.contents.ProductivityR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Productivity : " + BizColumn24Row3);
		WebControl.takeScreenshot("Reg_Auto_074_Productivity");
		
		ReportLog.setTestCase("Reg_Auto_075_Skills");
		VIPSheldonPage.contents.SkillsR1.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("The Walt Disney Company | Skills : " + BizColumn25Row1);
		VIPSheldonPage.contents.SkillsR2.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Netflix, Inc. | Skills : " + BizColumn25Row2);
		VIPSheldonPage.contents.SkillsR3.hover();
		Thread.sleep(3000);
		VIPSheldonPage.contents.ToolTipText.verifyText("Vivendi SA | Skills : " + BizColumn25Row3);
		WebControl.takeScreenshot("Reg_Auto_075_Skills");
		
		ReportLog.setTestCase("Reg_Auto_076_Acquisitions&Investments");
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.BurgerMenu.verifyDisplayed(true, 3);
		VIPSheldonPage.contents.BurgerMenu.click();
		VIPSheldonPage.contents.SideMenuAcqInvClick.verifyDisplayed(true, 3);
		VIPSheldonPage.contents.SideMenuAcqInvClick.click();
		VIPLandingPage.contents.HelpIcon.hover();
		WebControl.takeScreenshot("Reg_Auto_076_Acquisitions&Investments");
		
		ReportLog.setTestCase("Reg_Auto_077_AcquisitionsTitle");
		VIPSheldonPage.contents.AcquiTitle.verifyText("Acquisitions & Investments");
		WebControl.takeScreenshot("Reg_Auto_077_AcquisitionsTitle");
		
		ReportLog.setTestCase("Reg_Auto_078_AcquisitionsSubTitle");
		VIPSheldonPage.contents.AcquiSubTitle.verifyText("The data for this section is pulled from Accenture Strategy’s Sheldon Profiler.");
		WebControl.takeScreenshot("Reg_Auto_078_AcquisitionsSubTitle");
		//Get Investment&Acquisition values in Sheldon Website
		WebControl.switchWithTitle("SheldonProfilerFrontend");
		Thread.sleep(2000);
		String InvCompany1 = SheldonWebsitePage.contents.InvComp1.getText();
		SheldonWebsitePage.contents.InvComp1.verifyText(InvCompany1);
		String InvCompany2 = SheldonWebsitePage.contents.InvComp2.getText();
		SheldonWebsitePage.contents.InvComp2.verifyText(InvCompany2);
		String InvCompany3 = SheldonWebsitePage.contents.InvComp3.getText();
		SheldonWebsitePage.contents.InvComp3.verifyText(InvCompany3);
		String InvDescription1 = SheldonWebsitePage.contents.InvDesc1.getText();
		SheldonWebsitePage.contents.InvDesc1.verifyText(InvDescription1);
		String InvDescription2 = SheldonWebsitePage.contents.InvDesc2.getText();
		SheldonWebsitePage.contents.InvDesc2.verifyText(InvDescription2);
		String InvDescription3 = SheldonWebsitePage.contents.InvDesc3.getText();
		SheldonWebsitePage.contents.InvDesc3.verifyText(InvDescription3);
		String InvRound1 = SheldonWebsitePage.contents.InvRnd1.getText();
		SheldonWebsitePage.contents.InvRnd1.verifyText(InvRound1);
		String InvRound2 = SheldonWebsitePage.contents.InvRnd2.getText();
		SheldonWebsitePage.contents.InvRnd2.verifyText(InvRound2);
		String InvRound3 = SheldonWebsitePage.contents.InvRnd3.getText();
		SheldonWebsitePage.contents.InvRnd3.verifyText(InvRound3);
		String InvMoney1 = SheldonWebsitePage.contents.InvTMR1.getText();
		//int InvTMR1 = Integer.parseInt("20,000,000.00");
		SheldonWebsitePage.contents.InvTMR1.verifyText(InvMoney1);
		String InvMoney2 = SheldonWebsitePage.contents.InvTMR2.getText();
		//int InvTMR2 = Integer.valueOf(InvMoney2);
		SheldonWebsitePage.contents.InvTMR2.verifyText(InvMoney2);
		String InvMoney3 = SheldonWebsitePage.contents.InvTMR3.getText();
		//double InvTMR3 = Double.valueOf(InvMoney3);
		SheldonWebsitePage.contents.InvTMR3.verifyText(InvMoney3);
		String InvestDate1 = SheldonWebsitePage.contents.InvDate1.getText();
		SheldonWebsitePage.contents.InvDate1.verifyText(InvestDate1);
		String InvestDate2 = SheldonWebsitePage.contents.InvDate2.getText();
		SheldonWebsitePage.contents.InvDate2.verifyText(InvestDate2);
		String InvestDate3 = SheldonWebsitePage.contents.InvDate3.getText();
		SheldonWebsitePage.contents.InvDate3.verifyText(InvestDate3);
		String InvestScore = SheldonWebsitePage.contents.InvScore.getText();
		SheldonWebsitePage.contents.InvScore.verifyText(InvestScore);
		String AcquiComp1 = SheldonWebsitePage.contents.AcqComp1.getText();
		SheldonWebsitePage.contents.AcqComp1.verifyText(AcquiComp1);
		String AcquiComp2 = SheldonWebsitePage.contents.AcqComp2.getText();
		SheldonWebsitePage.contents.AcqComp2.verifyText(AcquiComp2);
		String AcquiDesc1 = SheldonWebsitePage.contents.AcqDesc1.getText();
		SheldonWebsitePage.contents.AcqDesc1.verifyText(AcquiDesc1);
		String AcquiDesc2 = SheldonWebsitePage.contents.AcqDesc2.getText();
		SheldonWebsitePage.contents.AcqDesc2.verifyText(AcquiDesc2);
		String AcquiTMR1 = SheldonWebsitePage.contents.AcqTMR1.getText();
		//double AcqTMR1 = Double.valueOf(AcquiTMR1);
		SheldonWebsitePage.contents.AcqTMR1.verifyText(AcquiTMR1);
		String AcquiDate1 = SheldonWebsitePage.contents.AcqDate1.getText();
		SheldonWebsitePage.contents.AcqDate1.verifyText(AcquiDate1);
		String AcquiDate2 = SheldonWebsitePage.contents.AcqDate2.getText();
		SheldonWebsitePage.contents.AcqDate2.verifyText(AcquiDate2);
		String AcquiScore = SheldonWebsitePage.contents.AcqScore.getText();
		SheldonWebsitePage.contents.AcqScore.verifyText(AcquiScore);
		
		ReportLog.setTestCase("Reg_Auto_080_Companies");
		WebControl.switchWithTitle("Value Insights Platform");		
		VIPLandingPage.contents.HelpIcon.hover();
		VIPSheldonPage.contents.AcquiTitle.verifyText("Acquisitions & Investments");
		VIPSheldonPage.contents.TopAcqComp1.verifyText(AcquiComp1);
		VIPSheldonPage.contents.TopAcqComp2.verifyText(AcquiComp2 + " (via The Walt Disney Company)");
		VIPSheldonPage.contents.TopInvComp1.verifyText(InvCompany1 + " (via The Walt Disney Company)");
		VIPSheldonPage.contents.TopInvComp2.verifyText(InvCompany2 + " (via The Walt Disney Company)");
		VIPSheldonPage.contents.TopInvComp3.verifyText(InvCompany3 + " (via The Walt Disney Company)");		
		WebControl.takeScreenshot("Reg_Auto_080_Companies");
		
		ReportLog.setTestCase("Reg_Auto_081_Descriptions");
		VIPSheldonPage.contents.TopAcqDesc1.verifyText(AcquiDesc1);
		VIPSheldonPage.contents.TopAcqDesc2.verifyText(AcquiDesc2);
		VIPSheldonPage.contents.TopInvDesc1.verifyText(InvDescription1);
		VIPSheldonPage.contents.TopInvDesc2.verifyText(InvDescription2);
		VIPSheldonPage.contents.TopInvDesc3.verifyText(InvDescription3);		
		WebControl.takeScreenshot("Reg_Auto_081_Descriptions");
		
		ReportLog.setTestCase("Reg_Auto_082_Round");
		VIPSheldonPage.contents.TopInvRnd1.verifyText(InvRound1);
		VIPSheldonPage.contents.TopInvRnd2.verifyText(InvRound2);
		VIPSheldonPage.contents.TopInvRnd3.verifyText(InvRound3);
		WebControl.takeScreenshot("Reg_Auto_082_Round");
		
		ReportLog.setTestCase("Reg_Auto_083_TotalMoneyRaised");
//		DecimalFormat nodecimal = new DecimalFormat("#");
//		nodecimal.setGroupingUsed(true);
//		nodecimal.setGroupingSize(3);		
//		
//		VIPSheldonPage.contents.TopAcqTMR1.verifyText(nodecimal.format(AcqTMR1));
//		VIPSheldonPage.contents.TopInvTMR1.verifyText(nodecimal.format(InvTMR1));
//		VIPSheldonPage.contents.TopInvTMR2.verifyText(nodecimal.format(InvTMR2));
//		VIPSheldonPage.contents.TopInvTMR3.verifyText(nodecimal.format(InvTMR3));
		
		VIPSheldonPage.contents.TopAcqTMR1.verifyText(AcquiTMR1);
		VIPSheldonPage.contents.TopInvTMR1.verifyText(InvMoney1);
		VIPSheldonPage.contents.TopInvTMR2.verifyText(InvMoney2);
		VIPSheldonPage.contents.TopInvTMR3.verifyText(InvMoney3);
		WebControl.takeScreenshot("Reg_Auto_083_TotalMoneyRaised");
		
		ReportLog.setTestCase("Reg_Auto_084_Date");	      
		VIPSheldonPage.contents.TopAcqDate1.verifyText("0"+AcquiDate1);
		VIPSheldonPage.contents.TopAcqDate2.verifyText(AcquiDate2);
		VIPSheldonPage.contents.TopInvDate1.verifyText("0"+InvestDate1);
		VIPSheldonPage.contents.TopInvDate2.verifyText("0"+InvestDate2);
		VIPSheldonPage.contents.TopInvDate3.verifyText("0"+InvestDate3);		
		WebControl.takeScreenshot("Reg_Auto_084_Date");
		
		ReportLog.setTestCase("Reg_Auto_085_Score");
		VIPSheldonPage.contents.SheldonScoreClick1.verifyText(AcquiScore);
		VIPSheldonPage.contents.SheldonScoreClick2.verifyText(InvestScore);
		WebControl.takeScreenshot("Reg_Auto_085_Score");
		
		ReportLog.setTestCase("Reg_Auto_086_Footnote");
		VIPSheldonPage.contents.AcquiFootnote.verifyText("Source: Crunchbase, and Sheldon Insight");
		WebControl.takeScreenshot("Reg_Auto_086_Footnote");
		
		ReportLog.setTestCase("Reg_Auto_089_ScoreInfoIcon");
		VIPSheldonPage.contents.AcquiScoreInfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InvScoreInfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.AcquiScoreInfoIcon.hover();
		VIPSheldonPage.contents.AcquiScoreInfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_089_ScoreInfoIcon");
		
		ReportLog.setTestCase("Reg_Auto_090_ScoreInfoIconMessage");
		VIPSheldonPage.contents.ScoreInfoTooltip.verifyDisplayed(true, 2);
		String ScoreTooltip = VIPSheldonPage.contents.ScoreInfoTooltip.getText();
		VIPSheldonPage.contents.ScoreInfoTooltip.verifyText(ScoreTooltip);
		VIPSheldonPage.contents.AcquiScoreInfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_090_ScoreInfoIconMessage");
		
		ReportLog.setTestCase("Reg_Auto_091_TMRInfoIcon");
		VIPSheldonPage.contents.AcquiTMRInfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.AcquiTMRInfoIcon.hover();
		VIPSheldonPage.contents.AcquiTMRInfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_091_TMRInfoIcon");
		
		ReportLog.setTestCase("Reg_Auto_092_AcqTMRInfoIconMessage");
		VIPSheldonPage.contents.TMRInfoTooltip.verifyDisplayed(true, 2);
		String AcqTMRTooltip = VIPSheldonPage.contents.TMRInfoTooltip.getText();
		VIPSheldonPage.contents.TMRInfoTooltip.verifyText(AcqTMRTooltip);
		VIPSheldonPage.contents.AcquiTMRInfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_092_AcqTMRInfoIconMessage");
		
		ReportLog.setTestCase("Reg_Auto_093_InvTMRInfoIconMessage");
		VIPSheldonPage.contents.InvTMRInfoIcon.verifyDisplayed(true, 2);
		VIPSheldonPage.contents.InvTMRInfoIcon.hover();
		VIPSheldonPage.contents.InvTMRInfoIcon.click();
		VIPSheldonPage.contents.TMRInfoTooltip.verifyDisplayed(true, 2);
		String InvTMRTooltip = VIPSheldonPage.contents.TMRInfoTooltip.getText();
		VIPSheldonPage.contents.TMRInfoTooltip.verifyText(InvTMRTooltip);
		VIPSheldonPage.contents.InvTMRInfoIcon.click();
		WebControl.takeScreenshot("Reg_Auto_093_InvTMRInfoIconMessage");
		
		ReportLog.setTestCase("Reg_Auto_079_SheldonScore");
		VIPSheldonPage.contents.SheldonScoreClick1.hover();
		VIPSheldonPage.contents.SheldonScoreClick1.click();
		WebControl.waitForPageToLoad(80);
		Thread.sleep(2000);
		WebControl.switchWithTitle("SheldonProfilerFrontend");
		Thread.sleep(2000);
		WebControl.switchWithTitle("Value Insights Platform");	
		Thread.sleep(2000);
		VIPSheldonPage.contents.SheldonScoreClick2.hover();
		VIPSheldonPage.contents.SheldonScoreClick2.click();
		WebControl.waitForPageToLoad(80);
		Thread.sleep(2000);
		WebControl.switchWithTitle("SheldonProfilerFrontend");
		Thread.sleep(2000);
		WebControl.close();
		WebControl.takeScreenshot("Reg_Auto_079_SheldonScore");
				
	}
	

}
	
