package pageobjects;

import org.openqa.selenium.By;

import auto.framework.TestBase;
import auto.framework.web.Element;

public class SheldonWebsitePage extends TestBase {
	
	public static final Contents contents = new Contents();
	public static class Contents extends Element{
		
		public final Element SheldonProfilerHeader;
		public final Element SelectCompanyHeader;
		public final Element CompanyNameInput;
		public final Element SearchButton;
		public final Element CompanyNameTypeAhead;
		public final Element Card1;
		public final Element Card2;
		public final Element NextButton;
		public final Element TechTable;
		public final Element TechLabel1;
		public final Element TechLabel2;
		public final Element TechLabel3;
		public final Element TechLabel4;
		public final Element TechLabel5;
		public final Element TechLabel6;
		public final Element TechLabel7;
		public final Element TechLabel8;
		public final Element TechLabel9;
		public final Element TechLabel10;
		public final Element TechLabel11;
		public final Element TechLabel12;
		public final Element TechLabel13;
		public final Element TechLabel14;
		public final Element TechLabel15;
		public final Element TechLabel16;
		public final Element TechLabel17;
		public final Element TechLabel18;
		public final Element TechLabel19;
		public final Element TechLabel20;
		public final Element TechLabel21;
		public final Element TechComp1;
		public final Element TechComp2;
		public final Element TechComp3;
		public final Element C1R1;
		public final Element C1R2;
		public final Element C1R3;
		public final Element C2R1;
		public final Element C2R2;
		public final Element C2R3;
		public final Element C3R1;
		public final Element C3R2;
		public final Element C3R3;
		public final Element C4R1;
		public final Element C4R2;
		public final Element C4R3;
		public final Element C5R1;
		public final Element C5R2;
		public final Element C5R3;
		public final Element C6R1;
		public final Element C6R2;
		public final Element C6R3;
		public final Element C7R1;
		public final Element C7R2;
		public final Element C7R3;
		public final Element C8R1;
		public final Element C8R2;
		public final Element C8R3;
		public final Element C9R1;
		public final Element C9R2;
		public final Element C9R3;
		public final Element C10R1;
		public final Element C10R2;
		public final Element C10R3;
		public final Element C11R1;
		public final Element C11R2;
		public final Element C11R3;
		public final Element C12R1;
		public final Element C12R2;
		public final Element C12R3;
		public final Element C13R1;
		public final Element C13R2;
		public final Element C13R3;
		public final Element C14R1;
		public final Element C14R2;
		public final Element C14R3;
		public final Element C15R1;
		public final Element C15R2;
		public final Element C15R3;
		public final Element C16R1;
		public final Element C16R2;
		public final Element C16R3;
		public final Element C17R1;
		public final Element C17R2;
		public final Element C17R3;
		public final Element C18R1;
		public final Element C18R2;
		public final Element C18R3;
		public final Element C19R1;
		public final Element C19R2;
		public final Element C19R3;
		public final Element C20R1;
		public final Element C20R2;
		public final Element C20R3;
		public final Element C21R1;
		public final Element C21R2;
		public final Element C21R3;
		
		public final Element BizC1R1;
		public final Element BizC1R2;
		public final Element BizC1R3;
		public final Element BizC2R1;
		public final Element BizC2R2;
		public final Element BizC2R3;
		public final Element BizC3R1;
		public final Element BizC3R2;
		public final Element BizC3R3;
		public final Element BizC4R1;
		public final Element BizC4R2;
		public final Element BizC4R3;
		public final Element BizC5R1;
		public final Element BizC5R2;
		public final Element BizC5R3;
		public final Element BizC6R1;
		public final Element BizC6R2;
		public final Element BizC6R3;
		public final Element BizC7R1;
		public final Element BizC7R2;
		public final Element BizC7R3;
		public final Element BizC8R1;
		public final Element BizC8R2;
		public final Element BizC8R3;
		public final Element BizC9R1;
		public final Element BizC9R2;
		public final Element BizC9R3;
		public final Element BizC10R1;
		public final Element BizC10R2;
		public final Element BizC10R3;
		public final Element BizC11R1;
		public final Element BizC11R2;
		public final Element BizC11R3;
		public final Element BizC12R1;
		public final Element BizC12R2;
		public final Element BizC12R3;
		public final Element BizC13R1;
		public final Element BizC13R2;
		public final Element BizC13R3;
		public final Element BizC14R1;
		public final Element BizC14R2;
		public final Element BizC14R3;
		public final Element BizC15R1;
		public final Element BizC15R2;
		public final Element BizC15R3;
		public final Element BizC16R1;
		public final Element BizC16R2;
		public final Element BizC16R3;
		public final Element BizC17R1;
		public final Element BizC17R2;
		public final Element BizC17R3;
		public final Element BizC18R1;
		public final Element BizC18R2;
		public final Element BizC18R3;
		public final Element BizC19R1;
		public final Element BizC19R2;
		public final Element BizC19R3;
		public final Element BizC20R1;
		public final Element BizC20R2;
		public final Element BizC20R3;
		public final Element BizC21R1;
		public final Element BizC21R2;
		public final Element BizC21R3;
		public final Element BizC221R1;
		public final Element BizC22R2;
		public final Element BizC22R3;
		public final Element BizC23R1;
		public final Element BizC23R2;
		public final Element BizC23R3;
		public final Element BizC24R1;
		public final Element BizC24R2;
		public final Element BizC24R3;
		public final Element BizC25R1;
		public final Element BizC25R2;
		public final Element BizC25R3;
		public final Element BizTable;
		public final Element BizLabel1;
		public final Element BizLabel2;
		public final Element BizLabel3;
		public final Element BizLabel4;
		public final Element BizLabel5;
		public final Element BizLabel6;
		public final Element BizLabel7;
		public final Element BizLabel8;
		public final Element BizLabel9;
		public final Element BizLabel10;
		public final Element BizLabel11;
		public final Element BizLabel12;
		public final Element BizLabel13;
		public final Element BizLabel14;
		public final Element BizLabel15;
		public final Element BizLabel16;
		public final Element BizLabel17;
		public final Element BizLabel18;
		public final Element BizLabel19;
		public final Element BizLabel20;
		public final Element BizLabel21;
		public final Element BizLabel22;
		public final Element BizLabel23;
		public final Element BizLabel24;
		public final Element BizLabel25;
		public final Element BizComp1;
		public final Element BizComp2;
		public final Element BizComp3;
	
		public final Element InvComp1;
		public final Element InvComp2;
		public final Element InvComp3;
		public final Element InvDesc1;
		public final Element InvDesc2;
		public final Element InvDesc3;
		public final Element InvRnd1;
		public final Element InvRnd2;
		public final Element InvRnd3;
		public final Element InvTMR1;
		public final Element InvTMR2;
		public final Element InvTMR3;
		public final Element InvDate1;
		public final Element InvDate2;
		public final Element InvDate3;
		public final Element InvScore;
		public final Element AcqComp1;
		public final Element AcqComp2;
		public final Element AcqDesc1;
		public final Element AcqDesc2;
		public final Element AcqTMR1;
		public final Element AcqDate1;
		public final Element AcqDate2;
		public final Element AcqScore;
				
		
		public Contents() {
			super("Container", By.className("mat-typography"));
	
			//Common
			SheldonProfilerHeader = new Element("Sheldon Profiler Logo", By.xpath("//*[@class='logo-sheldon']"), this);
			SelectCompanyHeader = new Element("Select Company Header", By.xpath("//div[@class='col1']//h2"), this);
			CompanyNameInput = new Element("Company Name Field", By.xpath("//*[@id='mat-input-0']"), this);
			CompanyNameTypeAhead = new Element("Company Name Appear", By.xpath("//*[@class='mat-option-text']"), this);
			SearchButton = new Element("Search Button", By.xpath("//button[@class='mat-raised-button mat-primary']"), this); 
			Card1 = new Element("Vivendi SA", By.xpath("(//*[@class='mat-card'])[1]"), this);
			Card2 = new Element("Netflix, Inc.", By.xpath("(//*[@class='mat-card'])[9]"), this);
			NextButton = new Element("Next", By.xpath("//button[@class='mat-raised-button mat-primary']"), this);
	
	
			//TechnologiesDataTable
			TechTable = new Element("Technologies Data Table", By.xpath("(//*[@transform='translate(200, 300)'])[1]"), this);
			TechComp1 = new Element("The Walt Disney Company", By.xpath("(//*[@transform='translate(180, 0)'])[1]"), this);
			TechComp2 = new Element("Netflix, Inc.", By.xpath("(//*[@transform='translate(180, 32)'])[1]"), this);
			TechComp3 = new Element("Vivendi SA", By.xpath("(//*[@transform='translate(180, 64)'])[1]"), this);
			
			TechLabel1 = new Element("3D Printing", By.xpath("(//*[@transform='translate(218, 280) rotate(-90)'])[1]"), this);
			C1R1 = new Element("Column 1 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[1]"), this);
			C1R2 = new Element("Column 1 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[2]"), this);
			C1R3 = new Element("Column 1 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[3]"), this);
//			C1R4 = new Element("Column 1 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[4]"), this);
//			C1R5 = new Element("Column 1 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[5]"), this);
//			C1R6 = new Element("Column 1 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[6]"), this);
//			C1R7 = new Element("Column 1 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[7]"), this);
//			C1R8 = new Element("Column 1 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[8]"), this);
//			C1R9 = new Element("Column 1 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[9]"), this);
//			C1R10 = new Element("Column 1 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[10]"), this);
//			C1R11 = new Element("Column 1 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[11]"), this);
//			C1R12 = new Element("Column 1 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[12]"), this);
//			C1R13 = new Element("Column 1 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[13]"), this);
//			C1R14 = new Element("Column 1 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[14]"), this);
//			C1R15 = new Element("Column 1 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[15]"), this);
			
			TechLabel2 = new Element("Advanced Analytics", By.xpath("(//*[@transform='translate(250, 280) rotate(-90)'])[1]"), this);			
			C2R1 = new Element("Column 2 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[1]"), this);
			C2R2 = new Element("Column 2 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[2]"), this);
			C2R3 = new Element("Column 2 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[3]"), this);
//			C2R4 = new Element("Column 2 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[4]"), this);
//			C2R5 = new Element("Column 2 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[5]"), this);
//			C2R6 = new Element("Column 2 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[6]"), this);
//			C2R7 = new Element("Column 2 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[7]"), this);
//			C2R8 = new Element("Column 2 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[8]"), this);
//			C2R9 = new Element("Column 2 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[9]"), this);
//			C2R10 = new Element("Column 2 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[10]"), this);
//			C2R11 = new Element("Column 2 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[11]"), this);
//			C2R12 = new Element("Column 2 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[12]"), this);
//			C2R13 = new Element("Column 2 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[13]"), this);
//			C2R14 = new Element("Column 2 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[14]"), this);
//			C2R15 = new Element("Column 2 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[15]"), this);
			
			TechLabel3 = new Element("Api Management Tools", By.xpath("(//*[@transform='translate(282, 280) rotate(-90)'])[1]"), this);
			C3R1 = new Element("Column 3 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[1]"), this);
			C3R2 = new Element("Column 3 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[2]"), this);
			C3R3 = new Element("Column 3 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[3]"), this);
//			C3R4 = new Element("Column 3 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[4]"), this);
//			C3R5 = new Element("Column 3 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[5]"), this);
//			C3R6 = new Element("Column 3 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[6]"), this);
//			C3R7 = new Element("Column 3 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[7]"), this);
//			C3R8 = new Element("Column 3 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[8]"), this);
//			C3R9 = new Element("Column 3 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[9]"), this);
//			C3R10 = new Element("Column 3 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[10]"), this);
//			C3R11 = new Element("Column 3 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[11]"), this);
//			C3R12 = new Element("Column 3 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[12]"), this);
//			C3R13 = new Element("Column 3 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[13]"), this);
//			C3R14 = new Element("Column 3 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[14]"), this);
//			C3R15 = new Element("Column 3 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[15]"), this);
			
			TechLabel4 = new Element("Artificial Intelligence", By.xpath("(//*[@transform='translate(314, 280) rotate(-90)'])[1]"), this);
			C4R1 = new Element("Column 4 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[1]"), this);
			C4R2 = new Element("Column 4 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[2]"), this);
			C4R3 = new Element("Column 4 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[3]"), this);
//			C4R4 = new Element("Column 4 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[4]"), this);
//			C4R5 = new Element("Column 4 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[5]"), this);
//			C4R6 = new Element("Column 4 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[6]"), this);
//			C4R7 = new Element("Column 4 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[7]"), this);
//			C4R8 = new Element("Column 4 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[8]"), this);
//			C4R9 = new Element("Column 4 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[9]"), this);
//			C4R10 = new Element("Column 4 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[10]"), this);
//			C4R11 = new Element("Column 4 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[11]"), this);
//			C4R12 = new Element("Column 4 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[12]"), this);
//			C4R13 = new Element("Column 4 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[13]"), this);
//			C4R14 = new Element("Column 4 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[14]"), this);
//			C4R15 = new Element("Column 4 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[15]"), this);
			
			TechLabel5 = new Element("Autonomous machines", By.xpath("(//*[@transform='translate(346, 280) rotate(-90)'])[1]"), this);
			C5R1 = new Element("Column 5 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[1]"), this);
			C5R2 = new Element("Column 5 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[2]"), this);
			C5R3 = new Element("Column 5 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[3]"), this);
//			C5R4 = new Element("Column 5 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[4]"), this);
//			C5R5 = new Element("Column 5 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[5]"), this);
//			C5R6 = new Element("Column 5 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[6]"), this);
//			C5R7 = new Element("Column 5 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[7]"), this);
//			C5R8 = new Element("Column 5 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[8]"), this);
//			C5R9 = new Element("Column 5 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[9]"), this);
//			C5R10 = new Element("Column 5 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[10]"), this);
//			C5R11 = new Element("Column 5 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[11]"), this);
//			C5R12 = new Element("Column 5 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[12]"), this);
//			C5R13 = new Element("Column 5 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[13]"), this);
//			C5R14 = new Element("Column 5 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[14]"), this);
//			C5R15 = new Element("Column 5 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[15]"), this);
			
			TechLabel6 = new Element("Big Data", By.xpath("(//*[@transform='translate(378, 280) rotate(-90)'])[1]"), this);
			C6R1 = new Element("Column 6 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[1]"), this);
			C6R2 = new Element("Column 6 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[2]"), this);
			C6R3 = new Element("Column 6 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[3]"), this);
//			C6R4 = new Element("Column 6 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[4]"), this);
//			C6R5 = new Element("Column 6 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[5]"), this);
//			C6R6 = new Element("Column 6 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[6]"), this);
//			C6R7 = new Element("Column 6 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[7]"), this);
//			C6R8 = new Element("Column 6 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[8]"), this); 
//			C6R9 = new Element("Column 6 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[9]"), this);
//			C6R10 = new Element("Column 6 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[10]"), this);
//			C6R11 = new Element("Column 6 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[11]"), this);
//			C6R12 = new Element("Column 6 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[12]"), this);
//			C6R13 = new Element("Column 6 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[13]"), this);
//			C6R14 = new Element("Column 6 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[14]"), this);
//			C6R15 = new Element("Column 6 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[15]"), this);
			
			TechLabel7 = new Element("Blockchain", By.xpath("(//*[@transform='translate(410, 280) rotate(-90)'])[1]"), this);
			C7R1 = new Element("Column 7 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[1]"), this);
			C7R2 = new Element("Column 7 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[2]"), this);
			C7R3 = new Element("Column 7 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[3]"), this);
//			C7R4 = new Element("Column 7 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[4]"), this);
//			C7R5 = new Element("Column 7 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[5]"), this);
//			C7R6 = new Element("Column 7 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[6]"), this);
//			C7R7 = new Element("Column 7 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[7]"), this);
//			C7R8 = new Element("Column 7 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[8]"), this); 
//			C7R9 = new Element("Column 7 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[9]"), this);
//			C7R10 = new Element("Column 7 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[10]"), this);
//			C7R11 = new Element("Column 7 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[11]"), this);
//			C7R12 = new Element("Column 7 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[12]"), this);
//			C7R13 = new Element("Column 7 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[13]"), this);
//			C7R14 = new Element("Column 7 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[14]"), this);
//			C7R15 = new Element("Column 7 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[15]"), this);
			
			TechLabel8 = new Element("Business Process Automation (inc. RPA)", By.xpath("(//*[@transform='translate(442, 280) rotate(-90)'])[1]"), this);
			C8R1 = new Element("Column 8 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[1]"), this);
			C8R2 = new Element("Column 8 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[2]"), this);
			C8R3 = new Element("Column 8 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[3]"), this);
//			C8R4 = new Element("Column 8 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[4]"), this);
//			C8R5 = new Element("Column 8 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[5]"), this);
//			C8R6 = new Element("Column 8 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[6]"), this);
//			C8R7 = new Element("Column 8 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[7]"), this);
//			C8R8 = new Element("Column 8 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[8]"), this); 
//			C8R9 = new Element("Column 8 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[9]"), this);
//			C8R10 = new Element("Column 8 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[10]"), this);
//			C8R11 = new Element("Column 8 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[11]"), this);
//			C8R12 = new Element("Column 8 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[12]"), this);
//			C8R13 = new Element("Column 8 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[13]"), this);
//			C8R14 = new Element("Column 8 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[14]"), this);
//			C8R15 = new Element("Column 8 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[15]"), this);
			
			TechLabel9 = new Element("Chatbots and virtual agents", By.xpath("(//*[@transform='translate(474, 280) rotate(-90)'])[1]"), this);
			C9R1 = new Element("Column 9 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[1]"), this);
			C9R2 = new Element("Column 9 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[2]"), this);
			C9R3 = new Element("Column 9 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[3]"), this);
//			C9R4 = new Element("Column 9 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[4]"), this);
//			C9R5 = new Element("Column 9 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[5]"), this);
//			C9R6 = new Element("Column 9 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[6]"), this);
//			C9R7 = new Element("Column 9 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[7]"), this);
//			C9R8 = new Element("Column 9 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[8]"), this); 
//			C9R9 = new Element("Column 9 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[9]"), this);
//			C9R10 = new Element("Column 9 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[10]"), this);
//			C9R11 = new Element("Column 9 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[11]"), this);
//			C9R12 = new Element("Column 9 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[12]"), this);
//			C9R13 = new Element("Column 9 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[13]"), this);
//			C9R14 = new Element("Column 9 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[14]"), this);
//			C9R15 = new Element("Column 9 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[15]"), this);
			
			TechLabel10 = new Element("Cloud, PaaS, SaaS, IaaS", By.xpath("(//*[@transform='translate(506, 280) rotate(-90)'])[1]"), this);
			C10R1 = new Element("Column 10 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[1]"), this);
			C10R2 = new Element("Column 10 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[2]"), this);
			C10R3 = new Element("Column 10 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[3]"), this);
//			C10R4 = new Element("Column 10 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[4]"), this);
//			C10R5 = new Element("Column 10 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[5]"), this);
//			C10R6 = new Element("Column 10 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[6]"), this);
//			C10R7 = new Element("Column 10 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[7]"), this);
//			C10R8 = new Element("Column 10 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[8]"), this); 
//			C10R9 = new Element("Column 10 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[9]"), this);
//			C10R10 = new Element("Column 10 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[10]"), this);
//			C10R11 = new Element("Column 10 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[11]"), this);
//			C10R12 = new Element("Column 10 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[12]"), this);
//			C10R13 = new Element("Column 10 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[13]"), this);
//			C10R14 = new Element("Column 10 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[14]"), this);
//			C10R15 = new Element("Column 10 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[15]"), this);
			
			TechLabel11 = new Element("Crowdsourcing", By.xpath("(//*[@transform='translate(538, 280) rotate(-90)'])[1]"), this);
			C11R1 = new Element("Column 11 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[1]"), this);
			C11R2 = new Element("Column 11 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[2]"), this);
			C11R3 = new Element("Column 11 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[3]"), this);
//			C11R4 = new Element("Column 11 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[4]"), this);
//			C11R5 = new Element("Column 11 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[5]"), this);
//			C11R6 = new Element("Column 11 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[6]"), this);
//			C11R7 = new Element("Column 11 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[7]"), this);
//			C11R8 = new Element("Column 11 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[8]"), this); 
//			C11R9 = new Element("Column 11 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[9]"), this);
//			C11R10 = new Element("Column 11 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[10]"), this);
//			C11R11 = new Element("Column 11 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[11]"), this);
//			C11R12 = new Element("Column 11 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[12]"), this);
//			C11R13 = new Element("Column 11 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[13]"), this);
//			C11R14 = new Element("Column 11 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[14]"), this);
//			C11R15 = new Element("Column 11 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[15]"), this);
			
			TechLabel12 = new Element("Extended Reality", By.xpath("(//*[@transform='translate(570, 280) rotate(-90)'])[1]"), this);
			C12R1 = new Element("Column 12 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[1]"), this);
			C12R2 = new Element("Column 12 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[2]"), this);
			C12R3 = new Element("Column 12 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[3]"), this);
//			C12R4 = new Element("Column 12 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[4]"), this);
//			C12R5 = new Element("Column 12 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[5]"), this);
//			C12R6 = new Element("Column 12 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[6]"), this);
//			C12R7 = new Element("Column 12 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[7]"), this);
//			C12R8 = new Element("Column 12 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[8]"), this); 
//			C12R9 = new Element("Column 12 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[9]"), this);
//			C12R10 = new Element("Column 12 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[10]"), this);
//			C12R11 = new Element("Column 12 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[11]"), this);
//			C12R12 = new Element("Column 12 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[12]"), this);
//			C12R13 = new Element("Column 12 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[13]"), this);
//			C12R14 = new Element("Column 12 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[14]"), this);
//			C12R15 = new Element("Column 12 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[15]"), this);
			
			TechLabel13 = new Element("Human Augmentation", By.xpath("(//*[@transform='translate(602, 280) rotate(-90)'])[1]"), this);
			C13R1 = new Element("Column 13 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[1]"), this);
			C13R2 = new Element("Column 13 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[2]"), this);
			C13R3 = new Element("Column 13 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[3]"), this);
//			C13R4 = new Element("Column 13 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[4]"), this);
//			C13R5 = new Element("Column 13 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[5]"), this);
//			C13R6 = new Element("Column 13 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[6]"), this);
//			C13R7 = new Element("Column 13 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[7]"), this);
//			C13R8 = new Element("Column 13 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[8]"), this); 
//			C13R9 = new Element("Column 13 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[9]"), this);
//			C13R10 = new Element("Column 13 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[10]"), this);
//			C13R11 = new Element("Column 13 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[11]"), this);
//			C13R12 = new Element("Column 13 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[12]"), this);
//			C13R13 = new Element("Column 13 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[13]"), this);
//			C13R14 = new Element("Column 13 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[14]"), this);
//			C13R15 = new Element("Column 13 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[15]"), this);
			
			TechLabel14 = new Element("Industry 4.0", By.xpath("(//*[@transform='translate(634, 280) rotate(-90)'])[1]"), this);
			C14R1 = new Element("Column 14 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[1]"), this);
			C14R2 = new Element("Column 14 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[2]"), this);
			C14R3 = new Element("Column 14 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[3]"), this);
//			C14R4 = new Element("Column 14 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[4]"), this);
//			C14R5 = new Element("Column 14 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[5]"), this);
//			C14R6 = new Element("Column 14 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[6]"), this);
//			C14R7 = new Element("Column 14 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[7]"), this);
//			C14R8 = new Element("Column 14 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[8]"), this); 
//			C14R9 = new Element("Column 14 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[9]"), this);
//			C14R10 = new Element("Column 14 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[10]"), this);
//			C14R11 = new Element("Column 14 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[11]"), this);
//			C14R12 = new Element("Column 14 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[12]"), this);
//			C14R13 = new Element("Column 14 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[13]"), this);
//			C14R14 = new Element("Column 14 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[14]"), this);
//			C14R15 = new Element("Column 14 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[15]"), this);
			
			TechLabel15 = new Element("Interactive", By.xpath("(//*[@transform='translate(666, 280) rotate(-90)'])[1]"), this);
			C15R1 = new Element("Column 15 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[1]"), this);
			C15R2 = new Element("Column 15 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[2]"), this);
			C15R3 = new Element("Column 15 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[3]"), this);
//			C15R4 = new Element("Column 15 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[4]"), this);
//			C15R5 = new Element("Column 15 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[5]"), this);
//			C15R6 = new Element("Column 15 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[6]"), this);
//			C15R7 = new Element("Column 15 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[7]"), this);
//			C15R8 = new Element("Column 15 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[8]"), this); 
//			C15R9 = new Element("Column 15 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[9]"), this);
//			C15R10 = new Element("Column 15 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[10]"), this);
//			C15R11 = new Element("Column 15 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[11]"), this);
//			C15R12 = new Element("Column 15 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[12]"), this);
//			C15R13 = new Element("Column 15 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[13]"), this);
//			C15R14 = new Element("Column 15 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[14]"), this);
//			C15R15 = new Element("Column 15 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[15]"), this);
			
			TechLabel16 = new Element("IoT", By.xpath("(//*[@transform='translate(698, 280) rotate(-90)'])[1]"), this);
			C16R1 = new Element("Column 16 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[1]"), this);
			C16R2 = new Element("Column 16 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[2]"), this);
			C16R3 = new Element("Column 16 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[3]"), this);
//			C16R4 = new Element("Column 16 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[4]"), this);
//			C16R5 = new Element("Column 16 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[5]"), this);
//			C16R6 = new Element("Column 16 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[6]"), this);
//			C16R7 = new Element("Column 16 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[7]"), this);
//			C16R8 = new Element("Column 16 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[8]"), this); 
//			C16R9 = new Element("Column 16 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[9]"), this);
//			C16R10 = new Element("Column 16 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[10]"), this);
//			C16R11 = new Element("Column 16 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[11]"), this);
//			C16R12 = new Element("Column 16 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[12]"), this);
//			C16R13 = new Element("Column 16 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[13]"), this);
//			C16R14 = new Element("Column 16 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[14]"), this);
//			C16R15 = new Element("Column 16 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[15]"), this);
			
			TechLabel17 = new Element("Mobile", By.xpath("(//*[@transform='translate(730, 280) rotate(-90)'])[1]"), this);
			C17R1 = new Element("Column 17 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[1]"), this);
			C17R2 = new Element("Column 17 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[2]"), this);
			C17R3 = new Element("Column 17 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[3]"), this);
//			C17R4 = new Element("Column 17 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[4]"), this);
//			C17R5 = new Element("Column 17 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[5]"), this);
//			C17R6 = new Element("Column 17 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[6]"), this);
//			C17R7 = new Element("Column 17 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[7]"), this);
//			C17R8 = new Element("Column 17 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[8]"), this); 
//			C17R9 = new Element("Column 17 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[9]"), this);
//			C17R10 = new Element("Column 17 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[10]"), this);
//			C17R11 = new Element("Column 17 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[11]"), this);
//			C17R12 = new Element("Column 17 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[12]"), this);
//			C17R13 = new Element("Column 17 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[13]"), this);
//			C17R14 = new Element("Column 17 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[14]"), this);
//			C17R15 = new Element("Column 17 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[15]"), this);
			
			TechLabel18 = new Element("Quantum Computing", By.xpath("(//*[@transform='translate(762, 280) rotate(-90)'])[1]"), this);
			C18R1 = new Element("Column 18 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[1]"), this);
			C18R2 = new Element("Column 18 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[2]"), this);
			C18R3 = new Element("Column 18 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[3]"), this);
//			C18R4 = new Element("Column 18 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[4]"), this);
//			C18R5 = new Element("Column 18 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[5]"), this);
//			C18R6 = new Element("Column 18 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[6]"), this);
//			C18R7 = new Element("Column 18 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[7]"), this);
//			C18R8 = new Element("Column 18 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[8]"), this); 
//			C18R9 = new Element("Column 18 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[9]"), this);
//			C18R10 = new Element("Column 18 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[10]"), this);
//			C18R11 = new Element("Column 18 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[11]"), this);
//			C18R12 = new Element("Column 18 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[12]"), this);
//			C18R13 = new Element("Column 18 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[13]"), this);
//			C18R14 = new Element("Column 18 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[14]"), this);
//			C18R15 = new Element("Column 18 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[15]"), this);
			
			TechLabel19 = new Element("Robots and drones", By.xpath("(//*[@transform='translate(794, 280) rotate(-90)'])[1]"), this);
			C19R1 = new Element("Column 19 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[1]"), this);
			C19R2 = new Element("Column 19 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[2]"), this);
			C19R3 = new Element("Column 19 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[3]"), this);
//			C19R4 = new Element("Column 19 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[4]"), this);
//			C19R5 = new Element("Column 19 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[5]"), this);
//			C19R6 = new Element("Column 19 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[6]"), this);
//			C19R7 = new Element("Column 19 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[7]"), this);
//			C19R8 = new Element("Column 19 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[8]"), this); 
//			C19R9 = new Element("Column 19 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[9]"), this);
//			C19R10 = new Element("Column 19 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[10]"), this);
//			C19R11 = new Element("Column 19 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[11]"), this);
//			C19R12 = new Element("Column 19 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[12]"), this);
//			C19R13 = new Element("Column 19 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[13]"), this);
//			C19R14 = new Element("Column 19 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[14]"), this);
//			C19R15 = new Element("Column 19 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[15]"), this);
			
			TechLabel20 = new Element("Security", By.xpath("(//*[@transform='translate(826, 280) rotate(-90)'])[1]"), this);
			C20R1 = new Element("Column 20 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[1]"), this);
			C20R2 = new Element("Column 20 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[2]"), this);
			C20R3 = new Element("Column 20 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[3]"), this);
//			C20R4 = new Element("Column 20 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[4]"), this);
//			C20R5 = new Element("Column 20 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[5]"), this);
//			C20R6 = new Element("Column 20 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[6]"), this);
//			C20R7 = new Element("Column 20 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[7]"), this);
//			C20R8 = new Element("Column 20 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[8]"), this); 
//			C20R9 = new Element("Column 20 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[9]"), this);
//			C20R10 = new Element("Column 20 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[10]"), this);
//			C20R11 = new Element("Column 20 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[11]"), this);
//			C20R12 = new Element("Column 20 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[12]"), this);
//			C20R13 = new Element("Column 20 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[13]"), this);
//			C20R14 = new Element("Column 20 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[14]"), this);
//			C20R15 = new Element("Column 20 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[15]"), this);
			
			TechLabel21 = new Element("Social/Collaboration", By.xpath("(//*[@transform='translate(858, 280) rotate(-90)'])[1]"), this);
			C21R1 = new Element("Column 21 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[1]"), this);
			C21R2 = new Element("Column 21 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[2]"), this);
			C21R3 = new Element("Column 21 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[3]"), this);
//			C21R4 = new Element("Column 21 Row 4", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[4]"), this);
//			C21R5 = new Element("Column 21 Row 5", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[5]"), this);
//			C21R6 = new Element("Column 21 Row 6", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[6]"), this);
//			C21R7 = new Element("Column 21 Row 7", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[7]"), this);
//			C21R8 = new Element("Column 21 Row 8", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[8]"), this); 
//			C21R9 = new Element("Column 21 Row 9", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[9]"), this);
//			C21R10 = new Element("Column 21 Row 10", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[10]"), this);
//			C21R11 = new Element("Column 21 Row 11", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[11]"), this);
//			C21R12 = new Element("Column 21 Row 12", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[12]"), this);
//			C21R13 = new Element("Column 21 Row 13", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[13]"), this);
//			C21R14 = new Element("Column 21 Row 14", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[14]"), this);
//			C21R15 = new Element("Column 21 Row 15", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[15]"), this);
			
			
			
			//BusinessDataTable
			BizTable = new Element("Business Data Table", By.xpath("(//*[@transform='translate(200, 300)'])[2]"), this);
			BizComp1 = new Element("The Walt Disney Company", By.xpath("(//*[@transform='translate(180, 0)'])[2]"), this);
			BizComp2 = new Element("Netflix, Inc.", By.xpath("(//*[@transform='translate(180, 32)'])[2]"), this);
			BizComp3 = new Element("Vivendi SA", By.xpath("(//*[@transform='translate(180, 64)'])[2]"), this);
			
			BizLabel1 = new Element("Asset utilization", By.xpath("(//*[@transform='translate(218, 280) rotate(-90)'])[2]"), this);
			BizC1R1 = new Element("Column 1 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[5]"), this);
			BizC1R2 = new Element("Column 1 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[6]"), this);
			BizC1R3 = new Element("Column 1 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(0, 0)'])[7]"), this);
			
			BizLabel2 = new Element("Brand Value and Corporate Image", By.xpath("(//*[@transform='translate(250, 280) rotate(-90)'])[2]"), this);			
			BizC2R1 = new Element("Column 2 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[5]"), this);
			BizC2R2 = new Element("Column 2 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[6]"), this);
			BizC2R3 = new Element("Column 2 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(32, 0)'])[7]"), this);
			
			BizLabel3 = new Element("Compliance", By.xpath("(//*[@transform='translate(282, 280) rotate(-90)'])[2]"), this);
			BizC3R1 = new Element("Column 3 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[5]"), this);
			BizC3R2 = new Element("Column 3 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[6]"), this);
			BizC3R3 = new Element("Column 3 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(64, 0)'])[7]"), this);
			
			BizLabel4 = new Element("Corporate Social Respo.", By.xpath("(//*[@transform='translate(314, 280) rotate(-90)'])[2]"), this);
			BizC4R1 = new Element("Column 4 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[5]"), this);
			BizC4R2 = new Element("Column 4 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[6]"), this);
			BizC4R3 = new Element("Column 4 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(96, 0)'])[7]"), this);
			
			
			BizLabel5 = new Element("Cost cutting", By.xpath("(//*[@transform='translate(346, 280) rotate(-90)'])[2]"), this);
			BizC5R1 = new Element("Column 5 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[5]"), this);
			BizC5R2 = new Element("Column 5 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[6]"), this);
			BizC5R3 = new Element("Column 5 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(128, 0)'])[7]"), this);
						
			BizLabel6 = new Element("Cost model and financial rules", By.xpath("(//*[@transform='translate(378, 280) rotate(-90)'])[2]"), this);
			BizC6R1 = new Element("Column 6 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[5]"), this);
			BizC6R2 = new Element("Column 6 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[6]"), this);
			BizC6R3 = new Element("Column 6 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(160, 0)'])[7]"), this);
			
			BizLabel7 = new Element("Cost optimization", By.xpath("(//*[@transform='translate(410, 280) rotate(-90)'])[2]"), this);
			BizC7R1 = new Element("Column 7 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[5]"), this);
			BizC7R2 = new Element("Column 7 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[6]"), this);
			BizC7R3 = new Element("Column 7 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(192, 0)'])[7]"), this);
						
			BizLabel8 = new Element("Cross-selling up-selling", By.xpath("(//*[@transform='translate(442, 280) rotate(-90)'])[2]"), this);
			BizC8R1 = new Element("Column 8 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[5]"), this);
			BizC8R2 = new Element("Column 8 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[6]"), this);
			BizC8R3 = new Element("Column 8 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(224, 0)'])[7]"), this);
						
			BizLabel9 = new Element("Culture, people, employee engagement", By.xpath("(//*[@transform='translate(474, 280) rotate(-90)'])[2]"), this);
			BizC9R1 = new Element("Column 9 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[5]"), this);
			BizC9R2 = new Element("Column 9 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[6]"), this);
			BizC9R3 = new Element("Column 9 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(256, 0)'])[7]"), this);
			
			BizLabel10 = new Element("Customer acquisition (new customers)", By.xpath("(//*[@transform='translate(506, 280) rotate(-90)'])[2]"), this);
			BizC10R1 = new Element("Column 10 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[5]"), this);
			BizC10R2 = new Element("Column 10 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[6]"), this);
			BizC10R3 = new Element("Column 10 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(288, 0)'])[7]"), this);
			
			BizLabel11 = new Element("Customer retention", By.xpath("(//*[@transform='translate(538, 280) rotate(-90)'])[2]"), this);
			BizC11R1 = new Element("Column 11 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[5]"), this);
			BizC11R2 = new Element("Column 11 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[6]"), this);
			BizC11R3 = new Element("Column 11 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(320, 0)'])[7]"), this);
			
			BizLabel12 = new Element("Customer satisfaction and user centricity", By.xpath("(//*[@transform='translate(570, 280) rotate(-90)'])[2]"), this);
			BizC12R1 = new Element("Column 12 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[5]"), this);
			BizC12R2 = new Element("Column 12 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[6]"), this);
			BizC12R3 = new Element("Column 12 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(352, 0)'])[7]"), this);
						
			BizLabel13 = new Element("Ecosystem Experience, Alliances, Partnerships", By.xpath("(//*[@transform='translate(602, 280) rotate(-90)'])[2]"), this);
			BizC13R1 = new Element("Column 13 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[5]"), this);
			BizC13R2 = new Element("Column 13 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[6]"), this);
			BizC13R3 = new Element("Column 13 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(384, 0)'])[7]"), this);
			
			BizLabel14 = new Element("Financial risk reduction", By.xpath("(//*[@transform='translate(634, 280) rotate(-90)'])[2]"), this);
			BizC14R1 = new Element("Column 14 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[5]"), this);
			BizC14R2 = new Element("Column 14 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[6]"), this);
			BizC14R3 = new Element("Column 14 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(416, 0)'])[7]"), this);
			
			BizLabel15 = new Element("M&A", By.xpath("(//*[@transform='translate(666, 280) rotate(-90)'])[2]"), this);
			BizC15R1 = new Element("Column 15 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[5]"), this);
			BizC15R2 = new Element("Column 15 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[6]"), this);
			BizC15R3 = new Element("Column 15 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(448, 0)'])[7]"), this);
						
			BizLabel16 = new Element("New and digital distribution channels", By.xpath("(//*[@transform='translate(698, 280) rotate(-90)'])[2]"), this);
			BizC16R1 = new Element("Column 16 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[5]"), this);
			BizC16R2 = new Element("Column 16 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[6]"), this);
			BizC16R3 = new Element("Column 16 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(480, 0)'])[7]"), this);
			
			BizLabel17 = new Element("New geographic markets and international growth", By.xpath("(//*[@transform='translate(730, 280) rotate(-90)'])[2]"), this);
			BizC17R1 = new Element("Column 17 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[5]"), this);
			BizC17R2 = new Element("Column 17 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[6]"), this);
			BizC17R3 = new Element("Column 17 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(512, 0)'])[7]"), this);
						
			BizLabel18 = new Element("New and adjacent products and services", By.xpath("(//*[@transform='translate(762, 280) rotate(-90)'])[2]"), this);
			BizC18R1 = new Element("Column 18 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[5]"), this);
			BizC18R2 = new Element("Column 18 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[6]"), this);
			BizC18R3 = new Element("Column 18 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(544, 0)'])[7]"), this);
			
			BizLabel19 = new Element("New and digital communication channels", By.xpath("(//*[@transform='translate(794, 280) rotate(-90)'])[2]"), this);
			BizC19R1 = new Element("Column 19 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[5]"), this);
			BizC19R2 = new Element("Column 19 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[6]"), this);
			BizC19R3 = new Element("Column 19 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(576, 0)'])[7]"), this);
			
			BizLabel20 = new Element("New business models", By.xpath("(//*[@transform='translate(826, 280) rotate(-90)'])[2]"), this);
			BizC20R1 = new Element("Column 20 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[5]"), this);
			BizC20R2 = new Element("Column 20 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[6]"), this);
			BizC20R3 = new Element("Column 20 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(608, 0)'])[7]"), this);
			
			BizLabel21 = new Element("Operational risk reduction", By.xpath("(//*[@transform='translate(858, 280) rotate(-90)'])[2]"), this);
			BizC21R1 = new Element("Column 21 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[5]"), this);
			BizC21R2 = new Element("Column 21 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[6]"), this);
			BizC21R3 = new Element("Column 21 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(640, 0)'])[7]"), this);
			
			BizLabel22 = new Element("Organization and organizational resilience", By.xpath("//*[@transform='translate(890, 280) rotate(-90)']"), this);
			BizC221R1 = new Element("Column 22 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(672, 0)'])[1]"), this);
			BizC22R2 = new Element("Column 22 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(672, 0)'])[2]"), this);
			BizC22R3 = new Element("Column 22 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(672, 0)'])[3]"), this);
			
			BizLabel23 = new Element("Process efficiency, process and operations management", By.xpath("//*[@transform='translate(922, 280) rotate(-90)']"), this);
			BizC23R1 = new Element("Column 23 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(704, 0)'])[1]"), this);
			BizC23R2 = new Element("Column 23 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(704, 0)'])[2]"), this);
			BizC23R3 = new Element("Column 23 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(704, 0)'])[3]"), this);
			
			BizLabel24 = new Element("Productivity", By.xpath("//*[@transform='translate(954, 280) rotate(-90)']"), this);
			BizC24R1 = new Element("Column 24 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(736, 0)'])[1]"), this);
			BizC24R2 = new Element("Column 24 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(736, 0)'])[2]"), this);
			BizC24R3 = new Element("Column 24 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(736, 0)'])[3]"), this);
			
			BizLabel25 = new Element("Skills", By.xpath("//*[@transform='translate(986, 280) rotate(-90)']"), this);
			BizC25R1 = new Element("Column 25 Row 1", By.xpath("(//*[@class='line']//*[@transform='translate(768, 0)'])[1]"), this);
			BizC25R2 = new Element("Column 25 Row 2", By.xpath("(//*[@class='line']//*[@transform='translate(768, 0)'])[2]"), this);
			BizC25R3 = new Element("Column 25 Row 3", By.xpath("(//*[@class='line']//*[@transform='translate(768, 0)'])[3]"), this);
			
			//Investments
			InvComp1 = new Element("THE VOID", By.xpath("//td[text()=' THE VOID ']"), this);
			InvComp2 = new Element("Quibi", By.xpath("//td[text()=' Quibi ']"), this);
			InvComp3 = new Element("Sphero", By.xpath("//td[text()=' Sphero ']"), this);
			InvDesc1 = new Element("THE VOID Desciption", By.xpath(" //td[text()=' THE VOID builds and operates virtual entertainment centers that primarily focus on exploring immersive virtual worlds and dimensions. ']"), this);
			InvDesc2 = new Element("Quibi Description ", By.xpath("//td[text()=' Quibi is a media company developing short-form media content designed for smartphones. ']"), this);
			InvDesc3 = new Element("Sphero Description", By.xpath("//td[text()=' Sphero bridges the gap between the real world and the virtual world with its smartphone-controlled robots. ']"), this);
			InvRnd1 = new Element("Round 1", By.xpath("(//td[text()='series unknown'])[1]"), this);
			InvRnd2 = new Element("Round 2", By.xpath("//td[text()='private equity']"), this);
			InvRnd3 = new Element("Round 3", By.xpath("(//td[text()='series unknown'])[2]"), this);
			InvTMR1 = new Element("Total Money Raised 1", By.xpath("//td[text()='$20,000,000.00']"), this);
			InvTMR2 = new Element("Total Money Raised 2", By.xpath("//td[text()='$1,000,000,000.00']"), this);
			InvTMR3 = new Element("Total Money Raised 3", By.xpath("//td[text()='$120,261,863.00']"), this);
			InvDate1 = new Element("Date 1", By.xpath("//td[text()='7/15/2019']"), this);
			InvDate2 = new Element("Date 2", By.xpath("//td[text()='8/7/2018']"), this);
			InvDate3 = new Element("Date 3", By.xpath("//td[text()='6/5/2018']"), this);
			InvScore = new Element("Investment Sheldon Score", By.xpath("//a[text()='59%']"), this);
			
			//Acquisitions
			AcqComp1 = new Element("Hulu", By.xpath("//td[text()=' Hulu ']"), this);
			AcqComp2 = new Element("21st Century Fox", By.xpath("//td[text()=' 21st Century Fox ']"), this);
			AcqDesc1 = new Element("Hulu Description ", By.xpath("//td[text()=' Hulu is an online video service that offers a selection of hit shows, clips, movies, and documentaries through its website.  ']"), this);
			AcqDesc2 = new Element("21st Century Fox Description", By.xpath("//td[text()=' 21st Century Fox is an American mass media corporation primarily dealing in the film and television industries. ']"), this);
			AcqTMR1 = new Element("Total Money Raised 1", By.xpath("//td[text()='$683,000,000.00']"), this);
			AcqDate1 = new Element("Date 1", By.xpath("//td[text()='5/14/2019']"), this);
			AcqDate2 = new Element("Date 2", By.xpath("//td[text()='12/14/2017']"), this);
			AcqScore = new Element("Acquisition Sheldon Score", By.xpath("//a[text()='36%']"), this);
			
		}
	}	
}
