package pageobjects;

import org.openqa.selenium.By;

import auto.framework.PageBase;
import auto.framework.web.Element;
import auto.framework.web.TextBox;

public class VIPCompetitorPage extends PageBase{
	
	public static final Contents contents = new Contents();
	
	public static class Contents extends Element{
		
		public final Element CompetitorTitle;
		public final Element TargetCompRevenue;
		public final Element CompetitorNoResults;
		public final Element TargetCompName;
		public final Element CompetitorSearchbox;
		public final Element CompetitorSearchTypeahead;
		public final Element Competitors1stPeers;
		public final Element Competitors2ndPeers;
		public final Element Competitors3rdPeers;
		public final Element Competitors4thPeers;
		public final Element Competitors5thPeers;
		public final Element Competitors6thPeers;
		public final Element Competitors7thPeers;
		public final Element Competitors8thPeers;
		public final Element Competitors9thPeers;
		public final Element Competitors10thPeers;
		public final Element Competitors11thPeers;
		public final Element Competitors12thPeers;
		public final Element Competitors13thPeers;
		public final Element Competitors14thPeers;
		public final Element Competitors15thPeers;
		public final Element Competitors16thPeers;
		public final Element Competitors17thPeers;
		public final Element Competitors18thPeers;
		public final Element Competitors19thPeers;
		public final Element Competitors20thPeers;
		public final Element Competitors21thPeers;
		public final Element Competitors22thPeers;
		public final Element Competitors23thPeers;
		public final Element Competitors24thPeers;
		public final Element Competitors25thPeers;
		public final Element Competitors26thPeers;
		public final Element CompetitorsPeersDeleteButton;
		public final Element CompetitorsPeersDeleteLoadingIcon;
		public final Element PeersCounter;
		public final Element VerticalLine;
		public final Element RefineCriteriaText;
		public final Element RefineCriteriaButton;
		public final Element RefineCriteriaModal;
		public final Element RefineCriteriaCloseButton;
		public final Element SelectRegionAccordionCollapsed;
		public final Element SelectRegionAccordionExpanded;
		public final Element SelectRegionDropdown;
		public final Element SelectCountryDropdown;
		public final Element SetRevenueAccordionCollapsed;
		public final Element SetRevenueAccordionExpanded;
		public final TextBox RevenueMin;
		public final TextBox RevenueMax;
		public final TextBox MarketCapMin;
		public final TextBox MarketCapMax;
		public final Element SaveCriteriaButton;
		public final Element NameCriteriaTextBox;
		public final Element NameCriteriaCloseButton;
		public final Element DoneCriteriaButton;
		public final Element PreSavedCriteriaAccordionCollapsed;
		public final Element PreSavedCriteriaAccordionExpanded;
		public final Element PreSavedCriteriaDropdown;
		public final Element PreSavedCriteriaDropdownMenu;
		public final Element ApplyCriteriaButton;
		public final Element TopFilterDropdown;
		public final Element TopFilterChoice15;
		public final Element TopFilterChoice25;
		public final TextBox TargetCompAlias1;
		public final TextBox NewTargetCompAlias;
		public final TextBox FirstPeerAlias1;
		public final TextBox NewFirstPeerAlias;
		public final TextBox TargetCompAlias2;
		public final TextBox FirstPeerAlias2;
		public final TextBox ReportSummaryPeer1;
		public final TextBox ReportSummaryPeer2;
		public final TextBox ReportSummaryPeer3;
		public final TextBox ReportSummaryPeer4;
		public final TextBox ReportSummaryPeer5;
		public final TextBox ReportSummaryPeer6;
		public final TextBox ReportSummaryPeer7;
		public final TextBox ReportSummaryPeer8;
		public final TextBox ReportSummaryPeer9;
		public final TextBox ReportSummaryPeer10;
		public final TextBox ReportSummaryPeer11;
		public final TextBox ReportSummaryPeer12;
		public final TextBox ReportSummaryPeer13;
		public final TextBox ReportSummaryPeer14;
		public final TextBox ReportSummaryPeer15;
		public final TextBox ReportSummaryDashboard1;
		public final TextBox ReportSummaryDashboard2;
		public final TextBox ReportSummaryDashboard3;
		public final TextBox ReportSummaryDashboard4;
		public final TextBox ReportSummaryDashboard5;
		public final TextBox ReportSummaryDashboard6;
		public final TextBox ReportSummaryDashboard7;
		public final TextBox ReportSummaryDashboard8;
		public final TextBox ReportSummaryDashboard9;
		public final TextBox ReportSummaryDashboard10;
		public final TextBox ReportSummaryDashboard11;
		public final TextBox ReportSummaryDashboard12;
		public final TextBox ReportSummaryDashboard13;
		public final TextBox ReportSummaryDashboard14;
		public final TextBox ReportSummaryDashboard15;
		public final TextBox ReportSummaryDashboard16;
		public final TextBox ReportSummaryDashboard17;
		public final TextBox Revenue1;
		public final TextBox Revenue2;
		public final TextBox Revenue3;
		public final TextBox Revenue4;
		public final TextBox Revenue5;
		public final TextBox Revenue6;
		public final TextBox Revenue7;
		public final TextBox Revenue8;
		public final TextBox Revenue9;
		public final TextBox Revenue10;
		public final TextBox Revenue11;
		public final TextBox Revenue12;
		public final TextBox Revenue13;
		public final TextBox Revenue14;
		public final TextBox Revenue15;
		public final TextBox Revenue16;
		public final TextBox Revenue17;
		public final TextBox Revenue18;
		public final TextBox Revenue19;
		public final TextBox Revenue20;
		public final TextBox Revenue21;
		public final TextBox Revenue22;
		public final TextBox Revenue23;
		public final TextBox Revenue24;
		public final TextBox Revenue25;
		public final TextBox Symbol1;
		public final TextBox Symbol2;
		public final TextBox Symbol3;
		public final TextBox Symbol4;
		public final TextBox Symbol5;
		public final TextBox Symbol6;
		public final TextBox Symbol7;
		public final TextBox Symbol8;
		public final TextBox Symbol9;
		public final TextBox Symbol10;
		public final TextBox Symbol11;
		public final TextBox Symbol12;
		public final TextBox Symbol13;
		public final TextBox Symbol14;
		public final TextBox Symbol15;
		public final Element CurratedNote;
		public final Element CurratedNoteHighlight;
		public final Element CompanyNameHeader;
		public final Element IndustryLocationHeader;
		public final Element LatestFinancialsHeader;
		public final Element RevenueHeader;
		public final Element MarketCapHeader;
		public final Element AliasHeader;
		public final Element AliasIcon;
		public final Element TooltipText;
		public final Element TargetIndustry;
		public final Element PeerIndustry1;
		public final Element PeerIndustry2;
		public final Element PeerIndustry3;
		public final Element PeerIndustry4;
		public final Element PeerIndustry5;
		public final Element PeerIndustry6;
		public final Element PeerIndustry7;
		public final Element PeerIndustry8;
		public final Element PeerIndustry9;
		public final Element PeerIndustry10;
		public final Element PeerIndustry11;
		public final Element PeerIndustry12;
		public final Element PeerIndustry13;
		public final Element PeerIndustry14;
		public final Element PeerIndustry15;
		public final Element TargetFinancials;
		public final Element TargetRevenue;
		public final Element TargetMarketCap;
		public final Element TargetAlias;
		public final Element Peer1Financials;
		public final Element Peer2Financials;
		public final Element Peer3Financials;
		public final Element Peer4Financials;
		public final Element Peer5Financials;
		public final Element Peer6Financials;
		public final Element Peer7Financials;
		public final Element Peer8Financials;
		public final Element Peer9Financials;
		public final Element Peer10Financials;
		public final Element Peer11Financials;
		public final Element Peer12Financials;
		public final Element Peer13Financials;
		public final Element Peer14Financials;
		public final Element Peer15Financials;
		public final Element Peer1MarketCap;
		public final Element Peer2MarketCap;
		public final Element Peer3MarketCap;
		public final Element Peer4MarketCap;
		public final Element Peer5MarketCap;
		public final Element Peer6MarketCap;
		public final Element Peer7MarketCap;
		public final Element Peer8MarketCap;
		public final Element Peer9MarketCap;
		public final Element Peer10MarketCap;
		public final Element Peer11MarketCap;
		public final Element Peer12MarketCap;
		public final Element Peer13MarketCap;
		public final Element Peer14MarketCap;
		public final Element Peer15MarketCap;
		public final Element Peer1Alias;
		public final Element DisclaimerHeader;
		public final Element Disclaimer1;
		public final Element Disclaimer2;
		public final Element Disclaimer3;
		public final Element Disclaimer4;
		public final Element Disclaimer5;
		public final Element TargetCountry;
		public final Element PeerCountry1;
		public final Element PeerCountry2;
		public final Element PeerCountry3;
		public final Element PeerCountry4;
		public final Element PeerCountry5;
		public final Element PeerCountry6;
		public final Element PeerCountry7;
		public final Element PeerCountry8;
		public final Element PeerCountry9;
		public final Element PeerCountry10;
		public final Element PeerCountry11;
		public final Element PeerCountry12;
		public final Element PeerCountry13;
		public final Element PeerCountry14;
		public final Element PeerCountry15;
		
		
//		String TargetCompNameData1 = VIPCompetitorPage.contents.TargetCompName.getText();
//		String FirstPeerCompNameData1 = VIPCompetitorPage.contents.Competitors1stPeers.getText();
//		String TargetCompNameData2 = "123456789012345678";
//		String FirstPeerCompNameData2 = "123456789012345678";
		
		public Contents() {
			super("Container", By.className("mainContainer"));
			
			CompetitorTitle = new Element("Competitor Title", By.xpath("//*[@class='competitors-title']"), this);
			TargetCompRevenue = new Element("Target Company Revenue Value", By.xpath("//*[@class='competitors-peers-target-rev']"), this);
			CompetitorNoResults = new Element("No Results Message", By.xpath("//*[@class='competitors-peers-message ng-star-inserted']"), this);
			TargetCompName = new Element("Target Company Name", By.xpath("//*[@class='competitors-peers-target-compname']"), this);
			CompetitorSearchbox = new Element("Competitor Search box", By.xpath("//*[@class='tool-competitors-wrapper']//*[@type='text']"), this);
			CompetitorSearchTypeahead = new Element("Competitor Search Typeahead", By.xpath("//*[@class='typeahead typeahead-competitors']//*[@class='typeahead-item ng-star-inserted'][1]"), this);
			Competitors1stPeers = new Element("Competitors 1st Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][1]//*[@class='competitors-peers-item-compname']"), this);
			Competitors2ndPeers = new Element("Competitors 2nd Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][2]//*[@class='competitors-peers-item-compname']"), this);
			Competitors3rdPeers = new Element("Competitors 3rd Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][3]//*[@class='competitors-peers-item-compname']"), this);
			Competitors4thPeers = new Element("Competitors 4th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][4]//*[@class='competitors-peers-item-compname']"), this);
			Competitors5thPeers = new Element("Competitors 5th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][5]//*[@class='competitors-peers-item-compname']"), this);
			Competitors6thPeers = new Element("Competitors 6th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][6]//*[@class='competitors-peers-item-compname']"), this);
			Competitors7thPeers = new Element("Competitors 7th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][7]//*[@class='competitors-peers-item-compname']"), this);
			Competitors8thPeers = new Element("Competitors 8th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][8]//*[@class='competitors-peers-item-compname']"), this);
			Competitors9thPeers = new Element("Competitors 9th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][9]//*[@class='competitors-peers-item-compname']"), this);
			Competitors10thPeers = new Element("Competitors 10th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][10]//*[@class='competitors-peers-item-compname']"), this);
			Competitors11thPeers = new Element("Competitors 11th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][11]//*[@class='competitors-peers-item-compname']"), this);
			Competitors12thPeers = new Element("Competitors 12th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][12]//*[@class='competitors-peers-item-compname']"), this);
			Competitors13thPeers = new Element("Competitors 13th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][13]//*[@class='competitors-peers-item-compname']"), this);
			Competitors14thPeers = new Element("Competitors 14th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][14]//*[@class='competitors-peers-item-compname']"), this);
			Competitors15thPeers = new Element("Competitors 15th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][15]//*[@class='competitors-peers-item-compname']"), this);
			Competitors16thPeers = new Element("Competitors 16th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][16]//*[@class='competitors-peers-item-compname']"), this);
			Competitors17thPeers = new Element("Competitors 17th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][17]//*[@class='competitors-peers-item-compname']"), this);
			Competitors18thPeers = new Element("Competitors 18th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][18]//*[@class='competitors-peers-item-compname']"), this);
			Competitors19thPeers = new Element("Competitors 19th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][19]//*[@class='competitors-peers-item-compname']"), this);
			Competitors20thPeers = new Element("Competitors 20th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][20]//*[@class='competitors-peers-item-compname']"), this);
			Competitors21thPeers = new Element("Competitors 21th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][21]//*[@class='competitors-peers-item-compname']"), this);
			Competitors22thPeers = new Element("Competitors 22th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][22]//*[@class='competitors-peers-item-compname']"), this);
			Competitors23thPeers = new Element("Competitors 23th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][23]//*[@class='competitors-peers-item-compname']"), this);
			Competitors24thPeers = new Element("Competitors 24th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][24]//*[@class='competitors-peers-item-compname']"), this);
			Competitors25thPeers = new Element("Competitors 25th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][25]//*[@class='competitors-peers-item-compname']"), this);
			Competitors26thPeers = new Element("Competitors 26th Peers", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][26]//*[@class='competitors-peers-item-compname']"), this);
			CompetitorsPeersDeleteButton = new Element("Competitors Peers Delete Button", By.xpath("//*[@class='competitors-peers-item-delete ng-star-inserted']"), this);
			CompetitorsPeersDeleteLoadingIcon = new Element("Competitors Peers Delete Loading Icon", By.xpath("//*[@class='loading1 ng-star-inserted']"), this);
			PeersCounter = new Element("Peers Counter", By.xpath("//*[@class='competitors-count ng-star-inserted']"), this);
			VerticalLine = new Element("Vertical | Line", By.xpath("//*[@class='competitors-verticalline ng-star-inserted']"), this);
			RefineCriteriaText = new Element("Refine Criteria ", By.xpath("//*[@class='competitors-criteria ng-star-inserted']"), this);
			RefineCriteriaButton = new Element("Refine Criteria Button", By.xpath("//*[@class='competitors-options-img']"), this);
			RefineCriteriaModal = new Element("Refine Criteria Modal", By.xpath("//*[@class='addpeer-showing']"), this);
			RefineCriteriaCloseButton = new Element("Refine Criteria Close Button", By.xpath("//*[@class='addpeer-showing-closeicon']"), this);
			SelectRegionAccordionCollapsed = new Element("Select Region Accordion (Collapsed)", By.xpath("//*[@class='panel-group']//*[@class='panel'][3]//*[@class='accordion-toggle']"), this);
			SelectRegionAccordionExpanded = new Element("Select Region Accordion (Expanded)", By.xpath("//*[@class='panel-group']//*[@class='panel panel-open']//*[@class='accordion-toggle']"), this);
			SelectRegionDropdown = new Element("Select Region Dropdown", By.xpath("//*[@class='panel-collapse collapse in show']//app-multipledropdown[1]//*[@class='btn-group']"), this);
			SelectCountryDropdown = new Element("Select Country Accordion", By.xpath("//*[@class='panel-collapse collapse in show']//app-multipledropdown[2]//*[@class='btn-group']"), this);
			SetRevenueAccordionCollapsed = new Element("Set Revenue Accordion (Collapsed)", By.xpath("//*[@class='panel-group']//*[@class='panel'][4]//*[@class='accordion-toggle']"), this);
			SetRevenueAccordionExpanded = new Element("Set Revenue Accordion (Expanded)", By.xpath("//*[@class='panel-group']//*[@class='panel panel-open']//*[@class='accordion-toggle']"), this);
//			RevenueMin = new TextBox("Min Revenue Textbox", By.xpath("//*[@class='panel-collapse collapse in show']//*[@class='input-cont'][1]//*[@class='input ng-untouched ng-pristine ng-valid']"), this);
//			RevenueMax = new TextBox("Max Revenue Textbox", By.xpath("//*[@class='panel-collapse collapse in show']//*[@class='input-cont'][2]//*[@class='input ng-untouched ng-pristine ng-valid']"), this);
//			MarketCapMin = new TextBox("Min Market Cap Textbox", By.xpath("//*[@class='panel-collapse collapse in show']//*[@class='input-cont'][3]//*[@class='input ng-untouched ng-pristine ng-valid']"), this);
//			MarketCapMax = new TextBox("Max Market Cap Textbox", By.xpath("//*[@class='panel-collapse collapse in show']//*[@class='input-cont'][4]//*[@class='input ng-untouched ng-pristine ng-valid']"), this);
			RevenueMin = new TextBox("Min Revenue Textbox", By.xpath("//*[@class='input-cont' or @class='input-cont ng-star-inserted'][1]//input"), this);
			RevenueMax = new TextBox("Max Revenue Textbox", By.xpath("//*[@class='input-cont' or @class='input-cont ng-star-inserted'][2]//input"), this);
			MarketCapMin = new TextBox("Min Market Cap Textbox", By.xpath("//*[@class='input-cont' or @class='input-cont ng-star-inserted'][3]//input"), this);
			MarketCapMax = new TextBox("Max Market Cap Textbox", By.xpath("//*[@class='input-cont' or @class='input-cont ng-star-inserted'][4]//input"), this);
			SaveCriteriaButton = new Element("Save Criteria Button", By.xpath("//*[@class='criteria-save-btn']"), this);
			NameCriteriaTextBox = new TextBox("Name Criteria TextBox", By.xpath("//*[@class='criteria-done-input-holder']/input"), this);
			NameCriteriaCloseButton = new Element("Name Criteria Close Button", By.xpath("//*[@class='criteria-done-input-clear']"), this);
			DoneCriteriaButton = new Element("Done Criteria Button", By.xpath("//*[@class='criteria-done-btn']"), this);
			PreSavedCriteriaAccordionCollapsed = new Element("Pre Saved Criteria Accordion (Collapsed)", By.xpath("//*[@class='panel-group']//*[@class='panel'][1]//*[@class='accordion-toggle']"), this);
			PreSavedCriteriaAccordionExpanded = new Element("Pre Saved Criteria Accordion (Expanded)", By.xpath("//*[@class='panel-group']//*[@class='panel panel-open']//*[@class='accordion-toggle']"), this);
			PreSavedCriteriaDropdown = new Element("Pre Saved Criteria Dropdown", By.xpath("//*[@class='panel-collapse collapse in show']//app-singledropdown//*[@class='btn btn-primary']"), this);
			PreSavedCriteriaDropdownMenu = new Element("Pre Saved Criteria Dropdown Menu", By.xpath("(//*[@role='menuitem'])[1]"), this);
			ApplyCriteriaButton = new Element("Apply Criteria Button", By.xpath("//*[@class='criteria-apply-btn']"), this);
			TopFilterDropdown = new Element("Top Filter Dropdown", By.xpath("//*[@class='topfilter ng-star-inserted']"), this);
			TopFilterChoice15 = new Element("Top Filter Choice", By.xpath("//*[@class='topfilterchoice ng-star-inserted']//*[@class='topfilterchoice-selections ng-star-inserted'][1]"), this);
			TopFilterChoice25 = new Element("Top Filter Choice", By.xpath("//*[@class='topfilterchoice ng-star-inserted']//*[@class='topfilterchoice-selections ng-star-inserted'][2]"), this);
			NewTargetCompAlias = new TextBox("Target Company Alias", By.xpath("//*[@class='competitors-peers-target']/input"), this);
			NewFirstPeerAlias = new TextBox("First Peer Alias", By.xpath("//*[@class='competitors-peers-item ng-star-inserted'][1]//input"), this);
//			TargetCompAlias2 = new TextBox("Target Company Alias", By.xpath("//*[@ng-reflect-model='" + TargetCompNameData2 + "']"), this);
//			FirstPeerAlias2 = new TextBox("First Peer Alias", By.xpath("//*[@ng-reflect-model='" + FirstPeerCompNameData2 + "']"), this);
			TargetCompAlias1 = new TextBox("Target Company Alias", By.xpath("//*[@ng-reflect-model='Unilever PLC']"), this);
			FirstPeerAlias1 = new TextBox("First Peer Alias", By.xpath("//*[@ng-reflect-model='Nestlé S.A.']"), this);
			TargetCompAlias2 = new TextBox("Target Company Alias", By.xpath("//*[@ng-reflect-model='123456789012345678']"), this);
			FirstPeerAlias2 = new TextBox("First Peer Alias", By.xpath("//*[@ng-reflect-model='123456789012345678']"), this);
			ReportSummaryPeer1 = new TextBox("Report Summary Peer 1", By.xpath("//*[@class='report-body-peer-content']//li[1]"), this);
			ReportSummaryPeer2 = new TextBox("Report Summary Peer 2", By.xpath("//*[@class='report-body-peer-content']//li[2]"), this);
			ReportSummaryPeer3 = new TextBox("Report Summary Peer 3", By.xpath("//*[@class='report-body-peer-content']//li[3]"), this);
			ReportSummaryPeer4 = new TextBox("Report Summary Peer 4", By.xpath("//*[@class='report-body-peer-content']//li[4]"), this);
			ReportSummaryPeer5 = new TextBox("Report Summary Peer 5", By.xpath("//*[@class='report-body-peer-content']//li[5]"), this);
			ReportSummaryPeer6 = new TextBox("Report Summary Peer 6", By.xpath("//*[@class='report-body-peer-content']//li[6]"), this);
			ReportSummaryPeer7 = new TextBox("Report Summary Peer 7", By.xpath("//*[@class='report-body-peer-content']//li[7]"), this);
			ReportSummaryPeer8 = new TextBox("Report Summary Peer 8", By.xpath("//*[@class='report-body-peer-content']//li[8]"), this);
			ReportSummaryPeer9 = new TextBox("Report Summary Peer 9", By.xpath("//*[@class='report-body-peer-content']//li[9]"), this);
			ReportSummaryPeer10 = new TextBox("Report Summary Peer 10", By.xpath("//*[@class='report-body-peer-content']//li[10]"), this);
			ReportSummaryPeer11 = new TextBox("Report Summary Peer 11", By.xpath("//*[@class='report-body-peer-content']//li[11]"), this);
			ReportSummaryPeer12 = new TextBox("Report Summary Peer 12", By.xpath("//*[@class='report-body-peer-content']//li[12]"), this);
			ReportSummaryPeer13 = new TextBox("Report Summary Peer 13", By.xpath("//*[@class='report-body-peer-content']//li[13]"), this);
			ReportSummaryPeer14 = new TextBox("Report Summary Peer 14", By.xpath("//*[@class='report-body-peer-content']//li[14]"), this);
			ReportSummaryPeer15 = new TextBox("Report Summary Peer 15", By.xpath("//*[@class='report-body-peer-content']//li[15]"), this);
			ReportSummaryDashboard1 = new TextBox("Report Summary Dashboard 1", By.xpath("//*[@class='report-body-dashboard-content']//li[1]"), this);
			ReportSummaryDashboard2 = new TextBox("Report Summary Dashboard 2", By.xpath("//*[@class='report-body-dashboard-content']//li[2]"), this);
			ReportSummaryDashboard3 = new TextBox("Report Summary Dashboard 3", By.xpath("//*[@class='report-body-dashboard-content']//li[3]"), this);
			ReportSummaryDashboard4 = new TextBox("Report Summary Dashboard 4", By.xpath("//*[@class='report-body-dashboard-content']//li[4]"), this);
			ReportSummaryDashboard5 = new TextBox("Report Summary Dashboard 5", By.xpath("//*[@class='report-body-dashboard-content']//li[5]"), this);
			ReportSummaryDashboard6 = new TextBox("Report Summary Dashboard 6", By.xpath("//*[@class='report-body-dashboard-content']//li[6]"), this);
			ReportSummaryDashboard7 = new TextBox("Report Summary Dashboard 7", By.xpath("//*[@class='report-body-dashboard-content']//li[7]"), this);
			ReportSummaryDashboard8 = new TextBox("Report Summary Dashboard 8", By.xpath("//*[@class='report-body-dashboard-content']//li[8]"), this);
			ReportSummaryDashboard9 = new TextBox("Report Summary Dashboard 9", By.xpath("//*[@class='report-body-dashboard-content']//li[9]"), this);
			ReportSummaryDashboard10 = new TextBox("Report Summary Dashboard 10", By.xpath("//*[@class='report-body-dashboard-content']//li[10]"), this);
			ReportSummaryDashboard11 = new TextBox("Report Summary Dashboard 11", By.xpath("//*[@class='report-body-dashboard-content']//li[11]"), this);
			ReportSummaryDashboard12 = new TextBox("Report Summary Dashboard 12", By.xpath("//*[@class='report-body-dashboard-content']//li[12]"), this);
			ReportSummaryDashboard13 = new TextBox("Report Summary Dashboard 13", By.xpath("//*[@class='report-body-dashboard-content']//li[13]"), this);
			ReportSummaryDashboard14 = new TextBox("Report Summary Dashboard 14", By.xpath("//*[@class='report-body-dashboard-content']//li[14]"), this);
			ReportSummaryDashboard15 = new TextBox("Report Summary Dashboard 15", By.xpath("//*[@class='report-body-dashboard-content']//li[15]"), this);
			ReportSummaryDashboard16 = new TextBox("Report Summary Dashboard 16", By.xpath("//*[@class='report-body-dashboard-content']//li[16]"), this);
			ReportSummaryDashboard17 = new TextBox("Report Summary Dashboard 17", By.xpath("//*[@class='report-body-dashboard-content']//li[17]"), this);
			Revenue1 = new TextBox("Competitors Revenue 1", By.xpath("(//*[@class='competitors-peers-item-rev'])[1]"), this);
			Revenue2 = new TextBox("Competitors Revenue 2", By.xpath("(//*[@class='competitors-peers-item-rev'])[2]"), this);
			Revenue3 = new TextBox("Competitors Revenue 3", By.xpath("(//*[@class='competitors-peers-item-rev'])[3]"), this);
			Revenue4 = new TextBox("Competitors Revenue 4", By.xpath("(//*[@class='competitors-peers-item-rev'])[4]"), this);
			Revenue5 = new TextBox("Competitors Revenue 5", By.xpath("(//*[@class='competitors-peers-item-rev'])[5]"), this);
			Revenue6 = new TextBox("Competitors Revenue 6", By.xpath("(//*[@class='competitors-peers-item-rev'])[6]"), this);
			Revenue7 = new TextBox("Competitors Revenue 7", By.xpath("(//*[@class='competitors-peers-item-rev'])[7]"), this);
			Revenue8 = new TextBox("Competitors Revenue 8", By.xpath("(//*[@class='competitors-peers-item-rev'])[8]"), this);
			Revenue9 = new TextBox("Competitors Revenue 9", By.xpath("(//*[@class='competitors-peers-item-rev'])[9]"), this);
			Revenue10 = new TextBox("Competitors Revenue 10", By.xpath("(//*[@class='competitors-peers-item-rev'])[10]"), this);
			Revenue11 = new TextBox("Competitors Revenue 11", By.xpath("(//*[@class='competitors-peers-item-rev'])[11]"), this);
			Revenue12 = new TextBox("Competitors Revenue 12", By.xpath("(//*[@class='competitors-peers-item-rev'])[12]"), this);
			Revenue13 = new TextBox("Competitors Revenue 13", By.xpath("(//*[@class='competitors-peers-item-rev'])[13]"), this);
			Revenue14 = new TextBox("Competitors Revenue 14", By.xpath("(//*[@class='competitors-peers-item-rev'])[14]"), this);
			Revenue15 = new TextBox("Competitors Revenue 15", By.xpath("(//*[@class='competitors-peers-item-rev'])[15]"), this);
			Revenue16 = new TextBox("Competitors Revenue 16", By.xpath("(//*[@class='competitors-peers-item-rev'])[16]"), this);
			Revenue17 = new TextBox("Competitors Revenue 17", By.xpath("(//*[@class='competitors-peers-item-rev'])[17]"), this);
			Revenue18 = new TextBox("Competitors Revenue 18", By.xpath("(//*[@class='competitors-peers-item-rev'])[18]"), this);
			Revenue19 = new TextBox("Competitors Revenue 19", By.xpath("(//*[@class='competitors-peers-item-rev'])[19]"), this);
			Revenue20 = new TextBox("Competitors Revenue 20", By.xpath("(//*[@class='competitors-peers-item-rev'])[20]"), this);
			Revenue21 = new TextBox("Competitors Revenue 21", By.xpath("(//*[@class='competitors-peers-item-rev'])[21]"), this);
			Revenue22 = new TextBox("Competitors Revenue 22", By.xpath("(//*[@class='competitors-peers-item-rev'])[22]"), this);
			Revenue23 = new TextBox("Competitors Revenue 23", By.xpath("(//*[@class='competitors-peers-item-rev'])[23]"), this);
			Revenue24 = new TextBox("Competitors Revenue 24", By.xpath("(//*[@class='competitors-peers-item-rev'])[24]"), this);
			Revenue25 = new TextBox("Competitors Revenue 25", By.xpath("(//*[@class='competitors-peers-item-rev'])[25]"), this);
			Symbol1 = new TextBox("Exchange symbol : Ticker symbol 1", By.xpath("(//*[@class='competitors-peers-item-br'])[1]"), this);
			Symbol2 = new TextBox("Exchange symbol : Ticker symbol 2", By.xpath("(//*[@class='competitors-peers-item-br'])[2]"), this);
			Symbol3 = new TextBox("Exchange symbol : Ticker symbol 3", By.xpath("(//*[@class='competitors-peers-item-br'])[3]"), this);
			Symbol4 = new TextBox("Exchange symbol : Ticker symbol 4", By.xpath("(//*[@class='competitors-peers-item-br'])[4]"), this);
			Symbol5 = new TextBox("Exchange symbol : Ticker symbol 5", By.xpath("(//*[@class='competitors-peers-item-br'])[5]"), this);
			Symbol6 = new TextBox("Exchange symbol : Ticker symbol 6", By.xpath("(//*[@class='competitors-peers-item-br'])[6]"), this);
			Symbol7 = new TextBox("Exchange symbol : Ticker symbol 7", By.xpath("(//*[@class='competitors-peers-item-br'])[7]"), this);
			Symbol8 = new TextBox("Exchange symbol : Ticker symbol 8", By.xpath("(//*[@class='competitors-peers-item-br'])[8]"), this);
			Symbol9 = new TextBox("Exchange symbol : Ticker symbol 9", By.xpath("(//*[@class='competitors-peers-item-br'])[9]"), this);
			Symbol10 = new TextBox("Exchange symbol : Ticker symbol 10", By.xpath("(//*[@class='competitors-peers-item-br'])[10]"), this);
			Symbol11 = new TextBox("Exchange symbol : Ticker symbol 11", By.xpath("(//*[@class='competitors-peers-item-br'])[11]"), this);
			Symbol12 = new TextBox("Exchange symbol : Ticker symbol 12", By.xpath("(//*[@class='competitors-peers-item-br'])[12]"), this);
			Symbol13 = new TextBox("Exchange symbol : Ticker symbol 13", By.xpath("(//*[@class='competitors-peers-item-br'])[13]"), this);
			Symbol14 = new TextBox("Exchange symbol : Ticker symbol 14", By.xpath("(//*[@class='competitors-peers-item-br'])[14]"), this);
			Symbol15 = new TextBox("Exchange symbol : Ticker symbol 15", By.xpath("(//*[@class='competitors-peers-item-br'])[15]"), this);
			CurratedNote = new Element("Currated List Note", By.xpath("//*[@class='competitors-subtitle ng-star-inserted']"), this);
			CurratedNoteHighlight = new Element("Currated List Note Highlight", By.xpath("//*[@class='competitors-subtitle-highlight']"), this);
			CompanyNameHeader = new Element("Company Name Header", By.xpath("//*[@class='competitors-peers-header']/div[1]"), this);
			IndustryLocationHeader = new Element("Industry Location Header", By.xpath("//*[@class='competitors-peers-header']/div[2]"), this);
			LatestFinancialsHeader = new Element("Latest Financials Header", By.xpath("//*[@class='competitors-peers-header']/div[3]"), this);
			RevenueHeader = new Element("Revenue Header", By.xpath("//*[@class='competitors-peers-header']/div[4]"), this);
			MarketCapHeader = new Element("Market Cap Header", By.xpath("//*[@class='competitors-peers-header']/div[5]"), this);
			AliasHeader = new Element("Alias Header", By.xpath("//*[@class='competitors-peers-header-alias']"), this);
			AliasIcon = new Element("Alias ? Icon", By.xpath("//*[@class='competitors-peers-header-img']"), this);
			TooltipText = new Element("Alias Tooltip Text", By.xpath("//*[@class='tooltip-text']"), this);
			TargetIndustry = new Element("Target Company Industry", By.xpath("//*[@class='competitors-peers-target-industryregion']"), this);
			PeerIndustry1 = new Element("Peer Company Industry 1", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[1]"), this);
			PeerIndustry2 = new Element("Peer Company Industry 2", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[2]"), this);
			PeerIndustry3 = new Element("Peer Company Industry 3", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[3]"), this);
			PeerIndustry4 = new Element("Peer Company Industry 4", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[4]"), this);
			PeerIndustry5 = new Element("Peer Company Industry 5", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[5]"), this);
			PeerIndustry6 = new Element("Peer Company Industry 6", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[6]"), this);
			PeerIndustry7 = new Element("Peer Company Industry 7", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[7]"), this);
			PeerIndustry8 = new Element("Peer Company Industry 8", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[8]"), this);
			PeerIndustry9 = new Element("Peer Company Industry 9", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[9]"), this);
			PeerIndustry10 = new Element("Peer Company Industry 10", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[10]"), this);
			PeerIndustry11 = new Element("Peer Company Industry 11", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[11]"), this);
			PeerIndustry12 = new Element("Peer Company Industry 12", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[12]"), this);
			PeerIndustry13 = new Element("Peer Company Industry 13", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[13]"), this);
			PeerIndustry14 = new Element("Peer Company Industry 14", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[14]"), this);
			PeerIndustry15 = new Element("Peer Company Industry 15", By.xpath("(//*[@class='competitors-peers-item-industryregion'])[15]"), this);
			TargetFinancials = new Element("Target Company Latest Financials", By.xpath("//*[@class='competitors-peers-target-financials']"), this);
			TargetRevenue = new Element("Target Company Revenue", By.xpath("//*[@class='competitors-peers-target-rev']"), this);
			TargetMarketCap = new Element("Target Company Market Cap", By.xpath("//*[@class='competitors-peers-target-marcap' or @class='competitors-peers-target-marcap ng-star-inserted']/span"), this);
			TargetAlias = new Element("Target Company Alias", By.xpath("//*[@class='competitors-peers-target']/input"), this);
			Peer1Financials = new Element("Peer 1 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[1]"), this);
			Peer2Financials = new Element("Peer 2 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[2]"), this);
			Peer3Financials = new Element("Peer 3 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[3]"), this);
			Peer4Financials = new Element("Peer 4 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[4]"), this);
			Peer5Financials = new Element("Peer 5 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[5]"), this);
			Peer6Financials = new Element("Peer 6 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[6]"), this);
			Peer7Financials = new Element("Peer 7 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[7]"), this);
			Peer8Financials = new Element("Peer 8 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[8]"), this);
			Peer9Financials = new Element("Peer 9 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[9]"), this);
			Peer10Financials = new Element("Peer 10 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[10]"), this);
			Peer11Financials = new Element("Peer 11 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[11]"), this);
			Peer12Financials = new Element("Peer 12 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[12]"), this);
			Peer13Financials = new Element("Peer 13 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[13]"), this);
			Peer14Financials = new Element("Peer 14 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[14]"), this);
			Peer15Financials = new Element("Peer 15 Company Latest Financials", By.xpath("(//*[@class='competitors-peers-item-financials'])[15]"), this);
			Peer1MarketCap = new Element("Peer 1 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[1]/span"), this);
			Peer2MarketCap = new Element("Peer 2 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[2]/span"), this);
			Peer3MarketCap = new Element("Peer 3 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[3]/span"), this);
			Peer4MarketCap = new Element("Peer 4 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[4]/span"), this);
			Peer5MarketCap = new Element("Peer 5 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[5]/span"), this);
			Peer6MarketCap = new Element("Peer 6 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[6]/span"), this);
			Peer7MarketCap = new Element("Peer 7 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[7]/span"), this);
			Peer8MarketCap = new Element("Peer 8 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[8]/span"), this);
			Peer9MarketCap = new Element("Peer 9 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[9]/span"), this);
			Peer10MarketCap = new Element("Peer 10 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[10]/span"), this);
			Peer11MarketCap = new Element("Peer 11 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[11]/span"), this);
			Peer12MarketCap = new Element("Peer 12 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[12]/span"), this);
			Peer13MarketCap = new Element("Peer 13 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[13]/span"), this);
			Peer14MarketCap = new Element("Peer 14 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[14]/span"), this);
			Peer15MarketCap = new Element("Peer 15 Company Market Cap", By.xpath("(//*[@class='competitors-peers-item-marcap'])[15]/span"), this);
			Peer1Alias = new Element("Peer 1 Company Alias", By.xpath("(//*[@class='competitors-peers-alias ng-untouched ng-pristine ng-valid'])[1]"), this);
			DisclaimerHeader = new Element("Disclaimer Header", By.xpath("//*[@class='competitors-disclaimer-header']"), this);
			Disclaimer1 = new Element("Disclaimer 1", By.xpath("(//*[@class='competitors-disclaimer-item ng-star-inserted'])[1]"), this);
			Disclaimer2 = new Element("Disclaimer 2", By.xpath("(//*[@class='competitors-disclaimer-item ng-star-inserted'])[2]"), this);
			Disclaimer3 = new Element("Disclaimer 3", By.xpath("(//*[@class='competitors-disclaimer-item ng-star-inserted'])[3]"), this);
			Disclaimer4 = new Element("Disclaimer 4", By.xpath("(//*[@class='competitors-disclaimer-item ng-star-inserted'])[4]"), this);
			Disclaimer5 = new Element("Disclaimer 5", By.xpath("(//*[@class='competitors-disclaimer-item ng-star-inserted'])[5]"), this);
			TargetCountry = new Element("Target Country", By.xpath("//*[@class='competitors-peers-target-br']"), this);
			PeerCountry1 = new Element("Peer 1 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[1]"), this);
			PeerCountry2 = new Element("Peer 2 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[2]"), this);
			PeerCountry3 = new Element("Peer 3 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[3]"), this);
			PeerCountry4 = new Element("Peer 4 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[4]"), this);
			PeerCountry5 = new Element("Peer 5 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[5]"), this);
			PeerCountry6 = new Element("Peer 6 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[6]"), this);
			PeerCountry7 = new Element("Peer 7 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[7]"), this);
			PeerCountry8 = new Element("Peer 8 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[8]"), this);
			PeerCountry9 = new Element("Peer 9 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[9]"), this);
			PeerCountry10 = new Element("Peer 10 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[10]"), this);
			PeerCountry11 = new Element("Peer 11 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[11]"), this);
			PeerCountry12 = new Element("Peer 12 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[12]"), this);
			PeerCountry13 = new Element("Peer 13 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[13]"), this);
			PeerCountry14 = new Element("Peer 14 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[14]"), this);
			PeerCountry15 = new Element("Peer 15 Country", By.xpath("(//*[@class='competitors-peers-item-industryregion'][1]//*[@class='competitors-peers-item-br'])[15]"), this);
			
		}
	}
	
	
	
}