package pageobjects;

import org.openqa.selenium.By;

import auto.framework.PageBase;
import auto.framework.web.Element;
import auto.framework.web.TextBox;

public class VIPLandingPage extends PageBase{
	
	public static final Contents contents = new Contents();
	
	public static class Contents extends Element{
		
		public final Element DowntimeModal;
		public final Element DowntimeModalCloseButton;
		public final Element WhatsNewModal;
		public final Element WhatsNewModalCloseButton;
		public final Element WhatsNewModal1;
		public final Element WhatsNewModalCloseButton1;
		public final Element StartNowButton;
		public final Element LandingPageLoadedCompletely;
		public final Element RequestAccessButton;
		public final Element StartNowButton1;
		public final Element StartNowButton2;
		public final Element ContactCVSTeamButton;
		public final Element ContactCVSTeamButton1;
		public final Element ContactCVSTeamButton2;
		public final Element HelpIcon;
		public final Element HelpText;
		public final Element HelpTooltip;
		public final Element HelpMenu;
		public final Element FAQHeader;
		public final Element FAQFooter;
		public final Element GiveUsFeedback;
		public final Element UserPhoto;
		public final Element UserEID;
		public final Element WhatIsVIP;
		public final Element MyLastReports;
		public final Element SavedCompaniesHeader;
		public final Element LatestNewsHeader;
		public final Element MyLastReports2;
		public final Element DisclaimerIcon;
		public final Element DisclaimerTooltip;
		public final Element OperatingLeaseAdjustmentIcon;
		public final Element OperatingLeaseAdjustmentTooltip;
		public final Element ClientFocusAccordion;
		public final Element ClientFocusAccordionTitle;
		public final Element ClientFocus1;
		public final Element ClientFocus2;
		public final Element ClientFocus3;
		public final Element ClientFocus1SS;
		public final Element ClientFocus2SS;
		public final Element ClientFocus3SS;
		public final Element ClientFocus1CS;
		public final Element ClientFocus2CS;
		public final Element ClientFocus3CS;
		public final Element AttributesAccordion;
		public final Element AttributesAccordionTitle;
		public final Element Attributes1;
		public final Element Attributes2;
		public final Element Attributes3;
		public final Element Attributes4;
		public final Element Attributes5;
		public final Element Attributes6;
		public final Element Attributes1SS;
		public final Element Attributes2SS;
		public final Element Attributes3SS;
		public final Element Attributes4SS;
		public final Element Attributes5SS;
		public final Element Attributes6SS;
		public final Element Attributes1CS;
		public final Element Attributes2CS;
		public final Element Attributes3CS;
		public final Element Attributes4CS;
		public final Element Attributes5CS;
		public final Element Attributes6CS;
		public final Element FinancialAnalysisAccordion;
		public final Element FinancialAnalysisAccordionTitle;
		public final Element FinancialAnalysisSubAccordion;
		public final Element FinancialAnalysis1;
		public final Element FinancialAnalysis2;
		public final Element FinancialAnalysis3;
		public final Element FinancialAnalysis4;
		public final Element FinancialAnalysis5;
		public final Element FinancialAnalysis1SS;
		public final Element FinancialAnalysis1CS;
		public final Element FinancialAnalysis2SS;
		public final Element FinancialAnalysis2CS;
		public final Element FinancialAnalysis4SS;
		public final Element FinancialAnalysis4CS;
		public final Element FinancialAnalysis5SS;
		public final Element FinancialAnalysis5CS;
		public final Element TechnicalFeaturesAccordion;
		public final Element TechnicalFeaturesAccordionTitle;
		public final Element TechnicalFeatures1;
		public final Element TechnicalFeatures2;
		public final Element TechnicalFeatures3;
		public final Element TechnicalFeatures1SS;
		public final Element TechnicalFeatures1CS;
		public final Element TechnicalFeatures2SS;
		public final Element TechnicalFeatures2CS;
		public final Element TechnicalFeatures3SS;
		public final Element TechnicalFeatures3CS;
		public final Element AccessibilityAccordion;
		public final Element AccessibilityAccordionTitle;
		public final Element AccessibilitySubAccordion;
		public final Element Accessibility1;
		public final Element Accessibility2;
		public final Element Accessibility3;
		public final Element Accessibility4;
		public final Element Accessibility5;
		public final Element AccessibilityMobileBrowser;
		public final Element AccessibilityQlikWorkbook;
		public final Element AccessibilityMobileApplication;
		public final Element Accessibility1SS;
		public final Element Accessibility1CS;
		public final Element Accessibility3SS;
		public final Element Accessibility3CS;
		public final Element Accessibility4SS;
		public final Element Accessibility4CS;
		public final Element Accessibility5SS;
		public final Element Accessibility5CS;
		public final Element DataSourceAccordion;
		public final Element DataSourceAccordionTitle;
		public final Element DataSource1;
		public final Element DataSource2;
		public final Element DataSource3;
		public final Element DataSource4;
		public final Element DataSource5;
		public final Element DataSource6;
		public final Element DataSource7;
		public final Element DataSource8;
		public final Element DataSource1C1;
		public final Element DataSource1C2;
		public final Element DataSource2C1;
		public final Element DataSource2C2;
		public final Element DataSource3C1;
		public final Element DataSource3C2;
		public final Element DataSource4C1;
		public final Element DataSource4C2;
		public final Element DataSource5C1;
		public final Element DataSource5C2;
		public final Element DataSource6C1;
		public final Element DataSource6C2;
		public final Element DataSource7C1;
		public final Element DataSource7C2;
		public final Element DataSource8C1;
		public final Element DataSource8C2;
		public final Element SupportAccordion;
		public final Element SupportAccordionTitle;
		public final Element Support1;
		public final Element Support2;
		public final Element Support1C1;
		public final Element Support1C2;
		public final Element Support2C1;
		public final Element Support2C2;
		public final Element ViewSampleText;
		public final Element SelfServiceTitle;
		public final Element SelfServiceSubTitle;
		public final Element SelfServiceBullet1;
		public final Element SelfServiceBullet2;
		public final Element SelfServiceBullet3;
		public final Element CustomTitle;
		public final Element CustomSubTitle;
		public final Element CustomBullet1;
		public final Element CustomBullet2;
		public final Element CustomBullet3;
		public final Element CVSContactsLabel;
		public final Element CVSContact1;
		public final Element CVSContact2;
		public final Element CVSContact3;
		public final Element CVSContact4;
		public final Element CVSContact5;
		public final Element CVSContact4Position;
		public final Element FACollapsedSection;
		public final Element FAExpandedSection;
		public final Element AttributesCollapsedSection;
		public final Element AttributesExpandedSection;
		public final Element NormalizationOfFinancialsSection;
		public final Element RestatementsIcon;
		public final Element RestatementsTooltip;
		public final Element AdjustedForFinanceDivisionIcon;
		public final Element AdjustedForFinanceDivisionTooltip;
		public final Element AccessibilityIcon;
		public final Element MyLastReportsTag;
		public final Element LatestNews;
		public final Element RefreshButtonTooltip;
		public final Element ShareButtonTooltip;
		public final Element ViewReportButton;
		public final Element ViewReportButtonTooltip;
		public final Element OverviewButtonTooltip;
		public final Element DownloadPPTButtonTooltip;
		public final Element SavedCompaniesEditIcon;
		public final TextBox SavedCompaniesSearchBox;
		public final Element AddButton;
		public final Element AddButton1;
		public final Element CompanyNameColumn;
		public final Element IndustryColumn;
		public final Element LocationColumn;
		public final Element DeleteButton;
		public final Element DeleteButton1;
		public final Element SavedCompEditIcon;
		public final Element FirstSavedComp;
		public final Element DisclaimerModal;
		public final Element NewDisclaimerModal;
		public final Element DisclaimerText;
		public final Element NewDisclaimerText;
		public final Element DontShowThisText;
		public final Element NewDontShowThisText;
		public final Element DontShowThisCheckbox;
		public final Element DisclaimerModalCloseButton;
		public final Element CompanyAnalysisTab;
		public final Element VCMTab;
		public final Element CompanyAnalysisTabTooltip;
		public final Element NewsEvent;
		public final Element DisclaimerProceedButton;
		public final TextBox CompanyNameTextbox;
		public final Element CompanyTypeAhead;
		public final Element CompanyTypeAhead1;
		public final Element CompanyTypeAhead2;
		public final Element SearchButton;
		public final Element SearchButton1;
		public final Element SearchButton2;
		public final Element CompanyCard1;
		public final Element CompanyCard2;
		public final Element CompanyCard3;
		public final Element CompanyCard4;
		public final Element CompanyCard5;
		public final Element CompanyCard39;
		public final Element CompanyCardType;
		public final Element CompanyCardTypeVCM;
		public final Element CompanyCardDate;
		public final Element CompanyCardName;
		public final Element CompanyCardName2;
		public final Element CompanyCardDate1;
		public final Element CompanyCardDate2;
		public final Element CompanyCardDate5;
		public final Element CompanyCardDate39;
		public final Element RefreshButton;
		public final Element DownloadPPTButton;
		public final Element ShareButton;
		public final Element ShareButton2;
		public final Element RefreshButton5;
		public final Element DownloadPPTButton5;
		public final Element ShareButton5;
		public final Element RefreshButton39;
		public final Element DownloadPPTButton39;
		public final Element ShareButton39;
		public final Element ReportsTotal;
		public final Element ReportsCurrent;
		public final Element RefreshCloseButton;
		public final Element OverviewButton;
		public final Element OverviewButton2;
		public final Element OverviewButton15;
		public final Element RefreshModalHeader;
		public final Element RefreshModalCompany;
		public final Element RefreshModalDate;
		public final Element RefreshModalDateValue;
		public final Element RefreshModalClose;
		public final Element ShareModalHeader;
		public final Element ShareModalCompany;
		public final Element ShareModalDate;
		public final Element ShareModalDateValue;
		public final TextBox ShareModalEmail;
		public final Element ShareModalShareButton;
		public final Element ShareModalCancelButton;
		public final Element ShareModalClose;
		public final Element OldWebsiteButton;
		public final Element Copyright1;
		public final Element Copyright2;
		public final Element Copyright3;
		public final Element DownloadUserGuideHeader;
		public final Element DownloadUserGuideFooter;
		public final Element NewDisclaimerProceedButton;
		public final Element NewQVWarningCloseButton;
		public final Element SideMenu;
		public final Element NewVCMModal;
		public final Element NewQVWarningText;
		public final Element EmailUsHeader;
		public final Element SSDashboardsCount;
		public final Element CSDashboardsCount;
		public final Element OperationalKPIs;
		public final Element SSOperationalKPIs;
		public final Element CSOperationalKPIs;
		public final Element NewsList;
		public final Element NewsListCompanyName;
		public final Element NextButton;
		public final Element PrevButton;
		public final Element HelpFAQ;
		public final Element HelpES;
		public final Element HelpDUG;
		public final Element HelpEU;
		public final Element HelpES1;
		public final Element HelpES2;
		public final Element HelpES3;
		public final Element HelpES4;
		public final Element FooterAU;
		public final Element FooterFAQ;
		public final Element FooterCU;
		public final Element FooterDUG;
		public final Element SavedCompContainer;
		
		public Contents() {
			super("Container", By.className("mainContainer"));
			
			DowntimeModal = new Element("Downtime Modal", By.xpath("//*[@id='customModalDowntime']"), this);
			DowntimeModalCloseButton = new Element("Downtime Modal Close Button", By.xpath("//*[@class='close-xbtn add-cls']"), this);
			WhatsNewModal = new Element("What's New Modal", By.xpath("//*[@id='customModalWhatsNewV3']"), this);
			WhatsNewModalCloseButton = new Element("What's New Modal Close Button", By.xpath("//*[@id='customModalWhatsNewV3']//*[@class='close-xbtn add-cls']"), this);
			WhatsNewModal1 = new Element("What's New Modal V1", By.xpath("//*[@id='customModalWhatsNewV2']"), this);
			WhatsNewModalCloseButton1 = new Element("What's New Modal Close Button V1", By.xpath("//*[@id='customModalWhatsNewV2']//*[@class='close-xbtn add-cls']"), this);
			//StartNowButton = new Element("Start Now Button", By.xpath("//*[@class='info-right-content']//button[normalize-space(text())='Start Now']"), this);
			StartNowButton = new Element("Start Now Button", By.xpath("//button[normalize-space(text())='Start Now']"), this);
			LandingPageLoadedCompletely = new Element("Landing Page Loaded Completely", By.xpath("//*[@class='savedcomp-container']//*[@class='content-wrapper'][1]"), this);
			RequestAccessButton = new Element("Request Access Button", By.xpath("//*[@class='info-right-content']//button[normalize-space(text())='Request Access']"), this);
			StartNowButton1 = new Element("Start Now Button", By.xpath("//*[@class='info-right-request btn']"), this);
			StartNowButton2 = new Element("Start Now Button", By.xpath("//*[@class='info-right-request btn ng-star-inserted']"), this);
			ContactCVSTeamButton = new Element("Contact CVS Team Button", By.xpath("//*[@class='info-right-content info-right-border']/a/div[1]"), this);
			ContactCVSTeamButton1 = new Element("Contact CVS Team Button", By.xpath("//*[@class='info-right-contact']"), this);
			ContactCVSTeamButton2 = new Element("Contact CVS Team Button", By.xpath("//*[@class='info-right-contact ng-star-inserted']"), this);
			HelpIcon = new Element("Help Icon", By.xpath("//*[@id='helpimage']"), this);
			HelpText = new Element("Help Text", By.xpath("//*[@id='helptext']"), this);
			HelpTooltip = new Element("Help Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			HelpMenu = new Element("Help Menu", By.xpath("//*[@id='helpComponent']"), this);
			FAQHeader = new Element("FAQ Header", By.xpath("//*[@id='helpComponent']/a/div"), this);
			FAQFooter = new Element("FAQ Footer", By.xpath("//*[@class='footer-container']/div[3]//a[1]/*[@class='footer-item-link onhover']"), this);
			GiveUsFeedback = new Element("Give Us Feedback Button", By.xpath("//*[@class='footer-feedback-button-content onhover']"), this);
			UserPhoto = new Element("User Photo", By.xpath("//*[@class='header-user-img']"), this);
			UserEID = new Element("User EID", By.xpath("//*[@class='header-user-eid']"), this);
			WhatIsVIP = new Element("What Is VIP Description", By.xpath("//*[@class='info-left-sub']"), this);
			MyLastReports = new Element("My Last Reports Header", By.xpath("//*[@class='reports-header']"), this);
			SavedCompaniesHeader = new Element("Saved Companies Header", By.xpath("//*[@class='savedcomp-title']"), this);
			LatestNewsHeader = new Element("Latest News Header", By.xpath("//*[@class='news-header']"), this);
			MyLastReports2 = new Element("My Last Reports Header", By.xpath("//*[@class='reports-header ng-star-inserted']"), this);
			DisclaimerIcon = new Element("Disclaimer Icon", By.xpath("//*[@class='info-selfservice-img']"), this);
			DisclaimerTooltip = new Element("Disclaimer Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			SelfServiceTitle = new Element("Self Service Title", By.xpath("(//*[@class='info-right-head'])[1]/div"), this);
			SelfServiceSubTitle = new Element("Self Service Sub-Title", By.xpath("(//*[@class='info-right-sub'])[1]"), this);
			SelfServiceBullet1 = new Element("Self Service Bullet 1", By.xpath("(//*[@class='info-right-list info-right-list-left']//*[@class='info-list-text'])[1]"), this);
			SelfServiceBullet2 = new Element("Self Service Bullet 2", By.xpath("(//*[@class='info-right-list info-right-list-left']//*[@class='info-list-text'])[2]"), this);
			SelfServiceBullet3 = new Element("Self Service Bullet 3", By.xpath("(//*[@class='info-right-list info-right-list-left']//*[@class='info-list-text'])[3]"), this);
			CustomTitle = new Element("Custom Title", By.xpath("(//*[@class='info-right-head'])[2]/div"), this);
			CustomSubTitle = new Element("Custom Sub-Title", By.xpath("(//*[@class='info-right-sub'])[2]"), this);
			CustomBullet1 = new Element("Custom Bullet 1", By.xpath("(//*[@class='info-right-list info-right-list-right']//*[@class='info-list-text'])[1]"), this);
			CustomBullet2 = new Element("Custom Bullet 2", By.xpath("(//*[@class='info-right-list info-right-list-right']//*[@class='info-list-text'])[2]"), this);
			CustomBullet3 = new Element("Custom Bullet 3", By.xpath("(//*[@class='info-right-list info-right-list-right']//*[@class='info-list-text'])[3]"), this);
			CVSContactsLabel = new Element("CVS Contacts Label", By.xpath("//*[@class='experts-header']"), this);
			CVSContact1 = new Element("CVS Contact 1", By.xpath("//*[@class='experts-list']/div[1]//*[@class='experts-item-name']"), this);
			CVSContact2 = new Element("CVS Contact 2", By.xpath("//*[@class='experts-list']/div[2]//*[@class='experts-item-name']"), this);
			CVSContact3 = new Element("CVS Contact 3", By.xpath("//*[@class='experts-list']/div[3]//*[@class='experts-item-name']"), this);
			CVSContact4 = new Element("CVS Contact 4", By.xpath("//*[@class='experts-list']/div[4]//*[@class='experts-item-name']"), this);
			CVSContact5 = new Element("CVS Contact 5", By.xpath("//*[@class='experts-list']/div[5]//*[@class='experts-item-name']"), this);
			CVSContact4Position = new Element("CVS Contact 4 Position", By.xpath("//*[@class='experts-list']/div[4]//*[@class='experts-item-position']"), this);
			OperatingLeaseAdjustmentIcon = new Element("Operating Lease Adjustment Icon", By.xpath("//*[@class='panel-body card-block card-body']//*[@class='financialanalysis']/div[1]/div[1]/i"), this);
			OperatingLeaseAdjustmentTooltip = new Element("Operating Lease Adjustment Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			ClientFocusAccordion = new Element("Client Focus Accordion", By.xpath("(//*[@class='accordion-toggle'])[1]"), this);
			ClientFocusAccordionTitle = new Element("Client Focus Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[1]//*[@class='features-item-text']"), this);
			ClientFocus1 = new Element("Client Focus Row 1", By.xpath("(//*[@class='clientfocus-row'])[1]//*[@class='clientfocus-col-description']"), this);
			ClientFocus2 = new Element("Client Focus Row 2", By.xpath("(//*[@class='clientfocus-row'])[2]//*[@class='clientfocus-col-description']"), this);
			ClientFocus3 = new Element("Client Focus Row 3", By.xpath("(//*[@class='clientfocus-row'])[3]//*[@class='clientfocus-col-description']"), this);
			ClientFocus1SS = new Element("Client Focus Row 1 Self Service - Check", By.xpath("(//*[@class='clientfocus-row'])[1]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			ClientFocus2SS = new Element("Client Focus Row 2 Self Service - Cross", By.xpath("(//*[@class='clientfocus-row'])[2]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			ClientFocus3SS = new Element("Client Focus Row 3 Self Service - Cross", By.xpath("(//*[@class='clientfocus-row'])[3]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			ClientFocus1CS = new Element("Client Focus Row 1 Custom - Check", By.xpath("(//*[@class='clientfocus-row'])[1]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			ClientFocus2CS = new Element("Client Focus Row 2 Custom - Check", By.xpath("(//*[@class='clientfocus-row'])[2]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			ClientFocus3CS = new Element("Client Focus Row 3 Custom - Check", By.xpath("(//*[@class='clientfocus-row'])[3]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			AttributesAccordion = new Element("Attributes Accordion", By.xpath("(//*[@class='accordion-toggle'])[2]"), this);
			AttributesAccordionTitle = new Element("Attributes Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[2]//*[@class='features-item-text']"), this);
			Attributes1 = new Element("Attributes Row 1", By.xpath("(//*[@class='attributes-row'])[1]//*[@class='attributes-col-description']"), this);
			Attributes2 = new Element("Attributes Row 2", By.xpath("(//*[@class='attributes-row'])[2]//*[@class='attributes-col-description']"), this);
			Attributes3 = new Element("Attributes Row 3", By.xpath("(//*[@class='attributes-row'])[3]//*[@class='attributes-col-description']"), this);
			Attributes4 = new Element("Attributes Row 4", By.xpath("(//*[@class='attributes-row'])[4]//*[@class='attributes-col-description']"), this);
			Attributes5 = new Element("Attributes Row 5", By.xpath("(//*[@class='attributes-row'])[5]//*[@class='attributes-col-description']"), this);
			Attributes6 = new Element("Attributes Row 6", By.xpath("(//*[@class='attributes-row'])[6]//*[@class='attributes-col-description']"), this);
			Attributes1SS = new Element("Attributes Row 1 Self Service", By.xpath("(//*[@class='attributes-row'])[1]//*[@class='attributes-col-value'][1]"), this);
			Attributes2SS = new Element("Attributes Row 2 Self Service", By.xpath("(//*[@class='attributes-row'])[2]//*[@class='attributes-col-value'][1]"), this);
			Attributes3SS = new Element("Attributes Row 3 Self Service", By.xpath("(//*[@class='attributes-row'])[3]//*[@class='attributes-col-value'][1]"), this);
			Attributes4SS = new Element("Attributes Row 4 Self Service - Check", By.xpath("(//*[@class='attributes-row'])[4]//*[@class='attributes-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Attributes5SS = new Element("Attributes Row 5 Self Service - Cross", By.xpath("(//*[@class='attributes-row'])[5]//*[@class='attributes-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			Attributes6SS = new Element("Attributes Row 6 Self Service", By.xpath("(//*[@class='attributes-row'])[6]//*[@class='attributes-col-value'][1]"), this);
			Attributes1CS = new Element("Attributes Row 1 Custom", By.xpath("(//*[@class='attributes-row'])[1]//*[@class='attributes-col-value'][2]"), this);
			Attributes2CS = new Element("Attributes Row 2 Custom", By.xpath("(//*[@class='attributes-row'])[2]//*[@class='attributes-col-value'][2]"), this);
			Attributes3CS = new Element("Attributes Row 3 Custom", By.xpath("(//*[@class='attributes-row'])[3]//*[@class='attributes-col-value'][2]"), this);
			Attributes4CS = new Element("Attributes Row 4 Custom - Check", By.xpath("(//*[@class='attributes-row'])[4]//*[@class='attributes-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Attributes5CS = new Element("Attributes Row 5 Custom - Check", By.xpath("(//*[@class='attributes-row'])[5]//*[@class='attributes-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Attributes6CS = new Element("Attributes Row 6 Custom", By.xpath("(//*[@class='attributes-row'])[6]//*[@class='attributes-col-value'][2]"), this);
			FinancialAnalysisAccordion = new Element("Financial Analysis Accordion", By.xpath("(//*[@class='accordion-toggle'])[3]"), this);
			FinancialAnalysisAccordionTitle = new Element("Financial Analysis Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[3]//*[@class='features-item-text']"), this);
			FinancialAnalysisSubAccordion = new Element("Financial Analysis Sub-Accordion", By.xpath("(//*[@class='accordion-toggle'])[4]"), this);
			FinancialAnalysis1 = new Element("Financial Analysis Row 1", By.xpath("(//*[@class='financialanalysis-row'])[1]//*[@class='financialanalysis-col-description']"), this);
			FinancialAnalysis2 = new Element("Financial Analysis Row 2", By.xpath("(//*[@class='financialanalysis-row'])[2]//*[@class='financialanalysis-col-description']"), this);
			FinancialAnalysis3 = new Element("Financial Analysis Row 3", By.xpath("(//*[@class='financialanalysis-row'])[3]//*[@class='financialanalysis-col-description']"), this);
			FinancialAnalysis4 = new Element("Financial Analysis Row 4", By.xpath("(//*[@class='financialanalysis-row'])[4]//*[@class='financialanalysis-col-description-sub']"), this);
			FinancialAnalysis5 = new Element("Financial Analysis Row 5", By.xpath("(//*[@class='financialanalysis-row'])[5]//*[@class='financialanalysis-col-description-sub']"), this);
			FinancialAnalysis1SS = new Element("Financial Analysis Row 1 Self Service", By.xpath("(//*[@class='financialanalysis-row'])[1]//*[@class='financialanalysis-col-value'][1]"), this);
			FinancialAnalysis1CS = new Element("Financial Analysis Row 1 Custom", By.xpath("(//*[@class='financialanalysis-row'])[1]//*[@class='financialanalysis-col-value'][2]"), this);
			FinancialAnalysis2SS = new Element("Financial Analysis Row 2 Self Service", By.xpath("(//*[@class='financialanalysis-row'])[2]//*[@class='financialanalysis-col-value'][1]"), this);
			FinancialAnalysis2CS = new Element("Financial Analysis Row 2 Custom", By.xpath("(//*[@class='financialanalysis-row'])[2]//*[@class='financialanalysis-col-value'][2]"), this);
			FinancialAnalysis4SS = new Element("Financial Analysis Row 4 Self Service - Cross", By.xpath("(//*[@class='financialanalysis-row'])[4]//*[@class='financialanalysis-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			FinancialAnalysis4CS = new Element("Financial Analysis Row 4 Custom - Check", By.xpath("(//*[@class='financialanalysis-row'])[4]//*[@class='financialanalysis-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			FinancialAnalysis5SS = new Element("Financial Analysis Row 5 Self Service - Cross", By.xpath("(//*[@class='financialanalysis-row'])[5]//*[@class='financialanalysis-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			FinancialAnalysis5CS = new Element("Financial Analysis Row 5 Custom - Check", By.xpath("(//*[@class='financialanalysis-row'])[5]//*[@class='financialanalysis-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			TechnicalFeaturesAccordion = new Element("Technical Features Accordion", By.xpath("(//*[@class='accordion-toggle'])[5]"), this);
			TechnicalFeaturesAccordionTitle = new Element("Technical Features Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[5]//*[@class='features-item-text']"), this);
			TechnicalFeatures1 = new Element("Technical Features Row 1", By.xpath("(//*[@class='technicalfeatures-row'])[1]//*[@class='technicalfeatures-col-description']"), this);
			TechnicalFeatures2 = new Element("Technical Features Row 1", By.xpath("(//*[@class='technicalfeatures-row'])[2]//*[@class='technicalfeatures-col-description']"), this);
			TechnicalFeatures3 = new Element("Technical Features Row 1", By.xpath("(//*[@class='technicalfeatures-row'])[3]//*[@class='technicalfeatures-col-description']"), this);
			TechnicalFeatures1SS = new Element("Technical Features Row 1 Self Service - Check", By.xpath("(//*[@class='technicalfeatures-row'])[1]//*[@class='technicalfeatures-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			TechnicalFeatures1CS = new Element("Technical Features Row 1 Custom - Check", By.xpath("(//*[@class='technicalfeatures-row'])[1]//*[@class='technicalfeatures-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			TechnicalFeatures2SS = new Element("Technical Features Row 2 Self Service - Check", By.xpath("(//*[@class='technicalfeatures-row'])[2]//*[@class='technicalfeatures-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			TechnicalFeatures2CS = new Element("Technical Features Row 2 Custom - Check", By.xpath("(//*[@class='technicalfeatures-row'])[2]//*[@class='technicalfeatures-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			TechnicalFeatures3SS = new Element("Technical Features Row 3 Self Service - Check", By.xpath("(//*[@class='technicalfeatures-row'])[3]//*[@class='technicalfeatures-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			TechnicalFeatures3CS = new Element("Technical Features Row 3 Custom - Check", By.xpath("(//*[@class='technicalfeatures-row'])[3]//*[@class='technicalfeatures-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			AccessibilityAccordion = new Element("Accessibility Accordion", By.xpath("(//*[@class='accordion-toggle'])[6]"), this);
			AccessibilityAccordionTitle = new Element("Accessibility Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[6]//*[@class='features-item-text']"), this);
			AccessibilitySubAccordion = new Element("Accessibility Sub-Accordion", By.xpath("(//*[@class='accordion-toggle'])[7]"), this);
			Accessibility1 = new Element("Accessibility Row 1", By.xpath("(//*[@class='accessibility-row'])[1]//*[@class='accessibility-col-description']"), this);
			Accessibility2 = new Element("Accessibility Row 2", By.xpath("(//*[@class='accessibility-row'])[2]//*[@class='accessibility-col-description']"), this);
			Accessibility3 = new Element("Accessibility Row 3", By.xpath("(//*[@class='accessibility-row'])[3]//*[@class='accessibility-col-description-sub']"), this);
			Accessibility4 = new Element("Accessibility Row 4", By.xpath("(//*[@class='accessibility-row'])[4]//*[@class='accessibility-col-description-sub']"), this);
			Accessibility5 = new Element("Accessibility Row 5", By.xpath("(//*[@class='accessibility-row'])[5]//*[@class='accessibility-col-description-sub']"), this);
			AccessibilityMobileBrowser = new Element("Accessibility Row - Mobile Browser", By.xpath("//*[@class='accessibility-row']//*[normalize-space(text())='Mobile Browser']"), this);
			AccessibilityQlikWorkbook = new Element("Accessibility Row - Qlik Workbook", By.xpath("//*[@class='accessibility-row']//*[normalize-space(text())='Qlik Workbook']"), this);
			AccessibilityMobileApplication = new Element("Accessibility Row - Mobile Application", By.xpath("//*[@class='accessibility-row']//*[normalize-space(text())='Mobile Application']"), this);
			Accessibility1SS = new Element("Accessibility Row 1 Self Service - Check", By.xpath("(//*[@class='accessibility-row'])[1]//*[@class='accessibility-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility1CS = new Element("Accessibility Row 1 Custom - Check", By.xpath("(//*[@class='accessibility-row'])[1]//*[@class='accessibility-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility3SS = new Element("Accessibility Row 3 Self Service - Check", By.xpath("(//*[@class='accessibility-row'])[3]//*[@class='accessibility-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility3CS = new Element("Accessibility Row 3 Custom - Check", By.xpath("(//*[@class='accessibility-row'])[3]//*[@class='accessibility-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility4SS = new Element("Accessibility Row 4 Self Service - Check", By.xpath("(//*[@class='accessibility-row'])[4]//*[@class='accessibility-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility4CS = new Element("Accessibility Row 4 Custom - Check", By.xpath("(//*[@class='accessibility-row'])[4]//*[@class='accessibility-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility5SS = new Element("Accessibility Row 5 Self Service - Check", By.xpath("(//*[@class='accessibility-row'])[5]//*[@class='accessibility-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Accessibility5CS = new Element("Accessibility Row 5 Custom - Check", By.xpath("(//*[@class='accessibility-row'])[5]//*[@class='accessibility-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSourceAccordion = new Element("Data Source Accordion", By.xpath("(//*[@class='accordion-toggle'])[8]"), this);
			DataSourceAccordionTitle = new Element("Data Source Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[8]//*[@class='features-item-txt-main']"), this);
			DataSource1 = new Element("Data Source Row 1", By.xpath("(//*[@class='clientfocus-row'])[4]//*[@class='clientfocus-col-description']"), this);
			DataSource2 = new Element("Data Source Row 2", By.xpath("(//*[@class='clientfocus-row'])[5]//*[@class='clientfocus-col-description']"), this);
			DataSource3 = new Element("Data Source Row 3", By.xpath("(//*[@class='clientfocus-row'])[6]//*[@class='clientfocus-col-description']"), this);
			DataSource4 = new Element("Data Source Row 4", By.xpath("(//*[@class='clientfocus-row'])[7]//*[@class='clientfocus-col-description']"), this);
			DataSource5 = new Element("Data Source Row 5", By.xpath("(//*[@class='clientfocus-row'])[8]//*[@class='clientfocus-col-description']"), this);
			DataSource6 = new Element("Data Source Row 6", By.xpath("(//*[@class='clientfocus-row'])[9]//*[@class='clientfocus-col-description']"), this);
			DataSource7 = new Element("Data Source Row 7", By.xpath("(//*[@class='clientfocus-row'])[10]//*[@class='clientfocus-col-description']"), this);
			DataSource8 = new Element("Data Source Row 8", By.xpath("(//*[@class='clientfocus-row'])[11]//*[@class='clientfocus-col-description']"), this);
			DataSource1C1 = new Element("Data Source Row 1 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[4]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource1C2 = new Element("Data Source Row 1 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[4]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource2C1 = new Element("Data Source Row 2 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[5]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource2C2 = new Element("Data Source Row 2 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[5]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource3C1 = new Element("Data Source Row 3 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[6]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			DataSource3C2 = new Element("Data Source Row 3 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[6]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource4C1 = new Element("Data Source Row 4 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[7]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			DataSource4C2 = new Element("Data Source Row 4 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[7]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource5C1 = new Element("Data Source Row 5 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[8]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			DataSource5C2 = new Element("Data Source Row 5 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[8]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource6C1 = new Element("Data Source Row 6 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[9]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-times-circle fa-w-16 redicon']"), this);
			DataSource6C2 = new Element("Data Source Row 6 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[9]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource7C1 = new Element("Data Source Row 7 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[10]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource7C2 = new Element("Data Source Row 7 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[10]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource8C1 = new Element("Data Source Row 8 S&P Capital IQ and Factiva", By.xpath("(//*[@class='clientfocus-row'])[11]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			DataSource8C2 = new Element("Data Source Row 8 Aggregated from multiple sources", By.xpath("(//*[@class='clientfocus-row'])[11]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			SupportAccordion = new Element("Support Accordion", By.xpath("(//*[@class='accordion-toggle'])[9]"), this);
			SupportAccordionTitle = new Element("Support Accordion Title", By.xpath("(//*[@class='accordion-toggle'])[9]//*[@class='features-item-text']"), this);
			Support1 = new Element("Support Row 1", By.xpath("(//*[@class='clientfocus-row'])[13]//*[@class='clientfocus-col-description']"), this);
			Support2 = new Element("Support Row 2", By.xpath("(//*[@class='clientfocus-row'])[14]//*[@class='clientfocus-col-description']"), this);
			Support1C1 = new Element("Support Row 1 Column 1", By.xpath("(//*[@class='clientfocus-row'])[13]//*[@class='clientfocus-col-value'][1]"), this);
			Support1C2 = new Element("Support Row 1 Column 2", By.xpath("(//*[@class='clientfocus-row'])[13]//*[@class='clientfocus-col-value'][2]"), this);
			Support2C1 = new Element("Support Row 2 Column 1", By.xpath("(//*[@class='clientfocus-row'])[14]//*[@class='clientfocus-col-value'][1]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			Support2C2 = new Element("Support Row 2 Column 2", By.xpath("(//*[@class='clientfocus-row'])[14]//*[@class='clientfocus-col-value'][2]//*[@class='svg-inline--fa fa-check-circle fa-w-16']"), this);
			ViewSampleText = new Element("View Sample Custom Service Text", By.xpath("(//*[@class='clientfocus-sample'])[1]//*[@class='clientfocus-col-value'][2]/div"), this);
			FACollapsedSection = new Element("Financial Analysis Section", By.xpath("//*[@class='panel'][3]/div[1]/div[1]/div[1]/div"), this);
			FAExpandedSection = new Element("Financial Analysis Section", By.xpath("//*[@class='panel panel-open']//*[@class='panel card customClass']/div[1]/div[1]/div[1]"), this);
			AttributesCollapsedSection = new Element("Attributes Section", By.xpath("//*[@class='panel'][2]/div[1]/div[1]/div[1]/div"), this);
			AttributesExpandedSection = new Element("Attributes Analysis Section", By.xpath("//*[@class='panel panel-open']//*[@class='panel card customClass']/div[1]/div[1]/div[1]"), this);
			NormalizationOfFinancialsSection = new Element("Normalization Of Financials Section", By.xpath("//*[@class='panel panel-open']//*[@class='financialanalysis']//*[@class='accordion-toggle']"), this);
			RestatementsIcon = new Element("Restatements Icon", By.xpath("(//*[@class='financialanalysis-row'])[4]//*[@class='svg-inline--fa fa-info-circle fa-w-16']"), this);
			RestatementsTooltip = new Element("Restatements Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			AdjustedForFinanceDivisionIcon = new Element("Adjusted for Finance Division Icon", By.xpath("(//*[@class='financialanalysis-row'])[5]//*[@class='svg-inline--fa fa-info-circle fa-w-16']"), this);
			AdjustedForFinanceDivisionTooltip = new Element("Adjusted for Finance Division Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			AccessibilityIcon = new Element("Accessibility Icon", By.xpath("(//*[@class='features-item-text'])[5]//*[@class='fas fa-info-circle']"), this);
			MyLastReportsTag = new Element("My Last Reports Tag", By.xpath("//*[@class='reports-subheader']"), this);
			LatestNews = new Element("Latest News", By.xpath("//*[@class='news']"), this);
			RefreshButtonTooltip = new Element("Refresh Button Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			ShareButtonTooltip = new Element("Share Button Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			ViewReportButton = new Element("View Report Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-link-download']"), this);
			ViewReportButtonTooltip = new Element("View Report Button Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			OverviewButtonTooltip = new Element("Overview Button Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			DownloadPPTButtonTooltip = new Element("Download PPT Button Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			SavedCompaniesEditIcon = new Element("Saved Companies Edit Icon", By.xpath("//*[@class='savedcomp-options']"), this);
			SavedCompaniesSearchBox = new TextBox("Saved Companies Search Box", By.xpath("//*[@class='tool-fwrapper' or @class='tool-fwrapper ng-star-inserted']//*[@type='text']"), this);
			AddButton = new Element("Saved Companies Add Button", By.xpath("//*[@class='tool-fbtn ng-star-inserted tool-fbtn-factive' or @class='tool-fbtn tool-fbtn-factive']"), this);
			AddButton1 = new Element("Saved Companies Add Button", By.xpath("//*[@class='tool-fbtn tool-fbtn-factive']"), this);
			CompanyNameColumn = new Element("Company Name Column", By.xpath("//*[@class='savedcomp-body-header-col-comp']"), this);
			IndustryColumn = new Element("Industry Column", By.xpath("//*[@class='savedcomp-body-header-col-ind']"), this);
			LocationColumn = new Element("Location Column", By.xpath("//*[@class='savedcomp-body-header-col-loc']"), this);
			//DeleteButton = new Element("Delete Button", By.xpath("//*[@class='content-wrapper']/div[1]/div[5]"), this);
			DeleteButton = new Element("Delete Button", By.xpath("//*[@class='savedcomp-body-cont-col-delete ng-star-inserted' or @class='savedcomp-body-cont-col-delete'][1]/img"), this);
			DeleteButton1 = new Element("Delete Button", By.xpath("//*[@class='savedcomp-body-cont-col-delete'][1]/img"), this);
			SavedCompEditIcon = new Element("Saved Companies Edit Icon", By.xpath("//*[@class='savedcomp-options']"), this);
			FirstSavedComp = new Element("First Saved Company", By.xpath("//*[@class='content-wrapper'][1]/div[1]//*[@class='savedcomp-body-cont-col-comp-name']"), this);
			DisclaimerModal = new Element("Client Value Services Disclaimer", By.xpath("//*[@class='modal-content modal-content-startnow']"), this);
			NewDisclaimerModal = new Element("New Client Value Services Disclaimer", By.xpath("//*[@id='customModalDisclaimer'][1]//*[@class='modal-body']"), this);
			DisclaimerText = new Element("Client Value Services Disclaimer Text", By.xpath("//*[@class='modal-content modal-content-startnow']/div[2]/div[1]"), this);
			NewDisclaimerText = new Element("New Client Value Services Disclaimer Text", By.xpath("//*[@id='customModalDisclaimer'][1]//*[@class='modal-title-subtitle']"), this);
			DontShowThisCheckbox = new Element("Don't Show This Message Checkbox", By.xpath("//*[@class='textbody-start-checkbox']"), this);
			DontShowThisText = new Element("Don't Show This Message Text", By.xpath("//*[@class='modal-content modal-content-startnow']/div[2]/div[2]/span"), this);
			NewDontShowThisText = new Element("New Don't Show This Message Text", By.xpath("//*[@class='modal-content']//*[@class='checkbox-text']"), this);
			DisclaimerModalCloseButton = new Element("Disclaimer Modal Close Button", By.xpath("//*[@class='modal-content modal-content-startnow']//*[@class='close']"), this);
			DisclaimerProceedButton = new Element("Disclaimer Proceed Button", By.xpath("//*[@class='modal-content modal-content-startnow']//*[@class='modal-footer']//*[@type='button']"), this);
			NewDisclaimerProceedButton = new Element("New Disclaimer Proceed Button", By.xpath("//*[@id='customModalDisclaimer'][1]//*[@class='button-close'][1]"), this);
			NewQVWarningCloseButton = new Element("New QV Warning Close Button", By.xpath("//*[@id='qvWarningPopUp']//*[@class='button-close'][1]"), this);
			NewVCMModal = new Element("New Value Case Modeler Popup", By.xpath("//*[@id='exampleModalCenter'][1]//*[@class='modal-title-subtitle']"), this);
			NewQVWarningText = new Element("New QV Warning Text", By.xpath("//*[@id='qvWarningPopUp']//*[@class='textbody-start']"), this);
			
			CompanyAnalysisTab = new Element("Company Analysis Tab", By.xpath("//*[@class='item']"), this);
			VCMTab = new Element("Value Case Modeler Tab", By.xpath("//*[@class='item item-inactive']"), this);
			CompanyAnalysisTabTooltip = new Element("Company AnalysisTab Tooltip", By.xpath("//*[@class='tooltip-text']"), this);
			NewsEvent = new Element("Latest News Event", By.xpath("//*[@class='news-details-title']"), this);
			CompanyNameTextbox = new TextBox("Company Name Textbox", By.xpath("//*[@class='tool-wrapper' or @class='tool-wrapper ng-star-inserted']//*[@type='text']"), this);
			//CompanyTypeAhead = new Element("Company Type Ahead", By.xpath("//*[@class='typeahead-container']/div[1]"), this);
			CompanyTypeAhead = new Element("Company Type Ahead", By.xpath("(//*[@class='typeahead-item ng-star-inserted' or @class='typeahead-item'])[1]"), this);
			CompanyTypeAhead1 = new Element("Company Type Ahead", By.xpath("(//*[@class='typeahead-item'])[1]"), this);
			CompanyTypeAhead2 = new Element("Company Type Ahead", By.xpath("(//*[@class='typeahead-item ng-star-inserted'])[1]"), this);
			SearchButton = new Element("Search Button", By.xpath("//*[@class='tool-btn tool-btn-active']"), this);
			SearchButton1 = new Element("Search Button", By.xpath("//*[@class='tool-btn tool-btn-inactive']"), this);
			SearchButton2 = new Element("Search Button", By.xpath("//*[@class='tool-btn ng-star-inserted tool-btn-active']"), this);
			CompanyCard1 = new Element("Company Card 1", By.xpath("(//*[@class='reports-list']//*[@class='card'])[1]"), this);
			CompanyCard2 = new Element("Company Card 2", By.xpath("(//*[@class='reports-list']//*[@class='card'])[2]"), this);
			CompanyCard3 = new Element("Company Card 3", By.xpath("(//*[@class='reports-list']//*[@class='card'])[3]"), this);
			CompanyCard4 = new Element("Company Card 4", By.xpath("(//*[@class='reports-list']//*[@class='card'])[4]"), this);
			CompanyCard5 = new Element("Company Card 5", By.xpath("(//*[@class='reports-list']//*[@class='card'])[5]"), this);
			CompanyCard39 = new Element("Company Card 39", By.xpath("(//*[@class='reports-list']//*[@class='card'])[39]"), this);
			CompanyCardType = new Element("Company Card Type", By.xpath("(//*[@class='card'])[1]//*[@class='card-type']"), this);
			CompanyCardTypeVCM = new Element("Company Card Type - VCM", By.xpath("(//*[@class='card'])[1]//*[normalize-space(text())='Value Case Modeler']"), this);
			CompanyCardDate = new Element("Company Card Date", By.xpath("(//*[@class='card'])[1]//*[@class='card-date']"), this);
			CompanyCardName = new Element("Company Card Name", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-company']"), this);
			CompanyCardName2 = new Element("Company Card Name", By.xpath("//*[@class='drag-scroll-content']//app-reports[2]//*[@class='card-company']"), this);
//			RefreshButton = new Element("Refresh Button", By.xpath("//*[@class='drag-scroll-content']/div//*[@class='ng-star-inserted'][1]//*[@class='btn']"), this);
//			RefreshButton = new Element("Refresh Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//button[1]"), this);
//			ShareButton = new Element("Share Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//button[2]"), this);
//			DownloadPPTButton = new Element("Download PPT Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//button[3]"), this);
			CompanyCardDate1 = new Element("Company Card Date", By.xpath("(//*[@class='card'])[1]//*[@class='card-date']"), this);
			CompanyCardDate2 = new Element("Company Card Date", By.xpath("(//*[@class='card'])[2]//*[@class='card-date']"), this);
			CompanyCardDate5 = new Element("Company Card Date", By.xpath("(//*[@class='card'])[5]//*[@class='card-date']"), this);
			CompanyCardDate39 = new Element("Company Card Date", By.xpath("(//*[@class='card'])[39]//*[@class='card-date']"), this);
			RefreshButton = new Element("Refresh Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-link-refresh']"), this);
			ShareButton = new Element("Share Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-link-share']"), this);
			ShareButton2 = new Element("Share Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[2]//*[@class='card-link-share']"), this);
			DownloadPPTButton = new Element("Download PPT Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-link-download']"), this);
			RefreshButton5 = new Element("Refresh Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[5]//*[@class='card-link-refresh']"), this);
			ShareButton5 = new Element("Share Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[5]//*[@class='card-link-share']"), this);
			DownloadPPTButton5 = new Element("Download PPT Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[5]//*[@class='card-link-download']"), this);
			RefreshButton39 = new Element("Refresh Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[39]//*[@class='card-link-refresh']"), this);
			ShareButton39 = new Element("Share Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[39]//*[@class='card-link-share']"), this);
			DownloadPPTButton39 = new Element("Download PPT Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[39]//*[@class='card-link-download']"), this);
			ReportsCurrent = new Element("Reports Current", By.xpath("//*[@class='reports-current']"), this);
			ReportsTotal = new Element("Reports Total Count", By.xpath("//*[@class='reports-total']"), this);
			//RefreshCloseButton = new Element("Refresh Close Button", By.xpath("//*[@class='button-close btn']"), this);
			RefreshCloseButton = new Element("Refresh Close Button", By.xpath("//*[@class='modal-content modal-content-refresh']//*[@class='modal-footer']/button"), this);
			//OverviewButton = new Element("Overview Button", By.xpath("//*[@class='drag-scroll-content']/div//*[@class='ng-star-inserted'][1]//*[@class='card-type-img']"), this);
			OverviewButton = new Element("Overview Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[1]//*[@class='card-type']/img"), this);
			OverviewButton2 = new Element("Overview Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[2]//*[@class='card-type']/img"), this);
			OverviewButton15 = new Element("Overview Button", By.xpath("//*[@class='drag-scroll-content']//app-reports[15]//*[@class='card-type']/img"), this);
			RefreshModalHeader = new Element("Refresh Modal Header", By.xpath("//*[@class='modal-content modal-content-refresh']//*[@id='exampleModalLongTitle']"), this);
			RefreshModalCompany = new Element("Refresh Modal Company", By.xpath("//*[@class='modal-content modal-content-refresh']//*[@class='textbody-refresh-info'][1]"), this);
			RefreshModalDate = new Element("Refresh Modal Request Date", By.xpath("//*[@class='modal-content modal-content-refresh']//*[@class='textbody-refresh textbody-refresh-space']"), this);
			RefreshModalDateValue = new Element("Refresh Modal Request Date value", By.xpath("(//*[@class='textbody-refresh-info'])[2]"), this);
			RefreshModalClose = new Element("Refresh Modal Close Button", By.xpath("//*[@class='modal-content modal-content-refresh']//*[@class='close']"), this);
			ShareModalHeader = new Element("Share Modal Header", By.xpath("//*[@id='exampleModalCenter-share']//*[@id='exampleModalLongTitle']"), this);
			ShareModalCompany = new Element("Share Modal Company", By.xpath("//*[@id='exampleModalCenter-share']//*[@class='textbody-share-header-info'][1]"), this);
			ShareModalDate = new Element("Share Modal Request Date", By.xpath("//*[@id='exampleModalCenter-share']//*[@class='textbody-share-header'][2]"), this);
			ShareModalDateValue = new Element("Share Modal Request Date Value", By.xpath("(//*[@class='textbody-share-header-info'])[2]"), this);
			ShareModalEmail = new TextBox("Share Modal Email", By.xpath("//*[@class='textbody-share-header-info-textarea']/input"), this);
			ShareModalShareButton = new Element("Share Modal Share Button", By.xpath("//*[@class='button-proceed']"), this);
			ShareModalCancelButton = new Element("Share Modal Cancel Button", By.xpath("//*[@class='button-close']"), this);
			ShareModalClose = new Element("Share Modal Close Button", By.xpath("//*[@id='exampleModalCenter-share']//*[@class='close']"), this);
			OldWebsiteButton = new Element("Old Website Button", By.xpath("//*[@class='header-oldArchLink']"), this);
			Copyright1 = new Element("Copyright 1", By.xpath("//*[@class='footer-copyrights-item']/div[1]"), this);
			Copyright2 = new Element("Copyright 2", By.xpath("//*[@class='footer-copyrights-item']/div[2]"), this);
			Copyright3 = new Element("Copyright 3", By.xpath("//*[@class='footer-copyrights-item']/div[3]"), this);
			DownloadUserGuideHeader = new Element("Download User Guide Header", By.xpath("//*[@id='helpComponent']/a[4]//*[@class='helpmenu-content onhover']"), this);
			EmailUsHeader = new Element("Email Us Header", By.xpath("//*[@id='helpComponent']/div[1]"), this);
			DownloadUserGuideFooter = new Element("Download User Guide Footer", By.xpath("//*[@class='footer-container']/div[3]//a[2]/*[@class='footer-item-link onhover']"), this);
			SSDashboardsCount = new Element("Self Service Dashboards Count", By.xpath("//*[@class='attributes']//*[@class='attributes-row'][1]//*[@class='attributes-col-value'][1]"), this);
			CSDashboardsCount = new Element("Custom Service Dashboards Count", By.xpath("//*[@class='attributes']//*[@class='attributes-row'][1]//*[@class='attributes-col-value'][2]"), this);
			OperationalKPIs = new Element("Operational KPIs", By.xpath("//*[@class='attributes']//*[@class='attributes-row'][6]//*[@class='attributes-col-description']"), this);
			SSOperationalKPIs = new Element("Self Service Operational KPIs", By.xpath("//*[@class='attributes']//*[@class='attributes-row'][6]//*[@class='attributes-col-value'][1]"), this);
			CSOperationalKPIs = new Element("Custom Service Operational KPIs", By.xpath("//*[@class='attributes']//*[@class='attributes-row'][6]//*[@class='attributes-col-value'][2]"), this);
			SideMenu = new Element("Side Menu", By.xpath("//*[@class='header-sidemenu']//*[@class='sidemenuexpanded isShow']/div[1]"), this);
			NewsList = new Element("News List", By.xpath("//*[@class='news-list']"), this);
			NewsListCompanyName = new Element("News List CompanyName", By.xpath("//app-news[1]//*[@class='card-type']"), this);
			NextButton = new Element("Next Button", By.xpath("//*[@class='reports-nav-right']"), this);
			PrevButton = new Element("Previous Button", By.xpath("//*[@class='reports-nav-left']"), this);
			HelpFAQ = new Element("Help - FAQ", By.xpath("(//*[@class='helpmenu-content onhover'])[2]"), this);
			HelpES = new Element("Help - Enablement Session", By.xpath("(//*[@class='helpmenu-content onhover'])[3]"), this);
			HelpDUG = new Element("Help - Download User Guide", By.xpath("(//*[@class='helpmenu-content onhover'])[4]"), this);
			HelpEU = new Element("Help - Email us", By.xpath("(//*[@class='helpmenu-needsupport onhover'])[1]"), this);
			HelpES1 = new Element("Help - Enablement Session 1", By.xpath("(//*[@class='enable-content onhover'])[1]"), this);
			HelpES2 = new Element("Help - Enablement Session 2", By.xpath("(//*[@class='enable-content onhover'])[2]"), this);
			HelpES3 = new Element("Help - Enablement Session 3", By.xpath("(//*[@class='enable-content onhover'])[3]"), this);
			HelpES4 = new Element("Help - Enablement Session 4", By.xpath("(//*[@class='enable-content onhover'])[4]"), this);
			FooterAU = new Element("Footer - About Us", By.xpath("(//*[@class='footer-item-link onhover'])[1]"), this);
			FooterFAQ = new Element("Footer - FAQ", By.xpath("(//*[@class='footer-item-link onhover'])[2]"), this);
			FooterCU = new Element("Footer - Contact Us", By.xpath("(//*[@class='footer-item-link onhover'])[2]"), this);
			FooterDUG = new Element("Footer - Download User Guide", By.xpath("(//*[@class='footer-item-link onhover'])[3]"), this);
			SavedCompContainer = new Element("Saved Company Container", By.xpath("(//*[@class='content-wrapper'])[1]"), this);
			
		}
	}
	
}