package pageobjects;

import org.openqa.selenium.By;
import auto.framework.PageBase;
import auto.framework.web.Element;
import auto.framework.web.TextBox;

public class VIPVCMPage extends PageBase{
	
	public static final Contents contents = new Contents();
	
	public static class Contents extends Element{
		
		//Common
		public final Element SideMenuVCM;
		public final Element VCMPageTitle;
		public final Element VCMModal;
		public final Element VCMModalTitle;
		public final Element VCMModalHeader;
		public final Element VCMModal1stStepTitle;
		public final Element VCMModal1stStepDescription;
		public final Element VCMModal2ndStepDescription;
		public final Element VCMModal3rdStepDescription;
		public final Element VCMModalDownloadUserGuideButton;
		public final Element VCMModalDoNotShowCheckbox;
		public final Element VCMModalDoNotShowText;
		public final Element VCMModalCloseButton;
		public final Element VCMBodyTitle;
		public final Element NextButtonDisabled;
		public final Element NextButtonEnabled;
		public final Element NextButtonEnabled2;
		
		/* Lsison, 20211019, SAVE button was removed in UI
		 * public final Element SaveButtonEnabled; public final Element
		 * SaveButtonDisabled;
		 */
		
		public final Element BackButton;
		public final Element NextButtonNote;
		public final Element NextButtonDoneNote;
		public final Element SelectedProgressBar;
		public final Element UnselectedProgressBar1;
		public final Element UnselectedProgressBar2;
		public final Element ProgressBarStep1;
		public final Element ProgressBarStep2;
		public final Element ProgressBarStep3;
		public final Element VCMTooltipText;
		public final Element VCMKPITHeaderTooltipText;
		public final Element VCMKPITTooltipText;
		public final Element VCMKPIPHeaderTooltipText;
		public final Element VCMKPIPTooltipText;
		public final Element VCMPrivateCompMessage;
		public final Element SegmentHeader1;
		public final Element SegmentHeader2;
		public final Element SegmentHeader3;
		public final Element SegmentHeader4;
		public final Element SectionHeader1;
		public final Element SectionHeader2;
		public final Element SectionHeader3;
		public final Element SectionHeader4;
		public final Element SectionHeader5;
		public final Element SectionHeader6;
		public final Element KPICOGS;
		public final Element KPISGA;
		public final Element KPIOER;
		public final Element KPI3YrCAGR;
		public final Element KPI2YrCAGR;
		public final Element KPINetPPE;
		public final Element KPIPayRev;
		public final Element KPIRecRev;
		public final Element KPIInvRev;
		public final Element KPINameCOGS;
		public final Element KPINameSGA;
		public final Element KPINameOER;
		public final Element KPIName3YrCAGR;
		public final Element KPIName2YrCAGR;
		public final Element KPINameNetPPE;
		public final Element KPINamePayRev;
		public final Element KPINameRecRev;
		public final Element KPINameInvRev;
		public final Element CircleCOGS;
		public final Element CircleRedCOGS;
		public final Element CircleGreenCOGS;
		public final Element CircleSGA;
		public final Element CircleRedSGA;
		public final Element CircleGreenSGA;
		public final Element Circle3YrCAGR;
		public final Element CircleRed3YrCAGR;
		public final Element CircleGreen3YrCAGR;
		public final Element Circle2YrCAGR;
		public final Element CircleRed2YrCAGR;
		public final Element CircleGreen2YrCAGR;
		public final Element CircleNetPPE;
		public final Element CircleRedNetPPE;
		public final Element CircleGreenNetPPE;
		public final Element CirclePayRev;
		public final Element CircleRedPayRev;
		public final Element CircleGreenPayRev;
		public final Element CircleRecRev;
		public final Element CircleRedRecRev;
		public final Element CircleGreenRecRev;
		public final Element CircleInvRev;
		public final Element CircleRedInvRev;
		public final Element CircleOrangeInvRev;
		public final Element CircleGreenInvRev;
		public final Element BetterLegendText1;
		public final Element BetterLegendCircle1;
		public final Element WorstLegendText1;
		public final Element WorstLegendCircle1;
		public final Element BetterLegendText2;
		public final Element BetterLegendCircle2;
		public final Element WorstLegendText2;
		public final Element WorstLegendCircle2;
		public final Element BetterLegendText3;
		public final Element BetterLegendCircle3;
		public final Element WorstLegendText3;
		public final Element WorstLegendCircle3;
		public final Element CRVCOCOGS;
		public final Element CRVCOSGA;
		public final Element CRVCOFO;
		public final Element CRVCOOrg;
		public final Element RGVCOPO;
		public final Element RGVCOIBD;
		public final Element RGVCOCCR;
		public final Element RGVCOSE;
		public final Element RGVCORDPE;
		public final Element RGVCONBM;
		public final Element RGVCOOP;
		public final Element RGVCOCDM;
		public final Element RGVCOSNA;
		public final Element RGVCOSPA;
		public final Element AEVCONPR;
		public final Element AEVCONPUI;
		public final Element AEVCOCM;
		public final Element AEVCODF;
		public final Element AEVCOFRC;
		public final Element AEVCORF;
		public final Element AEVCOVR;
		public final Element AEVCOIR;
		public final Element CRVCOCOGSCheckboxU;
		public final Element CRVCOCOGSCheckboxT;
		public final Element CRVCOSGACheckboxU;
		public final Element CRVCOSGACheckboxT;
		public final Element CRVCOFOCheckboxU;
		public final Element CRVCOFOCheckboxT;
		public final Element CRVCOOrgCheckboxU;
		public final Element CRVCOOrgCheckboxT;
		public final Element RGVCOPOCheckboxU;
		public final Element RGVCOPOCheckboxT;
		public final Element RGVCOIBDCheckboxU;
		public final Element RGVCOIBDCheckboxT;
		public final Element RGVCOCCRCheckboxU;
		public final Element RGVCOCCRCheckboxT;
		public final Element RGVCOSECheckboxU;
		public final Element RGVCOSECheckboxT;
		public final Element RGVCORDPECheckboxU;
		public final Element RGVCORDPECheckboxT;
		public final Element RGVCONBMCheckboxU;
		public final Element RGVCONBMCheckboxT;
		public final Element RGVCOOPCheckboxU;
		public final Element RGVCOOPCheckboxT;
		public final Element RGVCOCDMCheckboxU;
		public final Element RGVCOCDMCheckboxT;
		public final Element RGVCOSNACheckboxU;
		public final Element RGVCOSNACheckboxT;
		public final Element RGVCOSPACheckboxU;
		public final Element RGVCOSPACheckboxT;
		public final Element AEVCONPRCheckboxU;
		public final Element AEVCONPRCheckboxT;
		public final Element AEVCONPUICheckboxU;
		public final Element AEVCONPUICheckboxT;
		public final Element AEVCOCMCheckboxU;
		public final Element AEVCOCMCheckboxT;
		public final Element AEVCODFCheckboxU;
		public final Element AEVCODFCheckboxT;
		public final Element AEVCOFRCCheckboxU;
		public final Element AEVCOFRCCheckboxT;
		public final Element AEVCORFCheckboxU;
		public final Element AEVCORFCheckboxT;
		public final Element AEVCOVRCheckboxU;
		public final Element AEVCOVRCheckboxT;
		public final Element AEVCOIRCheckboxU;
		public final Element AEVCOIRCheckboxT;
		public final Element CRVCOCOGSTooltip;
		public final Element CRVCOSGATooltip;
		public final Element CRVCOFOTooltip;
		public final Element CRVCOOrgTooltip;
		public final Element RGVCOPOTooltip;
		public final Element RGVCOIBDTooltip;
		public final Element RGVCOCCRTooltip;
		public final Element RGVCOSETooltip;
		public final Element RGVCORDPETooltip;
		public final Element RGVCONBMTooltip;
		public final Element RGVCOOPTooltip;
		public final Element RGVCOCDMTooltip;
		public final Element RGVCOSNATooltip;
		public final Element RGVCOSPATooltip;
		public final Element AEVCONPRTooltip;
		public final Element AEVCONPUITooltip;
		public final Element AEVCOCMTooltip;
		public final Element AEVCODFTooltip;
		public final Element AEVCOFRCTooltip;
		public final Element AEVCORFTooltip;
		public final Element AEVCOVRTooltip;
		public final Element AEVCOIRTooltip;
		public final TextBox VCOName;
		public final Element VCOCategory;
		public final TextBox VCODescription;
		public final Element VCOAddDisabled;
		public final Element VCOAddEnabled;
		public final Element VCOEdit;
		public final Element VCOCategory1;
		public final Element VCOCategory2;
		public final Element VCOCategory3;
		public final Element AddedVCOListHeader1;
		public final Element AddedVCOListHeader2;
		public final Element AddedVCOListHeader3;
		public final Element AddedVCOName1;
		public final Element AddedVCOCategory1;
		public final Element AddedVCODescription1;
		public final Element AddedVCOEditButton1;
		public final Element AddedVCODeleteButton1;
		
		public final Element Accordion1;
		public final Element Accordion2;
		public final Element VCOAssumptionDropdown;
		public final Element VCOCategoryCostReduction;
		public final Element VCOCategoryCOGS;
		public final Element VCOCategorySGA;
		public final Element VCOCategoryORG;
		public final Element VCOCategoryRevenueGrowth;
		public final Element VCOCategoryPO;
		public final Element VCOCategoryAssetEfficiency;
		public final Element VCOCategoryNPR;
		public final Element VCOCategoryFRC;
		public final Element VCOCategoryVR;
		public final Element VCOCategoryIR;
		public final TextBox AddressableSGATextbox;
		public final TextBox SGAReductionTextbox;
		public final TextBox YearsForCostReductionTextbox;
		public final TextBox RecurringOpexAddressableSGATextbox;
		public final TextBox VCOImplementationCapexTextbox;
		public final TextBox CapexSpendingPeriodTextbox;
		public final Element CalculateDisabled;
		public final Element CalculateEnabled;
		public final TextBox WACCTextbox;
		public final Element WACCEditIcon;
		public final TextBox TerminalGrowthRateTextbox;
		public final Element TerminalGrowthRateEditIcon;
		public final TextBox EnterpriseValueTextbox;
		public final Element EnterpriseValueEditIcon;
		public final Element VCMInputTooltipText;
		public final Element WACCTooltip;
		public final Element TerminalGrowthRateTooltip;
		public final Element EnterpriseValueTooltip;
		public final Element EditEVModal;
		public final Element EditEVModalHeader;
		public final Element EditEVModalSubTitle;
		public final Element EditEVModalEditIcon;
		public final Element EditEVModalProceedButton;
		public final Element EditEVTooltipText;
		public final Element MarketCapitalizationLabel;
		public final Element MarketCapitalizationTooltip;
		public final TextBox MarketCapitalizationTextbox;
		public final Element MinorityInterestLabel;
		public final Element MinorityInterestTooltip;
		public final TextBox MinorityInterestTextbox;
		public final Element TotalDebtLabel;
		public final Element TotalDebtTooltip;
		public final TextBox TotalDebtTextbox;
		public final Element ShortTermInvestmentsLabel;
		public final Element ShortTermInvestmentsTooltip;
		public final TextBox ShortTermInvestmentsTextbox;
		public final Element PreferredEquityLabel;
		public final Element PreferredEquityTooltip;
		public final TextBox PreferredEquityTextbox;
		public final Element TotalEVLabel;
		public final Element TotalEVTooltip;
		public final TextBox TotalEVTextbox;
		public final Element LongTermInvestmentsLabel;
		public final Element LongTermInvestmentsTooltip;
		public final TextBox LongTermInvestmentsTextbox;
		public final Element OperatingEVLabel;
		public final Element OperatingEVTooltip;
		public final TextBox OperatingEVTextbox;
		public final Element MarketCapitalizationLabelR;
		public final Element MinorityInterestLabelR;
		public final Element TotalDebtLabelR;
		public final Element ShortTermInvestmentsLabelR;
		public final Element PreferredEquityLabelR;
		public final Element TotalEVLabelR;
		public final Element LongTermInvestmentsLabelR;
		public final Element OperatingEVLabelR;
		public final Element ReferenceDataName1_1;
		public final Element ReferenceDataValue1_1;
		public final Element ReferenceDataName1_2;
		public final Element ReferenceDataValue1_2;
		public final Element ReferenceDataName2_1;
		public final Element ReferenceDataValue2_1;
		public final Element ReferenceDataName2_2;
		public final Element ReferenceDataValue2_2;
		public final Element ReferenceDataName3_1;
		public final Element ReferenceDataValue3_1;
		public final Element ReferenceDataName3_2;
		public final Element ReferenceDataValue3_2;
		public final Element EaseOfImplementation;
		public final Element EaseOfImplementation1;
		public final Element EaseOfImplementation2;
		public final Element EaseOfImplementation3;
		public final Element EaseOfImplementation4;
		public final Element EaseOfImplementation5;
		public final Element EaseOfImplementation6;
		public final Element Chart1;
		public final Element Chart2;
		public final Element Chart1Title;
		public final Element Chart1SubTitle1;
		public final Element Chart1SubTitle2;
		public final Element SelectionTab1;
		public final Element SelectionTab2;
		public final Element SelectionTab3;
		public final Element SelectionTab4;
		public final Element CompanyCurrency;
		public final Element CRLegendCircle;
		public final Element CRLegendText;
		public final Element RGLegendCircle;
		public final Element RGLegendText;
		public final Element AELegendCircle;
		public final Element AELegendText;
		
		/* Lsison, 20211019, SAVE button was removed in UI
		 * public final Element VCMSaveModal; public final Element VCMSaveModalHeader;
		 * public final Element VCMSaveModalMessage; public final Element
		 * VCMSaveModalSaveButton; public final Element VCMSaveModalCloseButton;
		 */
		
		public final Element VCMHelpIcon;
		public final Element VCMFootNote;
		public final Element UpgradeInProgressClose;
		
		
		public Contents() {
			super("Container", By.className("mainContainer"));
			
			//Common
			UpgradeInProgressClose = new Element("Upgrade In Progress", By.xpath("//*[@class='close-xbtn add-cls']"), this);
			//SideMenuVCM = new Element("Side Menu Value Case Modeler", By.xpath("//*[@class='header-sidemenu']//*[@class='sidemenuexpanded isShow']/div[7]"), this);
			SideMenuVCM = new Element("Side Menu Value Case Modeler", By.xpath("//*[@src='../../assets/images/vcm-side-b.png' or @src='../../assets/images/vcm-side-p.png']"), this);
			//SideMenuVCM = new Element("Side Menu Value Case Modeler", By.xpath("(//*[@class=\"sidemenuexpanded-otheroptions-img\"])[8]"), this); //Replace SideMenuVCM Xpath
			VCMPageTitle = new Element("VCM Page Title", By.xpath("//*[@class='vcm-vcmtitle']"), this);
			VCMModal = new Element("VCM Modal Popup", By.xpath("//*[@id='vcmViewUses']"), this);
			VCMModalTitle = new Element("VCM Modal Popup Title", By.xpath("//*[@id='vcmViewUses']//*[@id='exampleModalLongTitle']"), this);
			VCMModalHeader = new Element("VCM Modal Popup Header", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-custom-paragraph-stly']"), this);
			VCMModal1stStepTitle = new Element("VCM Modal 1st Step Title - How to use?", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-custom-second']"), this);
			VCMModal1stStepDescription = new Element("VCM Modal 1st Step Description", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-boxs'][1]/p"), this);
			VCMModal2ndStepDescription = new Element("VCM Modal 2nd Step Description", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-boxs'][3]/p"), this);
			VCMModal3rdStepDescription = new Element("VCM Modal 3rd Step Description", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-boxs'][5]/p"), this);
			VCMModalDownloadUserGuideButton = new Element("VCM Modal Download User Guide Button", By.xpath("//*[@id='vcmViewUses']//*[@class='modal-btn-dl']"), this);
			VCMModalDoNotShowCheckbox = new Element("VCM Modal Do Not Show Checkbox", By.xpath("//*[@class='modal-custom-select-chk']//*[@class='checkmark']"), this);
			VCMModalDoNotShowText = new Element("VCM Modal Do Not Show Text", By.xpath("//*[@class='modal-custom-select-chk']//*[@class='modal-custom-chk-paragraph']"), this);
			VCMModalCloseButton = new Element("VCM Modal Close Button", By.xpath("//*[@id='vcmViewUses']//*[@class='close-xbtn add-cls']"), this);
			VCMBodyTitle = new Element("VCM Body Title", By.xpath("//*[@class='vcm-body-top-title']"), this);
			NextButtonDisabled = new Element("Next Button Disabled", By.xpath("//*[@class='vcm-body-top-proceed ng-star-inserted']"), this);
			NextButtonEnabled = new Element("Next Button Enabled", By.xpath("//*[@class='vcm-body-top-proceed ng-star-inserted vcm-body-top-proceed-go']"), this);
			NextButtonEnabled2 = new Element("Next Button Enabled", By.xpath("//*[@class='vcm-body-top-proceed vcm-body-top-proceed-go ng-star-inserted']"), this);
			
			/* Lsison, 20211019, SAVE button was removed in UI
			 * SaveButtonEnabled = new Element("Save Button Enabled", By.
			 * xpath("//*[@class='vcm-body-top-proceed vcm-body-top-proceed-go ng-star-inserted']"
			 * ), this); SaveButtonDisabled = new Element("Save Button Disabled", By.
			 * xpath("//*[@class='vcm-body-top-proceed vcm-body-top-proceed-go ng-star-inserted grey']"
			 * ), this);
			 */
			
			NextButtonNote = new Element("Next Button Note", By.xpath("//*[@class='vcm-body-top-proceed-note ng-star-inserted']"), this);
			NextButtonDoneNote = new Element("Next Button Done Note", By.xpath("//*[@class='vcm-body-top-proceed-note ng-star-inserted vcm-body-top-proceed-note-allow']"), this);
			BackButton = new Element("Back Button", By.xpath("//*[@class='vcm-body-top-back ng-star-inserted']"), this);
			SelectedProgressBar = new Element("Selected Progress Bar", By.xpath("//*[@class='rect vcm-progressbar2-step ng-star-inserted']"), this);
			UnselectedProgressBar1 = new Element("Unselected Progress Bar 1", By.xpath("//*[@class='rect vcm-progressbar2-step ng-star-inserted lightviolet-1']"), this);
			UnselectedProgressBar2 = new Element("Unselected Progress Bar 2", By.xpath("//*[@class='rect vcm-progressbar2-step ng-star-inserted lightviolet']"), this);
			ProgressBarStep1 = new Element("Progress Bar Step 1", By.xpath("//*[@class='vcm-progressbar2-text-step'][1]"), this);
			ProgressBarStep2 = new Element("Progress Bar Step 2", By.xpath("//*[@class='vcm-progressbar2-text-step'][2]"), this);
			ProgressBarStep3 = new Element("Progress Bar Step 3", By.xpath("//*[@class='vcm-progressbar2-text-step'][3]"), this);
			VCMTooltipText = new Element("VCM Tooltip Text", By.xpath("//*[@class='selectvco-vcoitem-tooltip ng-star-inserted']"), this);
			VCMKPITHeaderTooltipText = new Element("VCM Target Company KPI Header Tooltip Text", By.xpath("//*[@class='selectvco-kpi-info-box ng-star-inserted']/div[1]"), this);
			VCMKPITTooltipText = new Element("VCM Target Company KPI Tooltip Text", By.xpath("//*[@class='selectvco-kpi-info-box ng-star-inserted']/div[2]"), this);
			VCMKPIPHeaderTooltipText = new Element("VCM Peer Median Header Tooltip Text", By.xpath("//*[@class='selectvco-kpi-info-box ng-star-inserted']/div[3]"), this);
			VCMKPIPTooltipText = new Element("VCM Peer Median Tooltip Text", By.xpath("//*[@class='selectvco-kpi-info-box ng-star-inserted']/div[4]"), this);
			VCMPrivateCompMessage = new Element("VCM Private Company Message", By.xpath("//*[@class='vcm-forprivate ng-star-inserted']"), this);
			SegmentHeader1 = new Element("Segment Header 1 - Cost Reduction", By.xpath("(//*[@class='selectvco-valuedriver-title'])[1]"), this);
			SegmentHeader2 = new Element("Segment Header 2 - Revenue Growth", By.xpath("(//*[@class='selectvco-valuedriver-title'])[2]"), this);
			SegmentHeader3 = new Element("Segment Header 3 - Asset Efficiency", By.xpath("(//*[@class='selectvco-valuedriver-title'])[3]"), this);
			SegmentHeader4 = new Element("Segment Header 4 - Add Custom VCO", By.xpath("(//*[@class='selectvco-valuedriver-title'])[4]"), this);
			SectionHeader1 = new Element("Cost Reduction - COMPANY PERFORMANCE", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[1]"), this);
			SectionHeader2 = new Element("Cost Reduction - VALUE CREATION OPPORTUNITIES (VCO)", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[2]"), this);
			SectionHeader3 = new Element("Revenue Growth - COMPANY PERFORMANCE", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[3]"), this);
			SectionHeader4 = new Element("Revenue Growth - VALUE CREATION OPPORTUNITIES (VCO)", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[4]"), this);
			SectionHeader5 = new Element("Asset Efficiency - COMPANY PERFORMANCE", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[5]"), this);
			SectionHeader6 = new Element("Asset Efficiency - VALUE CREATION OPPORTUNITIES (VCO)", By.xpath("(//*[@class='selectvco-valuedriver-title-sub'])[6]"), this);
			KPICOGS = new Element("COGS / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[1]"), this);
			KPISGA = new Element("SG&A / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[2]"), this);
			KPIOER = new Element("Operating Expense / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[1]"), this);
			KPI3YrCAGR = new Element("3-yr Revenue CAGR KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[3]"), this);
			KPI2YrCAGR = new Element("2-yr Revenue CAGR KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[4]"), this);
			KPINetPPE = new Element("Net PP&E / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[5]"), this);
			KPIPayRev = new Element("Payables / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[6]"), this);
			KPIRecRev = new Element("Receivables / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[7]"), this);
			KPIInvRev = new Element("Inventory / Revenue KPI", By.xpath("(//*[@class='selectvco-kpi-value'])[8]"), this);
			KPINameCOGS = new Element("COGS / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[1]"), this);
			KPINameSGA = new Element("SG&A / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[2]"), this);
			KPINameOER = new Element("Operating Expense / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[1]"), this);
			KPIName3YrCAGR = new Element("3-yr Revenue CAGR KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[3]"), this);
			KPIName2YrCAGR = new Element("2-yr Revenue CAGR KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[4]"), this);
			KPINameNetPPE = new Element("Net PP&E / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[5]"), this);
			KPINamePayRev = new Element("Payables / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[6]"), this);
			KPINameRecRev = new Element("Receivables / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[7]"), this);
			KPINameInvRev = new Element("Inventory / Revenue KPI Name", By.xpath("(//*[@class='selectvco-kpi-name'])[8]"), this);
			CircleCOGS = new Element("COGS Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[1]"), this);
			CircleRedCOGS = new Element("COGS Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[1]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreenCOGS = new Element("COGS Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[1]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			CircleSGA = new Element("SGA Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[2]"), this);
			CircleRedSGA = new Element("SGA Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[2]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreenSGA = new Element("SGA Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[2]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			Circle3YrCAGR = new Element("3YrCAGR Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[3]"), this);
			CircleRed3YrCAGR = new Element("3YrCAGR Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[3]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreen3YrCAGR = new Element("3YrCAGR Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[3]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			Circle2YrCAGR = new Element("2YrCAGR Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[4]"), this);
			CircleRed2YrCAGR = new Element("2YrCAGR Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[4]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreen2YrCAGR = new Element("2YrCAGR Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[4]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			CircleNetPPE = new Element("NetPPE Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[5]"), this);
			CircleRedNetPPE = new Element("NetPPE Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[5]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreenNetPPE = new Element("NetPPE Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[5]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			CirclePayRev = new Element("PayRev Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[6]"), this);
			CircleRedPayRev = new Element("PayRev Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[6]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreenPayRev = new Element("PayRev Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[6]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			CircleRecRev = new Element("RecRev Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[7]"), this);
			CircleRedRecRev = new Element("RecRev Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[7]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleGreenRecRev = new Element("RecRev Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[7]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			CircleInvRev = new Element("InvRev Legend", By.xpath("(//*[@class='selectvco-kpi-lightindicator'])[8]"), this);
			CircleRedInvRev = new Element("InvRev Red Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[8]//*[@style='background-color: rgb(227, 107, 95);']"), this);
			CircleOrangeInvRev = new Element("InvRev Orange Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[8]//*[@style='background-color: rgb(245, 209, 112);']"), this);
			CircleGreenInvRev = new Element("InvRev Green Legend", By.xpath("(//*[@class='selectvco-kpi-item'])[8]//*[@style='background-color: rgb(184, 222, 112);']"), this);
			BetterLegendText1 = new Element("Cost Reduction - Better than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[1]"), this);
			BetterLegendCircle1 = new Element("Cost Reduction - Better than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-green'])[1]"), this);
			WorstLegendText1 = new Element("Cost Reduction - Worst than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[2]"), this);
			WorstLegendCircle1 = new Element("Cost Reduction - Worst than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-red'])[1]"), this);
			BetterLegendText2 = new Element("Revenue Growth - Better than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[3]"), this);
			BetterLegendCircle2 = new Element("Revenue Growth - Better than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-green'])[2]"), this);
			WorstLegendText2 = new Element("Revenue Growth - Worst than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[4]"), this);
			WorstLegendCircle2 = new Element("Revenue Growth - Worst than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-red'])[2]"), this);
			BetterLegendText3 = new Element("Asset Efficiency - Better than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[5]"), this);
			BetterLegendCircle3 = new Element("Asset Efficiency - Better than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-green'])[3]"), this);
			WorstLegendText3 = new Element("Asset Efficiency - Worst than Peer Median Legend Text", By.xpath("(//*[@class='selectvco-legend-text'])[6]"), this);
			WorstLegendCircle3 = new Element("Asset Efficiency - Worst than Peer Median Legend Circle", By.xpath("(//*[@class='selectvco-lightindicator-red'])[3]"), this);
			CRVCOCOGS = new Element("Cost Reduction VCO - COGS", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[1]"), this);
			CRVCOSGA = new Element("Cost Reduction VCO - SG&A", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[2]"), this);
			CRVCOFO = new Element("Cost Reduction VCO - Front Office", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[3]"), this);
			CRVCOOrg = new Element("Cost Reduction VCO - Organization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[4]"), this);
			RGVCOPO = new Element("Revenue Growth VCO - Price Optimization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[5]"), this);
			RGVCOIBD = new Element("Revenue Growth VCO - Increase Brand Distinction", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[6]"), this);
			RGVCOCCR = new Element("Revenue Growth VCO - Customer Churn Reduction", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[7]"), this);
			RGVCOSE = new Element("Revenue Growth VCO - Salesforce Effectiveness", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[8]"), this);
			RGVCORDPE = new Element("Revenue Growth VCO - R&D Productivity Enhancement", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[9]"), this);
			RGVCONBM = new Element("Revenue Growth VCO - New Business Models", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[10]"), this);
			RGVCOOP = new Element("Revenue Growth VCO - Omnichannel Presence", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[11]"), this);
			RGVCOCDM = new Element("Revenue Growth VCO - Customer Data Monetization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[12]"), this);
			RGVCOSNA = new Element("Revenue Growth VCO - Synergy from New Acquisitions", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[13]"), this);
			RGVCOSPA = new Element("Revenue Growth VCO - Synergy from Past Acquisitions", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[14]"), this);
			AEVCONPR = new Element("Asset Efficiency VCO - Net PP&E Rationalization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[15]"), this);
			AEVCONPUI = new Element("Asset Efficiency VCO - Net PP&E Utilization Improvement", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[16]"), this);
			AEVCOCM = new Element("Asset Efficiency VCO - Contract Manufacturing", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[17]"), this);
			AEVCODF = new Element("Asset Efficiency VCO - Digital Factory", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[18]"), this);
			AEVCOFRC = new Element("Asset Efficiency VCO - Faster Receivables Collection", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[19]"), this);
			AEVCORF = new Element("Asset Efficiency VCO - Receivables Factorization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[20]"), this);
			AEVCOVR = new Element("Asset Efficiency VCO - Vendor Rationalization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[21]"), this);
			AEVCOIR = new Element("Asset Efficiency VCO - Inventory Rationalization", By.xpath("(//*[@class='selectvco-vcoitem-name-container'])[22]"), this);
			CRVCOCOGSCheckboxU = new Element("Cost Reduction VCO - COGS Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[1]//*[@class='glyphicon glyphicon-ok']"), this);
			CRVCOCOGSCheckboxT = new Element("Cost Reduction VCO - COGS Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[1]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			CRVCOSGACheckboxU = new Element("Cost Reduction VCO - SGA Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[2]//*[@class='glyphicon glyphicon-ok']"), this);
			CRVCOSGACheckboxT = new Element("Cost Reduction VCO - SGA Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[2]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			CRVCOFOCheckboxU = new Element("Cost Reduction VCO - Front Office Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[3]//*[@class='glyphicon glyphicon-ok']"), this);
			CRVCOFOCheckboxT = new Element("Cost Reduction VCO - Front Office Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[3]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			CRVCOOrgCheckboxU = new Element("Cost Reduction VCO - Organization Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[4]//*[@class='glyphicon glyphicon-ok']"), this);
			CRVCOOrgCheckboxT = new Element("Cost Reduction VCO - Organization Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[4]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOPOCheckboxU = new Element("Revenue Growth VCO - PO Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[5]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOPOCheckboxT = new Element("Revenue Growth VCO - PO Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[5]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOIBDCheckboxU = new Element("Revenue Growth VCO - IBD Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[6]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOIBDCheckboxT = new Element("Revenue Growth VCO - IBD Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[6]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOCCRCheckboxU = new Element("Revenue Growth VCO - CCR Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[7]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOCCRCheckboxT = new Element("Revenue Growth VCO - CCR Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[7]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOSECheckboxU = new Element("Revenue Growth VCO - SE Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[8]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOSECheckboxT = new Element("Revenue Growth VCO - SE Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[8]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCORDPECheckboxU = new Element("Revenue Growth VCO - RDPE Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[9]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCORDPECheckboxT = new Element("Revenue Growth VCO - RDPE Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[9]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCONBMCheckboxU = new Element("Revenue Growth VCO - NBM Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[10]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCONBMCheckboxT = new Element("Revenue Growth VCO - NBM Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[10]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOOPCheckboxU = new Element("Revenue Growth VCO - OP Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[11]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOOPCheckboxT = new Element("Revenue Growth VCO - OP Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[11]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOCDMCheckboxU = new Element("Revenue Growth VCO - CDM Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[12]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOCDMCheckboxT = new Element("Revenue Growth VCO - CDM Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[12]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOSNACheckboxU = new Element("Revenue Growth VCO - SNA Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[13]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOSNACheckboxT = new Element("Revenue Growth VCO - SNA Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[13]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			RGVCOSPACheckboxU = new Element("Revenue Growth VCO - SPA Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[14]//*[@class='glyphicon glyphicon-ok']"), this);
			RGVCOSPACheckboxT = new Element("Revenue Growth VCO - SPA Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[14]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCONPRCheckboxU = new Element("Asset Efficiency VCO - NPR Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[15]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCONPRCheckboxT = new Element("Asset Efficiency VCO - NPR Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[15]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCONPUICheckboxU = new Element("Asset Efficiency VCO - NPUI Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[16]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCONPUICheckboxT = new Element("Asset Efficiency VCO - NPUI Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[16]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCOCMCheckboxU = new Element("Asset Efficiency VCO - CM Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[17]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCOCMCheckboxT = new Element("Asset Efficiency VCO - CM Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[17]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCODFCheckboxU = new Element("Asset Efficiency VCO - DF Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[18]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCODFCheckboxT = new Element("Asset Efficiency VCO - DF Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[18]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCOFRCCheckboxU = new Element("Asset Efficiency VCO - FRC Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[19]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCOFRCCheckboxT = new Element("Asset Efficiency VCO - FRC Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[19]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCORFCheckboxU = new Element("Asset Efficiency VCO - RF Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[20]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCORFCheckboxT = new Element("Asset Efficiency VCO - RF Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[20]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCOVRCheckboxU = new Element("Asset Efficiency VCO - VR Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[21]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCOVRCheckboxT = new Element("Asset Efficiency VCO - VR Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[21]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			AEVCOIRCheckboxU = new Element("Asset Efficiency VCO - IR Checkbox (Untick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[22]//*[@class='glyphicon glyphicon-ok']"), this);
			AEVCOIRCheckboxT = new Element("Asset Efficiency VCO - IR Checkbox (Tick)", By.xpath("(//*[@class='selectvco-vcoitem-cb'])[22]//*[@class='glyphicon glyphicon-ok changeToPurple']"), this);
			CRVCOCOGSTooltip = new Element("Cost Reduction VCO - COGS Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[1]"), this);
			CRVCOSGATooltip = new Element("Cost Reduction VCO - SG&A Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[2]"), this);
			CRVCOFOTooltip = new Element("Cost Reduction VCO - Front Office Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[3]"), this);
			CRVCOOrgTooltip = new Element("Cost Reduction VCO - Organization Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[4]"), this);
			RGVCOPOTooltip = new Element("Revenue Growth VCO - Price Optimization Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[5]"), this);
			RGVCOIBDTooltip = new Element("Revenue Growth VCO - Increase Brand Distinction Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[6]"), this);
			RGVCOCCRTooltip = new Element("Revenue Growth VCO - Customer Churn Reduction Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[7]"), this);
			RGVCOSETooltip = new Element("Revenue Growth VCO - Salesforce Effectiveness Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[8]"), this);
			RGVCORDPETooltip = new Element("Revenue Growth VCO - R&D Productivity Enhancement Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[9]"), this);
			RGVCONBMTooltip = new Element("Revenue Growth VCO - New Business Models Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[10]"), this);
			RGVCOOPTooltip = new Element("Revenue Growth VCO - Omnichannel Presence Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[11]"), this);
			RGVCOCDMTooltip = new Element("Revenue Growth VCO - Customer Data Monetization Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[12]"), this);
			RGVCOSNATooltip = new Element("Revenue Growth VCO - Synergy from New Acquisitions Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[13]"), this);
			RGVCOSPATooltip = new Element("Revenue Growth VCO - Synergy from Past Acquisitions Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[14]"), this);
			AEVCONPRTooltip = new Element("Asset Efficiency VCO - NPR Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[15]"), this);
			AEVCONPUITooltip = new Element("Asset Efficiency VCO - NPUI Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[16]"), this);
			AEVCOCMTooltip = new Element("Asset Efficiency VCO - CM Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[17]"), this);
			AEVCODFTooltip = new Element("Asset Efficiency VCO - DF Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[18]"), this);
			AEVCOFRCTooltip = new Element("Asset Efficiency VCO - FRC Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[19]"), this);
			AEVCORFTooltip = new Element("Asset Efficiency VCO - RF Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[20]"), this);
			AEVCOVRTooltip = new Element("Asset Efficiency VCO - VR Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[21]"), this);
			AEVCOIRTooltip = new Element("Asset Efficiency VCO - IR Tooltip", By.xpath("(//*[@class='selectvco-vcoitem-info-icon'])[22]"), this);
			VCOName = new TextBox("Add Custom VCO - VCO Name Textbox", By.xpath("//*[@class='selectvco-custom-body']/input"), this);
			VCOCategory = new Element("Add Custom VCO - VCO Category Dropdown", By.xpath("//*[@class='selectvco-custom-body']//*[@id='button-basic']"), this);
			VCODescription = new TextBox("Add Custom VCO - VCO Description Textbox", By.xpath("//*[@class='selectvco-custom-body-desc']/textarea"), this);
			VCOAddDisabled = new Element("Add Custom VCO - VCO Add Button", By.xpath("//*[@class='selectvco-custom-button ng-star-inserted']"), this);
			VCOAddEnabled = new Element("Add Custom VCO - VCO Add Button", By.xpath("//*[@class='selectvco-custom-button ng-star-inserted selectvco-custom-button-go']"), this);
			VCOEdit = new Element("Add Custom VCO - VCO Edit Button", By.xpath("//*[@class='selectvco-custom-button selectvco-custom-button-go ng-star-inserted']"), this);
			VCOCategory1 = new Element("VCO Category - Cost Reduction", By.xpath("(//*[@id='dropdown-basic']//*[@role='menuitem'])[1]"), this);
			VCOCategory2 = new Element("VCO Category - Revenue Growth", By.xpath("(//*[@id='dropdown-basic']//*[@role='menuitem'])[2]"), this);
			VCOCategory3 = new Element("VCO Category - Asset Efficiency", By.xpath("(//*[@id='dropdown-basic']//*[@role='menuitem'])[3]"), this);
			AddedVCOListHeader1 = new Element("Added VCO List Header - VCO Name", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-title-row']/div[1]"), this);
			AddedVCOListHeader2 = new Element("Added VCO List Header - VCO Category", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-title-row']/div[2]"), this);
			AddedVCOListHeader3 = new Element("Added VCO List Header - VCO Description", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-title-row']/div[3]"), this);
			AddedVCOName1 = new Element("Added VCO Name 1", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-item-row ng-star-inserted'][1]/div[1]"), this);
			AddedVCOCategory1 = new Element("Added VCO Category 1", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-item-row ng-star-inserted'][1]/div[2]"), this);
			AddedVCODescription1 = new Element("Added VCO Description 1", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-item-row ng-star-inserted'][1]/div[3]"), this);
			AddedVCOEditButton1 = new Element("Added VCO Edit 1", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-item-row ng-star-inserted'][1]//*[@class='glyphicon glyphicon-pencil']"), this);
			AddedVCODeleteButton1 = new Element("Added VCO Delete 1", By.xpath("//*[@class='row selectvco-custom-row selectvco-custom-table-item-row ng-star-inserted'][1]//*[@class='selectvco-custom-img']"), this);
			
			Accordion1 = new Element("OVERALL DCF ASSUMPTIONS Accordion", By.xpath("(//*[@class='accordion-toggle'])[1]"), this);
			Accordion2 = new Element("VCO ASSUMPTIONS Accordion", By.xpath("(//*[@class='accordion-toggle'])[2]"), this);
			VCOAssumptionDropdown = new Element("VCO ASSUMPTIONS Dropdown", By.xpath("//*[@class='btn btn-primary btnVCM']"), this);
			VCOCategoryCostReduction = new Element("VCO Category - Cost Reduction", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Cost Reduction']"), this);
			VCOCategoryCOGS = new Element("VCO Category - COGS", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='ZBSC (COGS)']"), this);
			VCOCategorySGA = new Element("VCO Category - SGA", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='ZBS (SG&A)']"), this);
			VCOCategoryORG = new Element("VCO Category - ORG", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='ZBO (organization)']"), this);
			VCOCategoryRevenueGrowth = new Element("VCO Category - Revenue Growth", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Revenue Growth']"), this);
			VCOCategoryPO = new Element("VCO Category - PO", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Price Optimization']"), this);
			VCOCategoryAssetEfficiency = new Element("VCO Category - Asset Efficiency", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Asset Efficiency']"), this);
			VCOCategoryNPR = new Element("VCO Category - NPR", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Net PP&E Rationalization']"), this);
			VCOCategoryFRC = new Element("VCO Category - FRC", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Faster Receivables Collection']"), this);
			VCOCategoryVR = new Element("VCO Category - VR", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Vendor Rationalization']"), this);
			VCOCategoryIR = new Element("VCO Category - IR", By.xpath("//*[@class='ng-star-inserted']//*[normalize-space(text())='Inventory Rationalization']"), this);
			AddressableSGATextbox = new TextBox("Addressable SG&A Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[1]/input"), this);
			SGAReductionTextbox = new TextBox("SG&A Reduction Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[2]/input"), this);
			YearsForCostReductionTextbox = new TextBox("# years for Cost Reduction Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[3]/input"), this);
			RecurringOpexAddressableSGATextbox = new TextBox("Recurring Opex as % of Addressable SG&A Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[4]/input"), this);
			VCOImplementationCapexTextbox = new TextBox("VCO Implementation Capex Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[5]/input"), this);
			CapexSpendingPeriodTextbox = new TextBox("Capex Spending Period Textbox", By.xpath("(//*[@class='assumption-inputs-form'])[6]/input"), this);
			CalculateDisabled = new Element("Calculate Disabled Button", By.xpath("//*[@class='assumptions-calcbtn']"), this);
			CalculateEnabled = new Element("Calculate Enabled Button", By.xpath("//*[@class='assumptions-calcbtn assumptions-calcbtn-go']"), this);
			WACCTextbox = new TextBox("WACC Textbox", By.xpath("(//*[@class='fcfInputs-item-cont'])[1]/input"), this);
			WACCEditIcon = new Element("WACC Edit Icon", By.xpath("(//*[@class='fcfInputs-item-cont'])[1]/img"), this);
			TerminalGrowthRateTextbox = new TextBox("Terminal Growth Rate Textbox", By.xpath("(//*[@class='fcfInputs-item-cont'])[2]/input"), this);
			TerminalGrowthRateEditIcon = new Element("Terminal Growth Rate EditIcon", By.xpath("(//*[@class='fcfInputs-item-cont'])[2]/img"), this);
			EnterpriseValueTextbox = new TextBox("Enterprise Value Textbox", By.xpath("(//*[@class='fcfInputs-item-cont'])[3]/input"), this);
			EnterpriseValueEditIcon = new Element("Enterprise Value EditIcon", By.xpath("(//*[@class='fcfInputs-item-cont'])[3]/img"), this);
			VCMInputTooltipText = new Element("VCM Input Tooltip Text", By.xpath("//*[@class='fcfInputs-item-tooltiptxt']"), this);
			WACCTooltip = new Element("WACC Tooltip Icon", By.xpath("(//*[@class='fcfInputs-item-info'])[1]"), this);
			TerminalGrowthRateTooltip = new Element("Terminal Growth Rate Tooltip Icon", By.xpath("(//*[@class='fcfInputs-item-info'])[2]"), this);
			EnterpriseValueTooltip = new Element("EnterpriseValue Tooltip Icon", By.xpath("(//*[@class='fcfInputs-item-info'])[3]"), this);
			EditEVModal = new Element("Review Enterprise Value Dissection Modal", By.xpath("//*[@id='vcmEditEvModel']"), this);
			EditEVModalHeader = new Element("Review Enterprise Value Dissection Modal Header", By.xpath("//*[@id='vcmEditEvModel']//*[@class='modal-title']"), this);
			EditEVModalSubTitle = new Element("Review Enterprise Value Dissection Modal SubTitle", By.xpath("//*[@id='vcmEditEvModel']//*[@class='modal-body-subtitle-date']"), this);
			EditEVModalEditIcon = new Element("Review Enterprise Value Dissection Modal EditIcon", By.xpath("//*[@id='vcmEditEvModel']//*[@class='modal-body-subtitle-img ng-star-inserted']"), this);
			EditEVModalProceedButton = new Element("Review Enterprise Value Dissection Modal ProceedButton", By.xpath("//*[@id='vcmEditEvModel']//*[@class='modal-proceed']"), this);
			EditEVTooltipText = new Element("Review Enterprise Value Dissection Modal Tooltip Text", By.xpath("//*[@class='modal-body-item-tooltiptxt ng-star-inserted']"), this);
			MarketCapitalizationLabel = new Element("Market Capitalization Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[1]/div"), this);
			MarketCapitalizationTooltip = new Element("Market Capitalization Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[1]/div/img"), this);
			MarketCapitalizationTextbox = new TextBox("Market Capitalization TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[1]/input"), this);
			MinorityInterestLabel = new Element("Minority Interest Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[2]/div"), this);
			MinorityInterestTooltip = new Element("Minority Interest Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[2]/div/img"), this);
			MinorityInterestTextbox = new TextBox("Minority Interest TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[2]/input"), this);
			TotalDebtLabel = new Element("Total Debt Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[3]/div"), this);
			TotalDebtTooltip = new Element("Total Debt Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[3]/div/img"), this);
			TotalDebtTextbox = new TextBox("Total Debt TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[3]/input"), this);
			ShortTermInvestmentsLabel = new Element("Short Term Investments Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[4]/div"), this);
			ShortTermInvestmentsTooltip = new Element("Short Term Investments Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[4]/div/img"), this);
			ShortTermInvestmentsTextbox = new TextBox("Short Term Investments TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[4]/input"), this);
			PreferredEquityLabel = new Element("Preferred Equity Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[5]/div"), this);
			PreferredEquityTooltip = new Element("Preferred Equity Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[5]/div/img"), this);
			PreferredEquityTextbox = new TextBox("Preferred Equity TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[5]/input"), this);
			TotalEVLabel = new Element("Total EV Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[6]/div"), this);
			TotalEVTooltip = new Element("Total EV Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[6]/div/img"), this);
			TotalEVTextbox = new TextBox("Total EV TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[6]/input"), this);
			LongTermInvestmentsLabel = new Element("Long Term Investments Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[7]/div"), this);
			LongTermInvestmentsTooltip = new Element("Long Term Investments Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[7]/div/img"), this);
			LongTermInvestmentsTextbox = new TextBox("Long Term Investments TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[7]/input"), this);
			OperatingEVLabel = new Element("Operating EV Label", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[8]/div"), this);
			OperatingEVTooltip = new Element("Operating EV Tooltip", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[8]/div/img"), this);
			OperatingEVTextbox = new TextBox("Operating EV TextBox", By.xpath("(//*[@class='modal-body-item ng-star-inserted'])[8]/input"), this);
			MarketCapitalizationLabelR = new Element("Right Side - Market Capitalization Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[1]"), this);
			MinorityInterestLabelR = new Element("Right Side - Minority Interest Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[2]"), this);
			TotalDebtLabelR = new Element("Right Side - Total Debt Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[3]"), this);
			ShortTermInvestmentsLabelR = new Element("Right Side - Short Term Investments Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[4]"), this);
			PreferredEquityLabelR = new Element("Right Side - Preferred Equity Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[5]"), this);
			TotalEVLabelR = new Element("Right Side - Total EV Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[6]"), this);
			LongTermInvestmentsLabelR = new Element("Right Side - Long Term Investments Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[7]"), this);
			OperatingEVLabelR = new Element("Right Side - Operating EV Label", By.xpath("(//*[@class='chart-label ng-star-inserted'])[8]"), this);
			ReferenceDataName1_1 = new Element("Reference Data - Section 1 Name 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][1]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue1_1 = new Element("Reference Data - Section 1 Value 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][1]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-value ng-star-inserted']"), this);
			ReferenceDataName1_2 = new Element("Reference Data - Section 1 Name 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][1]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue1_2 = new Element("Reference Data - Section 1 Value 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][1]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-value ng-star-inserted']"), this);
			ReferenceDataName2_1 = new Element("Reference Data - Section 2 Name 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][2]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue2_1 = new Element("Reference Data - Section 2 Value 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][2]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-value ng-star-inserted']"), this);
			ReferenceDataName2_2 = new Element("Reference Data - Section 2 Name 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][2]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue2_2 = new Element("Reference Data - Section 2 Value 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][2]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-value ng-star-inserted']"), this);
			ReferenceDataName3_1 = new Element("Reference Data - Section 3 Name 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][3]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue3_1 = new Element("Reference Data - Section 3 Value 1", By.xpath("//*[@class='history-data-item ng-star-inserted'][3]//*[@class='history-data-item-con ng-star-inserted'][1]//*[@class='history-data-value ng-star-inserted']"), this);
			ReferenceDataName3_2 = new Element("Reference Data - Section 3 Name 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][3]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-name ng-star-inserted']"), this);
			ReferenceDataValue3_2 = new Element("Reference Data - Section 3 Value 2", By.xpath("//*[@class='history-data-item ng-star-inserted'][3]//*[@class='history-data-item-con ng-star-inserted'][2]//*[@class='history-data-value ng-star-inserted']"), this);
			EaseOfImplementation = new Element("Ease Of Implementation", By.xpath("//*[@id='myRange']"), this);
			EaseOfImplementation1 = new Element("Ease Of Implementation Level 1", By.xpath("//*[@class='eoi-body-col-slider-cont'][1]/div[2]"), this);
			EaseOfImplementation2 = new Element("Ease Of Implementation Level 2", By.xpath("//*[@class='eoi-body-col-slider-cont'][2]/div[2]"), this);
			EaseOfImplementation3 = new Element("Ease Of Implementation Level 3", By.xpath("//*[@class='eoi-body-col-slider-cont'][3]/div[2]"), this);
			EaseOfImplementation4 = new Element("Ease Of Implementation Level 4", By.xpath("//*[@class='eoi-body-col-slider-cont'][4]/div[2]"), this);
			EaseOfImplementation5 = new Element("Ease Of Implementation Level 5", By.xpath("//*[@class='eoi-body-col-slider-cont'][5]/div[2]"), this);
			EaseOfImplementation6 = new Element("Ease Of Implementation Level 6", By.xpath("//*[@class='eoi-body-col-slider-cont'][6]/div[2]"), this);
			Chart1 = new Element("Chart 1", By.xpath("(//*[@class='charts ng-star-inserted'])[1]"), this);
			Chart2 = new Element("Chart 2", By.xpath("(//*[@class='charts ng-star-inserted'])[2]"), this);
			Chart1Title = new Element("Chart 1 Title", By.xpath("(//*[@class='charts-header-title'])[1]"), this);
			Chart1SubTitle1 = new Element("Chart 1 Sub Title 1", By.xpath("(//*[@class='charts-header-subtitle-item'])[1]"), this);
			Chart1SubTitle2 = new Element("Chart 1 Sub Title 2", By.xpath("(//*[@class='charts-header-subtitle-item'])[2]"), this);
			SelectionTab1 = new Element("EV Impact Tab", By.xpath("(//*[@class='summary-tabs-item'])[1]"), this);
			SelectionTab2 = new Element("Prioritization Matrix Tab", By.xpath("(//*[@class='summary-tabs-item'])[2]"), this);
			SelectionTab3 = new Element("P&L Impact Tab", By.xpath("(//*[@class='summary-tabs-item'])[3]"), this);
			SelectionTab4 = new Element("FCF Impact Tab", By.xpath("(//*[@class='summary-tabs-item'])[4]"), this);
			CompanyCurrency = new Element("Company Currency", By.xpath("//*[@class='evIsoCode']"), this);
			CRLegendCircle = new Element("Cost Reduction Legend Circle", By.xpath("//*[@class='pnl-scatterchart-legend-item'][1]/div[1]"), this);
			CRLegendText = new Element("Cost Reduction Legend Text", By.xpath("(//*[@class='pnl-scatterchart-legend-item-text'])[1]"), this);
			RGLegendCircle = new Element("Revenue Growth Legend Circle", By.xpath("//*[@class='pnl-scatterchart-legend-item'][2]/div[1]"), this);
			RGLegendText = new Element("Revenue Growth Legend Text", By.xpath("(//*[@class='pnl-scatterchart-legend-item-text'])[2]"), this);
			AELegendCircle = new Element("Asset Efficiency Legend Circle", By.xpath("//*[@class='pnl-scatterchart-legend-item'][3]/div[1]"), this);
			AELegendText = new Element("Asset Efficiency Legend Text", By.xpath("(//*[@class='pnl-scatterchart-legend-item-text'])[3]"), this);
			
			/* Lsison, 20211019, SAVE button was removed in UI
			 * VCMSaveModal = new Element("VCM Save Modal",
			 * By.xpath("//*[@class='modal-vcmsave']"), this); VCMSaveModalHeader = new
			 * Element("VCM Save Modal Header",
			 * By.xpath("//*[@class='modal-vcmsave']//*[@class='modal-vcmsave-header']"),
			 * this); VCMSaveModalMessage = new Element("VCM Save Modal Message",
			 * By.xpath("//*[@class='modal-vcmsave']//*[@class='modal-vcmsave-message']"),
			 * this); VCMSaveModalSaveButton = new Element("VCM Save Modal Save Button",
			 * By.xpath("//*[@class='modal-vcmsave']//*[@class='modal-vcmsave-button']"),
			 * this); VCMSaveModalCloseButton = new Element("VCM Save Modal Close Button",
			 * By.xpath("//*[@class='button-close btn']"), this);
			 */
			
			VCMHelpIcon = new Element("VCM Help Icon", By.xpath("//*[@class='vcm-helpimage']"), this);
			VCMFootNote = new Element("VCM FootNote", By.xpath("//*[@class='selectvco-footnote ng-star-inserted']"), this);
			
		}
	}
	
	
	
}